fraudgroup/codingtest

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/윤아영/index.js

✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 2024.07.08
- n개의 정수로 구성된 배열을 받아 조건에 충족하는 정수들의 배열을 반환한다.
- 첫 번째 요소는 무조건 출력한다.
- 배열의 filter 메서드를 사용하여 조건에 맞는 정수들을 골라낸다.
```javascript
return arr.filter((num, i) => num > (arr[i - 1] || 0));
}
```
- O(n)

[윤아영] 큰 수 출력하기

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/윤아영/index.js
02. 1, 2차원 배열 탐색/02. 보이는 학생/윤아영/index.js

✔ 문제 제목: 보이는 학생
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 24.07.08
- n개의 정수로 이루어진 배열이 주어지고 조건을 충족하는 요소의 개수를 출력한다.
- 학생이 일렬로 서 있을 때 앞을 볼 수 있는 학생의 수를 구한다
- 앞에 서 잇는 사람보다 크면 보인다. 작거나 같다면 보이지 않는다.
- 학생 수(answer), 현재 최대 키(maxHeight) 변수를 선언한다.
- 배열을 순회하면서 현재 최대 키보다 크다면 학생 수를 1 늘려주고 현재 최대 키를 갱신한다.
```javascript
let maxHeight = 0;
if (arr[i] > maxHeight) {
maxHeight = arr[i];
answer += 1;
}
}
return answer;
}
```
- O(n)
- 변수를 하나 줄일 수 있는 방법을 생각해보았다.
- 오히려 복잡해 보이는 거 같기도?
```js
let maxHeight = 0;
return arr.filter((height) => {
if (height > maxHeight) {
maxHeight = height;
return true;
}
return false;
}).length;
}
```

[윤아영] 보이는 학생

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/정봉찬/index.js
02. 1, 2차원 배열 탐색/02. 보이는 학생/정봉찬/index.js

✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-09
- 첫 번째 수는 무조건 출력한다.
- `N(1<=N<=100)`개의 정수 배열을 입력 받고 자신의 앞 수보다 큰 수를 출력한다.
- 첫 번째 수를 `push`해서 넣고 두 번째 수부터 배열로 돌면서 직전 값과 비교하기.
```javascript
if (arr[i] > arr[i - 1]) {
}
}
return answer;
}
```
- O(n)
- 더 느낌있게 풀고 싶지만 딱히 생각나지 않는다.

[정봉찬] 2-1. 큰 수 출력하기

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/정봉찬/index.js
02. 1, 2차원 배열 탐색/02. 보이는 학생/정봉찬/index.js

✔ 문제 제목: 보이는 학생
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-09
- 앞선 index들의 값보다 큰 값일 때 count를 증가한다.
- 반복문을 돌면서 max 값을 저장해서 비교한다.
```javascript
let max = arr[0];
if (arr[i] <= max) {
continue;
}
max = arr[i];
answer++;
}
return answer;
}
```
- O(n)
- 재밌다. 아마도.

[정봉찬] 2-2. 보이는 학생

---

02. 1, 2차원 배열 탐색/03. 가위바위보/윤아영/index.js

✔ 문제 제목: 가위 바위 보
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 24-07-09
- 2개의 배열을 받아 가위바위보 결과 배열을 반환한다.
- 객체를 만들어 가위 바위 보를 이기는 값을 선언해줍니다.
- a 배열을 돌면서(map) 각 값이 같다면 D를 반환하고 객체의 값과 해당 인덱스의 b 요소의 값이 같다면 A를 다르다면 B를 반환한다.
```javascript
const win = {
1: 3,
2: 1,
3: 2,
};
return a.map((v, i) => (v === b[i] ? "D" : win[v] === b[i] ? "A" : "B"));
}
```
- O(n)

[윤아영] 2-3 가위 바위 보

---

02. 1, 2차원 배열 탐색/03. 가위바위보/이서인/index.js
02. 1, 2차원 배열 탐색/04. 점수 계산/이서인/index.js

✔ 문제 제목: 가위바위보 풀이
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 2024.07.10
- A와 B의 가위바위보 결과를 출력한다.
- 가위, 바위, 보의 정보는 1:가위, 2:바위, 3:보 이다.
- A가 이기면 A, B가 이기면 B, 비기면 D를 출력한다.
- map 메서드와 if문을 이용해 비기는 조건, A가 이기거나 지는 조건의 return 값을 정한다.
- join("\n")으로 출력값에 맞게 개행한다.
```javascript
return a
.map((_, index) => {
if (a[index] === b[index]) return "D";
if (
(a[index] === 2 && b[index] === 1) ||
(a[index] === 3 && b[index] === 2) ||
(a[index] === 1 && b[index] === 3)
)
return "A";
return "B";
})
.join("\n");
}
let a = [2, 3, 3, 1, 3];
let b = [1, 1, 2, 2, 3];
```
- O(n)
```javascript
const win = {
1: 3,
2: 1,
3: 2,
};
return a.map((v, i) => (v === b[i] ? "D" : win[v] === b[i] ? "A" : "B"));
}
```
- map에서 인덱스만 쓰인다면 첫 번째 매개변수를 _(빈 값)으로 두자

[서인] 2-3.가위바위보

---

02. 1, 2차원 배열 탐색/03. 가위바위보/정봉찬/index.js

✔ 문제 제목: 가위바위보
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-10
- 가위: 1, 바위: 2, 보: 3
- 이긴 사람 출력, 비길 경우 D 출력
- 객체로 이기는 케이스를 만든다.
- 비기는 경우를 먼저 계산한다.
- a의 이기는 케이스와 b의 값이 같다면 승자는 A 아닐 경우 B가 승자.
```javascript
const winCase = {
1: 3,
2: 1,
3: 2,
};
function getWinner(a, b) {
if (a === b) {
return 'D';
}
return winCase[a] === b ? 'A' : 'B';
}
for (let i = 0; i < a.length; i++) {
answer += getWinner(a[i], b[i]);
}
return answer;
}
let a = [2, 3, 3, 1, 3];
let b = [1, 1, 2, 2, 3];
```
- O(n)
- 이기는 경우를 프로퍼티로 만들면 복잡한 조건문을 작성하지 않아도 된다.

[정봉찬] 2-3. 가위바위보

---

02. 1, 2차원 배열 탐색/04. 점수 계산/윤아영/index.js

✔ 문제 제목: 점수 계산
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 24-07-09
- 0과 1로 이루어진 n개의 배열이 주어집니다.
- 0: 틀린 문제, 1: 맞춘 문제
- 연속적으로 맞추면 가산점이 있습니다. 연속 2번째는 2점, 3번째는 3점, ..., n번째는 n점
- 총 점수를 반환합니다.
- 총점(answer), 점수(score) 변수 선언
- for문을 돌면서 0을 만나면 score를 1로 초기화하고 아니라면 총점에 현재 scroe를 추가하고 score를 1 증가시킨다.
```javascript
let score = 1;
if (arr[i] === 0) {
score = 1;
continue;
}
answer += score;
score += 1;
}
return answer;
}
```
O(n)
```js
let score = 1;
const scores = arr.map(v => {
if (v === 0) {
score = 1;
return v;
}
return score++;
})
return scores.reduce((acc, cur) => acc + cur, 0);
}
```
- 왠지 더 좋은 방법이 있을 것만 같은 느낌

[윤아영] 2-4 점수 계산

---

02. 1, 2차원 배열 탐색/04. 점수 계산/이서인/index.js

✔ 문제 제목: 점수 계산
✔ 문제 유형: 구현
✔ 문제 풀이 날짜: 2024.07.11
- OX 퀴즈 결과가 맞은 문제 1, 틀린 문제 0로 표시될 때 맞은 문제를 1로 계산해 점수를 구해야 한다.
- 연속으로 맞은 문제는 그 문제까지 연속된 1의 개수만큼 점수를 받는다.
- forEach 메서드를 사용한다.
- 요소가 1일 때 이전 요소가 0일 때와 0이 아닐 때로 나눠 count 변수에 재할당한다.
- count의 누적값을 반환한다.
```javascript
let count = 0;
let sum = 0;
arr.forEach((el, index) => {
if (el === 1) {
if (index === 0 || arr[index - 1] === 0) count = 1;
if (arr[index - 1] === 1) count++;
sum += count;
}
});
return sum;
}
```
O(n)
- 조건을 설정하는 게 좀 어려웠다.
```javascript
let score = 1;
if (arr[i] === 0) {
score = 1;
continue;
}
answer += score;
score += 1;
}
return answer;
}
```
```javascript
let point = 1;
for (let i = …
```

[서인] 2-4. 점수 계산

---

02. 1, 2차원 배열 탐색/02. 보이는 학생/김유경/index.js

✔ 문제 제목: 보이는 학생
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-11
- N(1<=N<=1000)의 배열이 주어진다.
- 이전 index 값들보다 크면 더해지고, 작으면 더해지지 않는다. 
- 첫 번째 숫자는 무조건 보이기 때문에 그 학생을 기준으로 taller을 넣어주고, 이후 기존의 taller보다 큰 숫자가 있으면 count를 더해줌과 동시에 taller을 갱신해줬다.
```javascript
let taller = arr[0];
if (taller < arr[i]) {
taller = arr[i];
answer++;
}
}
return answer;
}
let arr = [130, 135, 148, 140, 145, 150, 150, 153];
```
O(N)
- 다른 방법으로 풀어봐도 좋을 것 같다. 너무 쉬운 방법만 골라서 가는 느낌이 든다.

[김유경] 2-2 보이는 학생

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/김유경/index.js

✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-11
- N(1<=N<=100)개의 정수를 입력받아, 자신의 바로 앞 수보다 큰 수만 출력
- 첫 번째 수는 무조건 출력 (비교할 앞 수가 없기 때문)
- 첫 번째 수는 무조건 출력해야 해서, 먼저 answer에 push 해주고 for문을 돌렸다.
```javascript
if (arr[i] > arr[i - 1]) {
}
}
return answer;
}
```
- O(N)
: 입력된 배열의 길이가 N이면, for 루프가 N번 반복되기 때문
- 가장 직관적으로 떠오르는 방법으로 풀었는데, 다른 방법도 알고 있으면 좋을 것 같다.

[김유경] 2-1 큰 수 출력하기

---

02. 1, 2차원 배열 탐색/05. 등수구하기/윤아영/index.js

✔ 문제 제목: 등수구하기
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 24-07-10
- n개의 배열이 주어지면 n개의 배열로 반환
- 각 학생의 등수를 입력된 순서대로 출력
- 같은 점수가 있는 경우 높은 등수로 동일 처리
- 1등이 3명이라면 그 다음 학생은 4등이 된다.
- 배열을 정렬하여 해당 배열값과 인덱스 정보(등수)를 가지는 Map 객체를 생성
- filter 메서드를 사용하여 동일한 점수라면 높은 인덱스만 남도록 구현
- 주어진 배열을 map하면서 Map객체에서 값(등수)를 가져온다
```javascript
const sortMap = new Map(
[...arr]
.sort((a, b) => b - a)
.map((v, i) => [v, i + 1])
.filter((v, i, array) => v[0] !== array[i - 1]?.[0])
);
return arr.map((number) => sortMap.get(number));
}
```
O(n)
- 제일 먼저 생각난 풀이
```javascript
const sortArray = [...arr].sort((a, b) => b - a);
return arr.map(number => sortArray.indexOf(number) + 1);
}
```
- sort는 원본 배열을 변경하기 때문에 배열을 복사해서 사용했다.
- 시간복잡도를 줄이기 위해서 Map을 사용해보았다.

[윤아영] 2-5 등수구하기

---

.github/CODEOWNERS
02. 1, 2차원 배열 탐색/05. 등수구하기/이서인/index.js

* 코드 리뷰어 자동 지정 기능 추가했습니다.
✔ 문제 제목: 등수구하기
✔ 문제 유형: 배열
✔ 문제 풀이 날짜:2024.07.12
- 정해진 배열의 등수를 구해야 한다.
- 같은 등수가 2개 이상일 때 n개 다음 등수가 표시돼야 한다.
- arr를 복사해 내림차순으로 정렬하고, sort로 내림차순 정렬한다.
- map 메서드를 사용해 arr 요소를 복사한 배열의 인덱스로 치환한다.
```javascript
let copiedArr = [...arr].sort((a, b) => b - a);
return arr.map((el) => copiedArr.indexOf(el) + 1);
}
```
O(nlogn)
-
```javascript
const sortedArr = [...arr].sort((a, b) => b - a);
const rankMap = new Map();
sortedArr.forEach((el, index) => {
if (!rankMap.has(el)) {
rankMap.set(el, index + 1);
}
});
return arr.map(el => rankMap.get(el));
}
```
```javascript
const sortMap = new Map(
[...arr]
.sort((a, b) => b - a)
.map((v, i) => [v, i + 1])
.filter((v, i, array) => v[0] !== array[i - …
```

[서인] 2-5. 등수구하기

---

02. 1, 2차원 배열 탐색/03. 가위바위보/김유경/index.js

✔ 문제 제목: 가위 바위 
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 2024-07-12
- 가위 바위 보 결과를 출력한다
- 가위 : 1, 바위 : 2, 보 : 3 
- A가 이기면 A 출력, B가 이기면 B 출력, 비기면 D를 출력한다.
- 승자를 반환하는 함수를 따로 만들면 좋을 것 같다고 생각했다
- 분기가 많기 때문에 if문 말고 switch문을 사용했다.
- 
```javascript
function checkVictory(a, b) {
if (a === b) {
return "D";
}
if ((a === 1 && b === 3) || (a === 2 && b === 1) || (a === 3 && b === 2)) {
return "A";
} else {
return "B";
}
}
for (let i = 0; i < a.length; i++) {
answer.push(checkVictory(a[i], b[i]));
}
return answer.join("\n");
}
let a = [2, 3, 3, 1, 3];
let b = [1, 1, 2, 2, 3];
```
O(N)
- 코드가 너무 길고, A가 이기는 분기를 하나의 조건문 안에서 관리하는 게 나을 것 같아서 굳이 switch문을 사용하지 않음
- 훨씬 간결하고 가독성도 좋아진 것 같다.
```javascript
function …
```

[유경] 2-3 가위 바위 보

---

02. 1, 2차원 배열 탐색/06. 격자판 최대합/이서인/index.js

✔ 문제 제목: 격자판 최대합
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 2024.07.13
- N*N의 격자판의 각 행의 합, 각 열의 합, 대각선의 합 중 최대값을 구해야 한다.
- 각 행의 합, 각 열의 합, 대각선의 합을 구하고, 이 중 최대값을 구한다.
```javascript
const maxWidth = Math.max(
...arr.map((el) => el.reduce((acc, cur) => acc + cur), 0)
);
const heightSumArr = new Array(arr[0].length).fill(0);
arr.forEach((el) => {
el.forEach((el, index) => {
heightSumArr[index] += el;
});
});
const maxHeight = Math.max(...heightSumArr);
const leftDiagonal = arr
.map((el, index) => el[index])
.reduce((acc, cur) => acc + cur, 0);
const rightDiagonal = arr
.map((el, index) => el[arr[0].length - index - 1])
.reduce((acc, cur) => acc + cur, 0);
return answer = Math.max(maxWidth, maxHeight, leftDiagonal, rightDiagonal);
}
```
O(n * m)
- 열의 …

[서인] 2-6. 격자판 최대합

---

02. 1, 2차원 배열 탐색/07. 봉우리/윤아영/index.js

✔ 문제 제목: 봉우리
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 24-07-13
- n * n 배열이 주어집니다.
- 자신의 상하좌우 숫자보다 큰 숫자는 봉우리입니다.
- 봉우리의 개수를 반환합니다.
- 격자의 가장자리는 0으로 초기화 되었다고 가정합니다.
- 이중 for문을 돕니다.
- 상하좌우값을 비교해서 작다면 continue문으로 실행 흐름을 제어
- 옵셔널체이닝을 이용해서 존재하는 값인지를 확인한다.
```javascript
for (let j = 0; j < arr.length; j++) {
if (arr[i][j] < arr[i - 1]?.[j]) continue;
if (arr[i][j] < arr[i + 1]?.[j]) continue;
if (arr[i][j] < arr[i]?.[j - 1]) continue;
if (arr[i][j] < arr[i]?.[j + 1]) continue;
answer++;
}
}
return answer;
}
```
O(n<sup>2</sup>)
- 배열도 결국 객체다?

[윤아영] 2-7 봉우리

---

02. 1, 2차원 배열 탐색/07. 봉우리/이서인/index.js

✔ 문제 제목: 봉우리
✔ 문제 유형: 배열
✔ 문제 풀이 날짜: 2024.07.14
- N*N 격자판에서 각 격자가 상하좌우 격자의 숫자보다 크면 봉우리로 계산한다.
- directions로 상하좌우 인덱스를 배열로 만든다.
- forEach 메서드를 사용해 각 격자를 순회한다.
- every 메서드를 사용해 각 격자가 상하좌우 격자의 숫자보다 큰지 확인한다.
```javascript
const directions = [
[-1, 0],
[1, 0],
[0, -1],
[0, 1],
];
arr.forEach((row, i) => {
row.forEach((el, j) => {
const isPeak = directions.every(([directionX, directionY]) => {
const newI = i + directionX;
const newJ = j + directionY;
if (newI < 0 || newI >= arr.length || newJ < 0 || newJ >= arr.length) {
return true;
}
return el > arr[newI][newJ];
});
if (isPeak) answer++;
});
});
return answer;
}
```
O(n^2)
- 문제 접근 방식을 생각하는 게 어려웠다.
```javascript
for (let j = …
```

[서인] 2-7. 봉우리

---

02. 1, 2차원 배열 탐색/06. 격자판 최대합/정봉찬/index.js

✔ 문제 제목: 격자판 최대합
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-13
- N * N 격자판이 주어질 때 각 행의 합, 각 열의 합, 두 대각선의 합 중 가장 큰 합을 출력한다.
- 좌측 상단 -> 우측 하단 대각선: [0, 0] + [1, 1] + [2 + 2] + ...
- 우측 상단 -> 좌측 하단 대각선: [0, N] + [1, N - 1] + [2, N - 2] + ...
- 각 열의 합: [0, 0] + [1, 0] + [2, 0] + [3, 0] + ...
- 각 행의 합: [0, 0] + [0, 1] + [0, 2] + [0, 3] + ...
```javascript
const N = arr.length;
let leftTopDiagonalSum = 0;
let rightTopDiagonalSum = 0;
for (let i = 0; i < N; i++) {
leftTopDiagonalSum += arr[i][i];
rightTopDiagonalSum += arr[i][N - 1 - i];
}
let columnSumMax = 0;
let rowSumMax = 0;
for (let i = 0; i < N; i++) {
let columnSum = 0;
let rowSum = 0;
for (let j = 0; j < N; j++) {
columnSum += arr[j][i];
rowSum += arr[i][j];
}
if (columnSumMax < …
```

[정봉찬] 2-6.격자판 최대합

---

02. 1, 2차원 배열 탐색/07. 봉우리/정봉찬/index.js

✔ 문제 제목: 봉우리
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-13
- 각 격자의 값이 상하좌우 숫자보다 클 때 봉우리.
- 격자의 가장자리는 0으로 계산.
- [0, 2]의 봉우리 여부 확인하는 방법: [0, 1], [0, 3], [1, 2]의 값을 확인.
- 상하좌우 값을 구해서 현재 봉우리와 값을 비교.
```javascript
for (let j = 0; j < arr.length; j++) {
const current = arr[i][j];
const top = arr[i - 1]?.[j] || 0;
const down = arr[i + 1]?.[j] || 0;
const left = arr[i][j - 1] || 0;
const right = arr[i][j + 1] || 0;
if (current !== Math.max(current, top, down, left, right)) {
continue;
}
answer++;
}
}
return answer;
}
let arr = [
[5, 3, 7, 2, 3],
[3, 7, 1, 6, 1],
[7, 2, 5, 3, 4],
[4, 3, 6, 4, 1],
[8, 7, 3, 5, 2],
];
```
- O(n^2)
- 배고파요.
- 맛있고 건강한 음식 잘 챙겨드세요. 🍚

[정봉찬] 2-7.봉우리

---

03. 문자열 탐색/01. 회문문자열/이서인/index.js

✔ 문제 제목: 회문문자열
✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 2024.07.15
- 회문문자열: 문자열을 거꾸로 뒤집어도 값이 같다.
- 회문문자열이면 "YES" / 아니면 "NO"
- 대소문자를 상관하지 않는다.
- 문자열을 스프레드 문법으로 새 배열로 복사한다.
- reverse().join() 메서드를 사용해 문자열을 뒤집는다.
- toUpperCase() 메서드를 사용해 모든 문자를 대문자로 변환한다.
```javascript
return s.toUpperCase() === [...s].reverse().join("").toUpperCase()
? "YES"
: "NO";
}
```
O(n)
```javascript
```
- 카카오에서 문자열 문제를 자주 낸다고 합니다. 화이팅!

[서인] 3-1. 회문문자열

---

03. 문자열 탐색/01. 회문문자열/정봉찬/index.js

✔ 문제 제목: 회문문자열
✔ 문제 풀이 날짜: 2024-07-15
- 앞에서 읽을 때나 뒤에서 읽을 때나 같은 문자열을 회문 문자열이라고 한다.
- 회문 문자열이면 YES, 아니면 NO를 출력한다.
- 대소문자를 구분하지 않는다.
- 문자열을 배열로 변환 후 Array.prototype.reverse()를 사용해서 거꾸로 돌린 후 문자열로 변환한다.
- 원본 문자열과 거꾸로 돌린 문자열을 소문자 변환 또는 대문자 변환 후 비교한다.
```javascript
const reverse = [...s].reverse().join('');
if (s.toUpperCase() !== reverse.toUpperCase()) {
answer = 'No';
}
return answer;
}
let str = 'goooG';
```
```js
function solution2(s) {
const LENGTH = s.length;
for (let i = 0; i < Math.trunc(LENGTH / 2); i++) {
const current = s[i];
const reverse = s[LENGTH - 1 - i];
if (current.toUpperCase() !== reverse.toUpperCase()) {
answer = 'No';
break;
}
}
return answer;
}
console.log('solution2: …
```

[정봉찬] 3-1. 회문문자열

---

02. 1, 2차원 배열 탐색/04. 점수 계산/김유경/index.js
02. 1, 2차원 배열 탐색/05. 등수구하기/김유경/index.js

**✔ 문제 제목: 등수 구하기**
**✔ 문제 유형: 배열 탐색**
**✔ 문제 풀이 날짜: 2024-07-15**
- N(1<=N<=100)명의 학생의 국어 점수가 입력되면 각 학생의 등수를 입력된 순서대로 출력
- 내림차순으로 입력받은 배열을 정렬한다.
- 정렬된 배열을 순회하며 아래와 같은 과정을 반복한다.
- 가장 높은 점수 (정렬되었으니 i가 될 듯)
- 동점자 수 구하기
- 동점자인 애들한테 현재 등수 넣어주기
- 반복문 횟수에서 동점자 수 차감하기
- 현재 등수에 동점자 수 더하기
```jsx
let n = arr.length; // 학생 수
let sortedScores = [...arr].sort((a, b) => b - a);
let ranks = new Array(n); // 학생들 등수 반환할 배열 생성
let currentRank = 1; // 현재 등수 초기화
for (let i = 0; i < n; ) {
let score = sortedScores[i]; // 현재 점수 저장
let count = 0; // 동점자 변수
// 현재 점수랑 동점인 학생 세기
while (i + count < n && sortedScores[i + count] === score) {
count++;
}
// 동일한 점수를 가진 애들한테, 현재 등수 할당하기
for (let j = 0; j < n; j++) {
if (arr[j] === score) {
ranks[j] = currentRank;
}
}
// 다음 점수로 이동하기 전에, 동점자 수만큼을 …
```

[김유경] 2-5 등수 구하기

---

02. 1, 2차원 배열 탐색/04. 점수 계산/김유경/index.js

**✔ 문제 제목: 점수 계산**
**✔ 문제 유형: 배열 탐색**
**✔ 문제 풀이 날짜: 2024-07-15**
- 1이 연속으로 나올 수록 가산점이 붙고, 틀린 문제의 경우 0점이다.
- 0을 기준으로 나누어 연속된 1을 가진 배열만 남긴 후, 각 배열의 길이에 따라 값을 더하면 될 것 같다.
```jsx
let totalScore = 0;
let correctArray = arr
.join("")
.split("0")
.map((subArr) => subArr.split("").map(Number))
.filter((subArr) => subArr.every((num) => num === 1));
correctArray.forEach((array) =>
array.forEach((_, index) => (totalScore += index + 1))
);
return totalScore;
}
let arr = [1, 0, 1, 1, 1, 0, 0, 1, 1, 0];
```
**O(N)**
- 처음에는 변수를 하나 정의해서 풀어볼까 싶기도 했지만, 최대한 자바스크립트의 내장 메서드를 활용할 수 있는 문제 풀이를 고민해보았다.
- 알고리즘을 설계한 것에 비해 내장 메서드를 바로바로 떠올리지 못했는데, 조금 더 익숙해질 필요가 있을 것 같다.

[김유경] 2-4 점수 계산

---

03. 문자열 탐색/01. 회문문자열/윤아영/index.js

✔ 문제 제목: 회문문자열
✔ 문제 풀이 날짜: 24-07-15
- 회문 문자열이면 YES 아니면 NO 출력
- 회문 문자열: 앞에서 읽을 때나 뒤에서 읽을 때나 같은 문자열
- 대소문자는 구분하지 않는다.
- 문자열을 소문자로 바꾼다
- 반복문을 문자 길이의 반만큼 돌면서 각 인덱스에 해당하는 문자를 대칭하는 문자와 비교한다.
```javascript
const lowerString = s.toLowerCase();
for (let i = 0; i < s.length / 2; i++) {
if (lowerString[i] !== lowerString[lowerString.length - (i + 1)]) {
return 'NO';
}
}
return 'YES';
}
```
O(n)
- 문자열을 뒤집어 비교
```javascript
const reverseString = [...s].reverse((a, b) => a < b).join("");
return s.toLowerCase() === reverseString.toLocaleLowerCase() ? "YES" : "NO";
}
```

[윤아영] 3-1 회문문자열

---

03. 문자열 탐색/02. 유효한 팰린드롬/이서인/index.js

✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 2024.07.16
- 팰린드롬: 앞에서 읽거나 뒤에서 읽거나 같은 문자열
- 입력 문자열이 팰린드롬이면 "YES, 아니면 "NO"를 출력해야 한다.
- 대소문자를 구분하지 않고, 알파벳 이외 문자는 무시한다.
- 소문자 알파벳 배열을 만든다.
- 인수를 toLowerCase() 메서드로 소문자로 변환한 뒤 소문자 알파벳인지 filter한 후 문자열로 join()한다.
- reverse 메서드를 사용해 팰린드롬인지 확인한다.
```javascript
const alphabet = Array.from({ length: 26 }, (v, i) =>
String.fromCharCode(i + 97)
);
Array(26)
.fill()
.map((v, i) => String.fromCharCode(i + 97));
const filteredS = [...s.toLowerCase()]
.filter((el) => alphabet.includes(el))
.join("");
return filteredS === [...filteredS].reverse().join("") ? "YES" : "NO";
}
```
O(n)
- 처음에 알파벳을 하드 코딩했으나 아스키 코드를 활용해 알파벳 배열을 생성했다.
```javascript
const formattedStr = …
```

[서인] 3-2. 유효한 팰린드롬

---

03. 문자열 탐색/02. 유효한 팰린드롬/윤아영/index.js

✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 24-07-16
- 문자열이 팰린드롬이면 "YES", 아니면 "NO"
- 팰린드롬: 아펭서 읽을 때나 뒤에서 읽을 때나 같은 문자열
- 알파벳만 가지고 검사한다.
- 대소문자를 구분하지 않는다.
- 알파벳만으로 구성된 문자열로 재구성
- 반복문을 문자열의 길이의 반만큼 돌면서 해당 문자열과 대칭되는 문자열을 비교
```javascript
const string = s.toUpperCase().replaceAll(/[^A-Z]/g, "");
for (let i = 0; i < string.length / 2; i++) {
if (string[i] !== string[string.length - i - 1]) {
return "NO";
}
}
return "YES";
}
```
O(n)
- 입력 설명에 공백이 없는 문자열이 주어진다고 하였으나 예제 문자열에 공백이 존재한다.
- 정규표현식에서 ^가 대괄호 밖에 있으면 시작을 의미하고 대괄호 안에 있으면 not을 의미한다.

[윤아영] 3-2 유효한 팰린드롬

---

03. 문자열 탐색/02. 유효한 팰린드롬/정봉찬/index.js

✔ 문제 풀이 날짜: 2024-07-16
- 앞에서 읽을 때나 뒤에서 읽을 때나 같은 문자열을 팰린드롬이라고 한다.
- 팰린드롬이면 YES, 아니면 NO를 출력한다.
- 알파벳만 가지고 검사하며 대소문자를 구분하지 않는다. 알파벳 이외의 문자들은 무시한다.
- 매개변수로 넘어온 문자열을 소문자 변환 또는 대문자 변환한다.
- `replaceAll`을 통해서 알파벳만 남긴다.
- 배열로 변환 후 reverse를 통해서 비교한다.
```javascript
const formattedStr = s.toLowerCase().replaceAll(/[^a-z]/g, '');
const reversedStr = [...formattedStr].reverse().join('');
if (formattedStr !== reversedStr) {
answer = 'NO';
}
return answer;
}
let str = 'found7, time: study; Yduts; emit, 7Dnuof';
```
```js
const alphabets = {
a: 'a',
b: 'b',
c: 'c',
d: 'd',
e: 'e',
f: 'f',
g: 'g',
h: 'h',
i: 'i',
j: 'j',
k: 'k',
l: 'l',
m: 'm',
n: 'n',
o: 'o',
p: 'p',
q: 'q',
r: 'r',
s: 's',
t: 't',
u: …
```

[정봉찬] 3-2. 유효한 팰린드롬

---

02. 1, 2차원 배열 탐색/06. 격자판 최대합/김유경/index.js

**✔ 문제 제목: 격자판 최대합**
**✔ 문제 유형: 배열 탐색**
**✔ 문제 풀이 날짜: 2024-07-17**
- 각 행의 합, 각 열의 합, 두 대각선의 합 중 가 장 큰 합을 출력
- 행과 열의 합은 이중 for문 돌리면서 더하면 될 듯
- 대각선
- 오른쪽으로 내려가는 대각선은 i와 j가 모두 같으면 됨
- 왼쪽으로 내려가는 대각선은 i와 j의 합이 5이면 됨
- 더해뒀던 걸 배열로 저장했다가 Math.max하면 될 것 같다.
```css
[0 0] [0 1] [0 2] [0 3] [0 4] [0 5]
[1 0] [1 1] [1 2] [1 3] [1 4] [1 5]
[2 0] [2 1] [2 2] [2 3] [2 4] [2 5]
[3 0] [3 1] [3 2] [3 3] [3 4] [3 5]
[4 0] [4 1] [4 2] [4 3] [4 4] [4 5]
[5 0] [5 1] [5 2] [5 3] [5 4] [5 5]
```
```jsx
const L = arr.length;
let maxSum = 0;
let rowSum, columnSum;
let toLeftCrossSum = 0;
let toRightCrossSum = 0;
// 행과 열의 합 구하기
for (let i = 0; i < L; i++) {
rowSum = 0;
columnSum = 0;
for (let j = 0; j < L; j++) {
rowSum += arr[i][j];
columnSum += arr[j][i];
// 대각선 합 구하기
if (i === j) { …
```

[김유경] 2-6 격자판 최대합

---

03. 문자열 탐색/03. 숫자만 추출/이서인/index.js

✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 2024.07.17
- 숫자와 문자가 섞여있는 문자열 중 숫자만 추출해서 순서대로 자연수를 만들어야 한다.
- 정규식과 replaceAll 메서드를 사용해 문자열 중 숫자만 추출한다.
- 삼항 연산자를 사용해 formatting한 문자열 맨 앞이 0일 때 0이후 문자열만 반환하게 한다.
```javascript
const formattedStr = str.replaceAll(/[^0-9]/g, "");
return formattedStr[0] === "0" ? formattedStr.slice(1) : formattedStr;
}
```
O(n)
```javascript
return +str.replaceAll(/\D/gi, '');
}
```
- /[^0-9/]g, /[^a-z/]g 정규식은 진짜 많이 사용한다.
- 다들 감기 조심하세요오오오오오오

[서인] 3-3. 숫자만 추출

---

02. 1, 2차원 배열 탐색/07. 봉우리/김유경/index.js

✔ 문제 제목: 봉우리
✔ 문제 유형: 배열 탐색
✔ 문제 풀이 날짜: 2024-07-17
- 상 하 좌우의 값보다 큰 값이 몇 개 있는지 출력하기
- 이때 상 하 좌 우가 모두 있는 것이 아니기 때문에 조건부 처리를 해줘야 함
- 상하좌우의 관계성을 먼저 파악해야 한다.
- 좌 : [ i ] [ j -1 ]
** 좌가 없는 경우 j가 0인 경우
- 우 : [ i ] [ j +1 ]
** 우가 없는 경우 j가 arr.length -1인 경우
- 상 : [ i - 1 ]  [ j ]
** 상이 없는 경우 i가 0인 경우 
- 하 : [ i + 1 ] [ j ]
** 하가 없는 경우 i가 arr.length -1인 경우
```javascript
let L = arr.length;
let maxCount = 0;
for (let i = 0; i < L; i++) {
for (let j = 0; j < L; j++) {
let current = arr[i][j];
let top = i > 0 ? arr[i - 1][j] : 0;
let bottom = i < L - 1 ? arr[i + 1][j] : 0;
let left = j > 0 ? arr[i][j - 1] : 0;
let right = j < L - 1 ? arr[i][j + 1] : 0;
if (
current > top &&
current > bottom &&
current > left &&
current > right
) {
maxCount++;
}
}
}
return maxCount;
}
let arr = …
```

[김유경] 2-7 봉우리

---

03. 문자열 탐색/03. 숫자만 추출/윤아영/index.js

✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 24-07-27
- 문자와 숫자가 섞여있는 문자열이 주어진다
- 숫자만 추출하여 그 순서대로 자연수를 만든다.
- replaceAll 메서드를 사용하여 숫자를 제외한 문자를 제거
- 숫자타입으로 변경하여 앞에 있는 0들을 제거
```javascript
return +str.replaceAll(/\D/gi, '');
}
```
O(n)
```javascript
return +[...str].filter(s => !Number.isNaN(+s)).join('');
}
```
- 문자열을 하면서 정규표현식을 검색하게 된다. 🤣

[윤아영] 3-3 숫자만 추출

---

03. 문자열 탐색/03. 숫자만 추출/정봉찬/index.js

✔ 문제 풀이 날짜: 2024-07-17
- 숫자만 추출해서 그 순서대로 자연수를 만든다.
- 정규식을 활용해서 숫자만 남긴다.
- `parseInt` 메서드를 활용해서 자연수로 변환한다.
```javascript
answer = parseInt(str.replaceAll(/[^0-9]/g, ''));
return answer;
}
let str = 'g0en2T0s8eSoft';
```
- O(n)
- 오늘 집무실 처음 왔어요. 서울대점 좋아요 😁
- 맛있는 거 많이 드시고 건강하세요!🍀
- `Number.parseInt()`와 `parseInt()`는 같은 동작을 수행한다고 합니다.
- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt

[정봉찬] 3-3. 숫자만 추출

---

03. 문자열 탐색/02. 유효한 팰린드롬/김유경/index.js

✔ 문제 풀이 날짜: 2024-07-18
- 회문 문자열인지 확인하는 문제와 동일하나, 알파벳만 가지고 검사한다는 제한조건이 달렸다.
- 알파벳을 사전에 정의하고, 소문자로 변환한 후 그걸 확인하는 방법이 있을 것 같다.
- 두번째 풀이) 알파벳을 정의하지 않고 푸는 방법으로는 정규식으로 우선 알파벳만 남긴 후, while문으로 증감식을 다르게 하면 되지 않을까 하는 생각이 들었다.
```jsx
const onlyAlphabet = s.toLowerCase().replace(/[^a-z]/g, "");
let backward = 0;
let forward = onlyAlphabet.length - 1;
while (backward < forward) {
if (onlyAlphabet[backward] !== onlyAlphabet[forward]) {
return "No";
}
backward++;
forward--;
}
return "YES";
}
```
```jsx
const ALPHABET = [
"a",
"b",
"c",
"d",
"e",
"f",
"g",
"h",
"i",
"j",
"k",
"l",
"m",
"n",
"o",
"p",
"q",
"r",
"s",
"t",
"u",
"v",
"w",
"x",
"y",
"z",
];
let L = s.length;
let strArray = new Array({ length: L });
let …
```

[김유경] 3-2 유효한 팰린드롬

---

01. 기본문제 풀이/01. 세 수 중 최솟값/김보경/index.js
01. 기본문제 풀이/02. 삼각형 판별하기/김보경/index.js
01. 기본문제 풀이/03. 연필개수/김보경/index.js
01. 기본문제 풀이/04. 1부터 N까지의 합/김보경/index.js
01. 기본문제 풀이/05. 최솟값 구하기/김보경/index.js
01. 기본문제 풀이/06. 홀수/김보경/index.js
01. 기본문제 풀이/07. 10부제/김보경/index.js
01. 기본문제 풀이/08. 일곱난쟁이/김보경/index.js
01. 기본문제 풀이/09. A를 #으로/김보경/index.js
01. 기본문제 풀이/10. 문자 찾기/김보경/index.js
01. 기본문제 풀이/11. 대문자 찾기/김보경/index.js
01. 기본문제 풀이/12. 대문자로 통일/김보경/index.js
01. 기본문제 풀이/14. 가장 긴 문자열/김보경/index.js
01. 기본문제 풀이/15. 가운데 문자 출력/김보경/index.js
01. 기본문제 풀이/16. 중복문자제거/김보경/index.js
01. 기본문제 풀이/17. 중복단어제거/김보경/index.js

✔ 문제 제목:
✔ 문제 유형:
✔ 문제 풀이 날짜:
- 0단계 수준이라 한번에 풀어 올립니다!
- 기본 메서드만 활용해서 풀었습니다
```javascript
// 여기에 코드 작성해주세요 !
```
-
```javascript
```
- 메서드 많이 까먹은거같은데 다시 머슬메모리 살려보겠읍니다~
- 금방 섹션3까지 뽑아서 올릴게요!

[김보경] 1-워밍업

---

03. 문자열 탐색/04. 가장 짧은 문자거리/이서인/index.js

✔ 문제 제목: 가장 짧은 문자거리
✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 2024.07.18
- 한 개의 문자열 s와 문자 t가 주어질 때 문자열 s 내 문자가 t와 떨어진 최소 거리를 출력해야 한다.
(1시간 정도 고민했는데 최소거리를 못 구해서 다른 풀이 참고했습니다.)
- 각 위치에서 t까지 최단 거리를 지정할 배열을 초기화한다.
- 왼쪽에서 오른쪽으로 순회하면서 문자열의 요소가 t와 같을 때의 인덱스를 마지막 위치로 저장한다.
- 현재 위치에서 t의 마지막 위치까지의 거리를 저장한다.
- 오른쪽에서 왼쪽으로 순회할 때도 같은 과정을 거친다.
- 두 순회로 나온 거리 중 최소값을 distances 배열에 저장한다.
```javascript
const L = s.length;
const distances = new Array(L).fill(Infinity);
let lastPosition = -Infinity;
for (let i = 0; i < L; i++) {
if (s[i] === t) {
lastPosition = i;
}
distances[i] = i - lastPosition;
}
lastPosition = Infinity;
for (let i = L - 1; i >= 0; i--) {
if (s[i] === t) {
lastPosition = i;
}
distances[i] = Math.min(distances[i], lastPosition - i);
}
return distances;
}
```
O(n)
- 최소 거리를 구하는 로직을 …

[서인] 3-4. 가장 짧은 문자거리

---

03. 문자열 탐색/04. 가장 짧은 문자거리/윤아영/index.js

✔ 문제 제목: 가장 짧은 문자거리
✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 24-07-18
- 한 개의 문자열 s와 문자 t가 주어진다
- s의 각 문자가 문자 t와 떨어진 최소 거리를 출력
- answer를 문자열 s와 동일한 length를 가지고 0으로 채워진 배열로 초기화 한다.
- 각 문자의 이전 t index(tPrevIndex)와 다음 t index(tNextIndex)를 기록
- tNextIndex와 현재 인덱스가 같을 때 tPrevIndex, tNextIndex를 업데이트
- 각 인덱스와 현재 위치와의 거리(절대값)을 비교해서 작은 값을 answer[i]에 업데이트
- tPrevIndex, tNextIndex가 없을 경우를 있는 값에서 인덱스를 뺀 절대값을 적용
```javascript
let answer = new Array(s.length).fill(0);
let tPrevIndex = -1;
let tNextIndex = s.indexOf(t);
if (i === tNextIndex) {
tPrevIndex = i;
tNextIndex = s.indexOf(t, i + 1);
continue;
}
if (tPrevIndex === -1) {
answer[i] = Math.abs(tNextIndex - i)
continue;
}
if (tNextIndex === -1) {      
answer[i] = Math.abs(tPrevIndex - i)
continue;
} …
```

[윤아영] 3-4 가장 짧은 문자거리

---

03. 문자열 탐색/05. 문자열 압축/이서인/index.js

✔ 문제 제목: 문자열 압축
✔ 문제 유형: 문자열
✔ 문제 풀이 날짜: 2024.07.19
- 문자열 중 같은 문자가 연속 반복될 때 반복되는 문자 오른쪽에 반복 횟수를 표기한다.
- 문자 요소가 1개라면 1을 생략한다.
- 스프레드 문법을 사용해 문자열을 배열로 만든다.
- reduce 메서드를 사용해 인덱스가 0인 문자이거나 이전 문자와 다른 문자일 경우 {요소, 개수}를 배열에 넣는다.
- 그렇지 않으면(연속하는 문자) count를 추가한다.
- map 메서드를 사용해 count가 1을 초과하면 cur과 count를 반환하고, 그렇지 않으면 cur만 반환한다.
```javascript
const result = [...s].reduce((acc, cur, i, arr) => {
if (i === 0 || cur !== arr[i - 1]) {
acc.push({ cur, count: 1 });
} else {
acc[acc.length - 1].count++;
}
return acc;
}, []);
return result
.map(({ cur, count }) => (count > 1 ? cur + count : cur))
.join("");
}
```
O(n)
- 객체의 키와 값을 배열로 변환하는 방식을 생각하지 못했다.
```javascript
const objectS = {};
[...s].map((el) => {
objectS[el] = (objectS[el] || 0) + 1;
});
return …
```

[서인] 3-5. 문자열 압축

---

03. 문자열 탐색/05. 문자열 압축/정봉찬/index.js

✔ 문제 제목: 문자열 압축
✔ 문제 풀이 날짜: 2024-07-19
- 같은 문자가 연속으로 반복될 때 반복되는 문자 바로 오른쪽에 반복 횟수를 표기한다.
- 반복 횟수가 1인 경우 생략한다.
- 반복 횟수를 저장할 count 변수를 만든다.
- 반복문을 돌면서 같은 문자가 반복되면 count를 증감한다.
- 이전 인덱스와 다른 문자가 나오면 문자를 저장하고 count가 1이 아닐 경우 count를 저장하고 count를 1로 초기화한다.
```javascript
let count = 1;
const pre = s[i - 1] || '';
const cur = s[i];
if (pre === cur) {
count++;
continue;
}
if (count > 1) {
answer += count;
}
answer += cur;
count = 1;
}
return answer;
}
let str = 'KKHSSSSSSSE';
```
- O(n)
- 현재 문자와 이전 문자가 다를 때 `count`를 붙여주기 때문에 마지막 문자가 반복될 경우 `count`가 붙지 않았다.
- 반복문 종료 후에 `count > 1`일 경우 `count`를 붙여준다.
```javascript
function solution2(s) {
let count = 1;
for (let i = …
```

[정봉찬] 3-5. 문자열 압축

---

03. 문자열 탐색/05. 문자열 압축/윤아영/index.js

✔ 문제 제목: 문자열 압축
✔ 문제 풀이 날짜: 24-07-19
- 같은 문자가 연속으로 반복되는 경우 반복되는 문자 바로 오른쪽에 반복 횟수를 표기
- 반복 횟수가 1인 경우 생략합니다.
- 문자열의 길이 만큼 반복문을 돈다.
- 반복 문자와 현재 문자가 다르다면,
- 정답 문자열에 반복 숫자가 1이 아니라면 반복 숫자를 추가한다.
- 정답 문자열에 현재 문자열을 추가한다. 
- 반복 문자를 현재 문자로, 반복 숫자를 1로 초기화한다.
- 반복 문자와 현재 문자가 같다면,
- 반복 숫자를 1 증가시키고, continue문을 실행한다.
```javascript
let repeatString = "";
let repeatNumber = 1;
if (repeatString === s[i]) {
repeatNumber++;
continue;
}
answer += repeatNumber === 1 ? "" : repeatNumber;
answer += s[i];
repeatString = s[i];
repeatNumber = 1;
}
return answer;
}
```
O(n)
- 마지막 문자가 반복된 횟수는 적용이 되지 않는다.
```js
let repeatString = "";
let repeatNumber = 1;
for (let i = 0; i < s.length; …
```

[윤아영] 3-5 문자열 압축

---

03. 문자열 탐색/01. 회문문자열/김유경/index.js

✔ 문제 제목: 회문 문자열
✔ 문제 풀이 날짜: 2024-07-18
- 앞에서부터 읽을 때와 뒤에서부터 읽을 때가 같은지 여부를 “YES”, “NO”로 출력하시오
- 뒤집는 메서드 쓰면 될 것 같은데
```jsx
return str === str.split("").reverse().join("") ? "YES" : "NO";
}
/** 테스트 */
let str1 = "goooG";
let str2 = "abdba";
let str3 = "aabaad";
let str4 = "aaaaa";
console.log(solution(str1));
console.log(solution(str2));
console.log(solution(str3));
console.log(solution(str4));
```
- O(N)
- 배열을 직접 비교할 수 없다는 것을 알게 되었다.
why? 참조 값을 비교하기 때문
- 변수를 사용해서 코드의 가독성을 높여야했을까 싶기도 했지만, 회문 문자열인지를 판독하는데 반드시 필요한 변수라는 생각은 안들었다.

[김유경] 3-1 회문 문자열

---

03. 문자열 탐색/03. 숫자만 추출/김유경/index.js

✔ 문제 풀이 날짜: 2024-07-20
- 숫자만 추출해서 자연수를 만든다
- 그 자연수의 크기는 100,000,000를 넘기지 않는다.
- 정규식을 활용하여 숫자만 남긴 후, 숫자 타입으로 변환해주면 될 것 같다.
- 만들어지는 자연수가 100,000,000 넘는 경우
- 100,000,000을 반환하거나 끝자리를 자르는 등의 조건이 추가로 있어야할 것 같은데 없어서 내가 적절한 처리를 고민해야 한다.
- 처음에는 끝자리를 차근차근 잘라나가겠노라 생각했는데 최댓값을 반환하는게 맞는 것 같아서 수정했다.
```jsx
const MAX_SIZE = 100000000;
let answer = parseInt(str.replace(/[^0-9]/g, ""));
return answer > MAX_SIZE ? MAX_SIZE : answer;
}
```
O(N)
- 조건문 해석을 꼬아서 한 것 같다.
- 굳이굳이 끝자리를 잘라서 작게 만들어야겠다고 생각했다.
```jsx
let answer = Number(str.replace(/[^0-9]/g, ""));
while (answer > 100000000) {
answer = Number(answer.toString().slice(0, -1));
}
return answer;
}
let str = "g0en2T0s8eSoft";
let soBig = "abc1234567890def"; …
```

[김유경] 3-3 숫자만 추출

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/김보경/index.js
02. 1, 2차원 배열 탐색/02. 보이는 학생/김보경/index.js
02. 1, 2차원 배열 탐색/03. 가위바위보/김보경/index.js
02. 1, 2차원 배열 탐색/04. 점수 계산/김보경/index.js
02. 1, 2차원 배열 탐색/05. 등수구하기/김보경/index.js
02. 1, 2차원 배열 탐색/06. 격자판 최대합/김보경/index.js
02. 1, 2차원 배열 탐색/07. 봉우리/김보경/index.js

✔ 문제 제목: 2-7 봉우리
✔ 문제 유형: 탐색?
✔ 문제 풀이 날짜: 24.07.20 토요일
주어진 이차원배열 행열 좌표의 상하좌우 탐색
- dx dy를 사용한 상하좌우 탐색
```javascript
let n = arr.length;
let dx = [-1, 0, 1, 0];
let dy = [0, 1, 0, -1];
for (let j = 0; j < n; j++) {
let flag = 1;
for (let k = 0; k < dx.length; k++) {
let nx = i + dx[k];
let ny = j + dy[k];
if (
nx >= 0 &&
nx < n &&
ny >= 0 &&
ny < n &&
arr[nx][ny] >= arr[i][j]
) {
flag = 0;
break;
}
}
if (flag) {
answer++;
}
}
}
return answer;
}
let arr = [
[5, 3, 7, 2, 3],
[3, 7, 1, 6, 1],
[7, 2, 5, 3, 4],
[4, 3, 6, 4, 1],
[8, 7, 3, 5, 2],
];
```
-
```javascript
```
- 다른 문제는 쉽게 해결했는데 마지막 봉우리 문제만 플지 못했습니다
- 처음보는 유형의 문제이고 풀지 못해서 동영상 참고해서 차근차근 풀이 진행해봤습니다.
- dx dy 탐색법에 대해 조금은 …

[김보경] 2-7 봉우리

---

04. 완전탐색(블루투포스)/02. 뒤집은 소수/정봉찬/index.js

✔ 문제 유형: 브루트 포스
✔ 문제 풀이 날짜: 2024-07-22
- N개의 자연수 배열이 입력된다.
- 자연수를 뒤집었을 때 소수일 때 그 소수를 출력한다.
- 자연수의 수만큼 반복문을 돈다.
- 자연수를 문자열, 배열로 변환 후 reverse로 뒤집는다.
- 뒤집은 배열을 문자열, 숫자로 변환한다.
- 뒤집은 숫자의 제곱근만큼 반복문을 돌며 소수 판별한다.
```javascript
const num = arr[i];
const reverseNum = parseInt([...num.toString()].reverse().join(''));
if (reverseNum <= 1) {
continue;
}
let isPassed = true;
for (let j = 2; j <= Math.trunc(Math.sqrt(reverseNum)); j++) {
if (reverseNum % j === 0) {
isPassed = false;
break;
}
}
if (isPassed) {
answer.push(reverseNum);
}
}
return answer;
}
let arr = [32, 55, 62, 20, 250, 370, 200, 30, 100];
```
- O(n^2)
- 여러분 파이팅!🎉
- `0`은 자연수 이기도 하고 아니기도 하다고 합니다. 뒤집은 수가 `1` 이하인 경우에는 …

[정봉찬] 4-2.뒤집은 소수

---

04. 완전탐색(블루투포스)/01. 자리수의 합/정봉찬/index.js

✔ 문제 제목: 자리수의 합
✔ 문제 유형: 완전 탐색(블루투포스)
✔ 문제 풀이 날짜: 2024-07-19
- 자연수의 자릿수의 합을 구한다. 그 합이 최대인 자연수를 출력한다.
- 자릿수의 합이 같은 경우 원래 숫자가 큰 숫자를 출력한다.
- 자연수 배열을 반복문 돌면서 자릿수의 합이 최대일 때 자연수의 크기를 비교한다.
```javascript
let answer;
let maxKey = 0;
let maxValue = 0;
const current = arr[i];
const sum = +[...current.toString()].reduce((pre, cur) => pre + +cur, 0);
if (sum < maxValue) {
continue;
}
maxValue = sum;
if (current >= maxKey) {
maxKey = current;
}
}
answer = maxKey;
return answer;
}
let arr = [128, 460, 603, 40, 521, 137, 123];
console.log(solution(7, arr));
```
- O(n^2)
- 봐주셔서 감사합니다. ☺️

[정봉찬] 4-1. 자리수의 합

---

04. 완전탐색(블루투포스)/01. 자리수의 합/이서인/index.js

✔ 문제 제목: 자리수의 합
✔ 문제 유형: 브루트포스
✔ 문제 풀이 날짜: 2024.07.20
- 각 자연수의 자릿수의 합을 구하고, 그 합이 최대인 자연수를 출력해야 한다.
- 자연수의 합이 같은 경우 원래 숫자가 큰 숫자를 반환해야 한다.
- map 메서드를 사용해 배열 요소의 자릿수 합을 구한다.
- 그 중 가장 큰 수와 큰 수의 인덱스를 구한다.
- 조건문을 사용해 최대값이 1개 이상일 때 기존 자연수 중 큰 숫자를 반환한다.
```javascript
const formattedNs = arr.map((el) => {
return [...el.toString()].reduce((a, b) => a * 1 + b * 1);
});
const maxEl = Math.max(...formattedNs);
const maxElIndex = formattedNs
.map((n, index) => (n === maxEl ? index : -1))
.filter((index) => index !== -1);
if (maxElIndex.length > 1) {
const maxValues = maxElIndex.map((index) => arr[index]);
return Math.max(...maxValues);
}
return arr[maxElIndex[0]];
}
```
O(n+m)
-
```javascript
let answer;
let maxKey = 0;
let maxValue = 0;
for (let …
```

[서인] 4-1. 자리수의 합

---

04. 완전탐색(블루투포스)/01. 자리수의 합/이서인/index.js
04. 완전탐색(블루투포스)/02. 뒤집은 소수/이서인/index.js

✔ 문제 유형: 브루트포스
✔ 문제 풀이 날짜: 2024.07.22
- N개의 자연수를 각각 뒤집는다.
- 뒤집은 수가 소수이면 출력한다.
- 배열 요소를 각각 뒤집고 정수로 반환한다.
- 요소가 1보다 클 때 for문을 돌려 제곱근 이하의 수 중 요소의 약수인 수가 있을 때(소수가 아닐 때) 0을 반환한다.
```javascript
const reversedNumbers = arr.map((el) =>
parseInt([...(el + "")].reverse().join(""))
);
return reversedNumbers
.filter((number) => {
if (number > 1) {
for (let i = 2; i <= Math.sqrt(number); i++) {
if (number % i === 0) {
return false;
}
}
return true;
}
return false;
})
.join(" ");
}
```
O(n &radic;m)
-
```javascript
const reverseNumbers = arr.map((v) => +[...String(v)].reverse().join(""));
return reverseNumbers.filter((v) => {
if (v < 2) return false;
for (let i = 2; i < Math.sqrt(v); i++) {
if (!(v % i)) {
return false;
}
}
return true; …
```

[서인] 4-2.뒤집은 소수

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/백지원/index.js

✔ 문제 유형: 1,2차원 배열 탐색
✔ 문제 풀이 날짜: 07.23
자신 앞 수보다 큰 수만 출력 
- 첫 번째 수는 무조건 출력하므로 answer 배열에 push
- for문을 통해 arr.length만큼 반복하여 앞 수와 그 다음 수를 비교하여 그 다음 수가 더 클 경우 answer 배열에 push
```javascript
if (arr[i] < arr[i + 1]) {
answer.push(arr[i + 1]);
}
}
return answer;
}
```
O(n)
- 생각의 흐름대로 짰는데 대강 수도코드를 짜고 코드로 실천해보자.

[지원] 2-1. 큰 수 출력하기

---

04. 완전탐색(블루투포스)/01. 자리수의 합/윤아영/index.js
04. 완전탐색(블루투포스)/02. 뒤집은 소수/윤아영/index.js

✔ 문제 유형: 완전 탐색
✔ 문제 풀이 날짜: 24-07-23
- 자연수로 이루어진 n개의 배열이 주어진다
- 각 자연수를 뒤집은 수가 소수라면 출력한다.
- 뒤집은 수를 숫자화 해야한다
- 각 자연수를 뒤집는다.
- 각 자연수가 소수인지 확인한다.
```javascript
const reverseNumbers = arr.map((v) => +[...String(v)].reverse().join(""));
return reverseNumbers.filter((v) => {
if (v < 2) return false;
for (let i = 2; i < Math.sqrt(v); i++) {
if (!(v % i)) {
return false;
}
}
return true;
});
}
```
O(n<sup>2</sup>)
- reverse도 O(n)이다.
- https://learnersbucket.com/examples/algorithms/how-to-reverse-an-array-in-javascript/

[윤아영] 4-2 뒤집은 소수

---

04. 완전탐색(블루투포스)/01. 자리수의 합/윤아영/index.js

✔ 문제 제목: 자릿수의 합
✔ 문제 유형: 완전 탐색
✔ 문제 풀이 날짜: 24-07-22
- 숫자로 이루어진 n개의 배열이 주어진다.
- 각 배열의 있는 숫자의 자릿수 합을 구한다.
- 그 합이 최대인 숫자를 출력한다.
- 자릿수의 합이 같다면 원래 숫자가 큰 수를 출력한다.
- 최대 합과 해당 숫자를 가지는 객체를 선언한다.
- 배열을 돌면서 각 숫자의 자릿수 합을 구한다.
- 현재합이 최대합보다 작다면 continue
- 현재합과 최대합이 같다면 원래 숫자를 비교하여 재할당
- 현재합이 최대합보다 크다면 현재 값으로 재할당
```javascript
let maxNumberSum = {
sum: Number.MIN_SAFE_INTEGER,
number: null,
};
let sum = 0;
let number = arr[i];
while (number > 0) {
sum += number % 10;
number = Math.floor(number / 10);
}
if (sum < maxNumberSum.sum) {
continue;
}
if (maxNumberSum.sum === sum) {
maxNumberSum.number = Math.max(maxNumberSum.number, arr[i]);
continue;
}
maxNumberSum = {
sum,
number: arr[i],
};
}
return maxNumberSum.number;
}
```
O(n<sup>2</sup>)

[윤아영] 4-1 자릿수의 합

---

03. 문자열 탐색/04. 가장 짧은 문자거리/김유경/index.js

✔ 문제 제목: 가장 짧은 문자거리
✔ 문제 풀이 날짜: 2024-07-23
- 한 개의 문자열이 주어지면, 그 안에서 다른 문자와 t가 떨어진 최소 거리를 출력해라
- t가 어떤 인덱스에 위치하는 지 파악해서, 그걸 이용하면 될 것 같다.
```jsx
let answer = new Array(s.length).fill(Infinity);
let tIndex = -1;
// 왼쪽에서 오른쪽으로 최소거리 계산
if (s[i] === t) tIndex = i;
if (tIndex !== -1) {
answer[i] = Math.abs(i - tIndex);
}
}
// 오른쪽에서 왼쪽으로 최소거리 계산
tIndex = -1;
for (let i = s.length - 1; i >= 0; i--) {
if (s[i] === t) tIndex = i;
if (tIndex !== -1) {
answer[i] = Math.min(answer[i], Math.abs(i - tIndex));
}
}
return answer;
}
let str = "teachermode";
console.log(solution(str, "e"));
```
O(n)
- 최악 시간 복잡도가 O(n2)이 나와서…이중 for문을 사용하지 않도록 해보았습니다.
- 그냥 시간 복잡도는 O(n+n⋅m) 였습니다.
```jsx
let …
```

[김유경] 3-4 가장 짧은 문자 거리

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/김민영/index.js

✔ 문제 제목: 2-1. 큰 수 출력하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 2024.07.23
-
```javascript
for (i = 1; i < arr.length; i++) {
if (arr[i - 1] < arr[i]) {
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 2-1. 큰 수 출력하기

---

04. 완전탐색(블루투포스)/03. 멘토링/윤아영/index.js

✔ 문제 제목: 멘토링
✔ 문제 유형: 완전 탐색
✔ 문제 풀이 날짜: 24-07-24
- N명의 학생의 등수가 정렬된 M번의 수학 테스트 배열이 주어집니다.
- A 학생이 멘토이고 B 학생이 멘티라면, A 학생은 M번의 수학테스트에서 모두 B 학생보다 등수가 앞서야 합니다.
- 짝을 만들 수 있는 경우의 수를 구하시오
- 멘토멘티짝을 객체로 선언합니다.
- 이중배열에서 첫번째 배열에서는 각 학생(키)의 아래 등수 학생들(값)을 객체에 저장합니다.
- 두번째 배열부터는 아래 등수 학생들과 저장되어 있는 학생들 중 겹치는 것들만 남깁니다.
- 객체의 키 값들(항상 해당 키 아래에 있었던 학생들)만 뽑아서 길이를 구합니다.
```javascript
function solution(test) {
const numberOfStudents = test[0].length;
const mentoNmentee = {};
for (let i = 0; i < test.length; i++) {
for (j = 0; j < numberOfStudents; j++) {
if (i === 0) {
mentoNmentee[test[i][j]] = test[i].slice(j + 1);
continue;
}
const below = new Set(test[i].slice(j + 1));
mentoNmentee[test[i][j]] = mentoNmentee[test[i][j]].filter((v) =>
below.has(v)
);
}
}
return Object.values(mentoNmentee).flat().length;
} …
```

[윤아영] 4-3 멘토링

---

04. 완전탐색(블루투포스)/03. 멘토링/이서인/index.js
04. 완전탐색(블루투포스)/04. 졸업선물/이서인/index.js

✔ 문제 제목: 졸업선물
✔ 문제 유형:브루트 포스
✔ 문제 풀이 날짜: 2024.07.24
- [가격, 배송비] 요소로 이뤄진 이중 배열에서 예산 내 최대로 구매할 수 있는 상품 개수를 구해야 한다.
- 상품 하나를 50% 할인해서 살 수 있고, 배송비는 할인에 포함되지 않는다.
- 각 요소의 합(상품 가격 + 배송비)을 오름차순으로 정렬한다.
- 요소들의 합이 예산 이하일 때 까지 계산하고, 요소 개수를 구한다.
- 요소 개수가 전체 상품 개수보다 작을 때 가장 큰 할인 금액을 계산한다.
- 현재 가격에서 최대 할인액을 빼고 예산 내에서 추가 구매가 가능한지 확인한다.
> - 잘못된 설계: 요소 개수가 전체 상품 개수보다 작을 때 사지 못한 상품 중 가격이 제일 낮은 상품 가격에 할인을 적용해서 더한다. => 정렬된 배열 인덱스를 기준으로 하므로 잘못된 결과가 나올 수 있다. 정확한 할인 금액을 계산하기 위해 원본 배열 인덱스를 사용하는 게 맞다.
```javascript
let sums = product.map((el) => el[0] + el[1]);
sums.sort((a, b) => a - b);
let buyProducts = 0;
let currentPrice = 0;
for (let i = 0; i < sums.length; i++) {
if (currentPrice + sums[i] > m) {
break;
}
currentPrice += sums[i];
buyProducts++;
}
if (buyProducts < …
```

[서인] 4-4. 졸업선물

---

04. 완전탐색(블루투포스)/03. 멘토링/이서인/index.js

✔ 문제 제목: 멘토링
✔ 문제 유형: 브루트 포스
✔ 문제 풀이 날짜: 2024.07.23
- T번의 수학테스트 등수로 멘토와 멘티를 정해야 한다.
- 학생 중 멘토와 멘티를 정할 수 있는 경우의 수를 구해야 한다.
- T번의 테스트에서 멘토 학생은 멘티 학생보다 등수가 앞서야 한다.
(다른 풀이 참고했습니다.)
- 학생 수, 테스트 수, 순위 저장 배열을 변수로 선언한다.
- arr을 순회하면서 testResult(각 배열) 내 학생 번호와 순위로 rankings[testIndex][student - 1] = rankIndex + 1를 실행한다.
- rankings[testIndex][student - 1] = rankIndex + 1은 rankings(순위 저장 배열)에 학생 번호 -1을 인덱스로 지정해 배치하고, 해당 위치에 순위(rankIndex + 1)를 넣는 로직이다.
- 순위 저장 배열(이중 배열)을 돌며 멘토와 멘티 요소가 같지 않고, 멘토의 순위가 멘티보다 높은 경우의 수를 반환한다.
```javascript
function solution(test) {
const S = test[0].length;
const T = test.length;
let rankings = Array.from({ length: T }, () => Array(S));
test.forEach((testResult, testIndex) => {
testResult.forEach((student, rankIndex) => {
rankings[testIndex][student - 1] = …
```

[서인] 4-3. 멘토링

---

04. 완전탐색(블루투포스)/04. 졸업선물/윤아영/index.js

✔ 문제 제목: 졸업선물
✔ 문제 유형: 완전탐색
✔ 문제 풀이 날짜: 24-07-24
- 현재 예산으로 선물을 사줄 수 있는 최대 학생 수 구하기
- 상품 하나를 50% 할인 가격(배송비미포함)으로 구매할 수 있다.
- [현재 가격 + 배송비, 반 값 가격 + 배송비]를 가지는 배열(이중배열)을 선언합니다.
- for문을 돌면서 인덱스가 일치하는 요소를 반 값 가격을 나머지는 원래 가격을 선택한 배열을 만들고,
- 가격이 적은 순서대로 정렬한다.
- for문을 돌면서 합계를 구하고 예산을 넘어가면 현재 정답과 비교해서 큰 수를 선택한다.
- 모든 선물 가격을 합쳤음에도 예산보다 작거나 같다면 전체 선물 수를 반환한다.
```javascript
const totalPrices = product.map(([price, delivery]) => [price + delivery, price / 2 + delivery]);
for (let i = 0; i < totalPrices.length; i++) {
let sum = 0;
const prices = totalPrices
.map(([price, discount], index) => (index === i ? discount : price))
.sort((a, b) => a - b);
for (let j = 0; j < prices.length; j++) {
sum += prices[j];
if (sum > m) {
answer = Math.max(answer, j); …
```

[윤아영]  4-4 졸업선물

---

02. 1, 2차원 배열 탐색/02. 보이는 학생/백지원/index.js

✔ 문제 제목: 보이는 학생
✔ 문제 유형: 1,2차원 배열 탐색
✔ 문제 풀이 날짜: 07.24
학생의 키가 앞에서부터 순서대로 주어질 때, 맨 앞에 서 있는 선생님이 볼 수 있는 학생의 수 구하기
- max의 초기값을 가장 앞에 있는 학생으로 둔다.
- max와 배열의 값을 비교하며 배열의 값이 더 클 경우 answer의 값을 1 증가하고 max값을 업데이트 한다.
```javascript
let max = arr[0];
for (i = 1; i < arr.length; i++) {
if (arr[i] > max) {
answer++;
max = arr[i];
}
}
return answer;
}
let arr = [130, 135, 148, 140, 145, 150, 150, 153];
```
O(n)
- 전 값과 비교하는건지 현재까지의 값과 비교하는 건지 정확히 구분하자.

[지원] 2-2. 보이는 학생

---

02. 1, 2차원 배열 탐색/02. 보이는 학생/김민영/index.js

✔ 문제 제목: 2-2. 보이는 학생
✔ 문제 유형:
✔ 문제 풀이 날짜: 2024.07.24
-
```javascript
let currentMaxHeight = arr[0];
if (arr[i] > currentMaxHeight) {
answer += 1;
currentMaxHeight = arr[i];
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 2-2. 보이는 학생

---

04. 완전탐색(블루투포스)/04. 졸업선물/정봉찬/index.js

✔ 문제 제목: 졸업선물
✔ 문제 유형: 브루트 포스
✔ 문제 풀이 날짜: 2024-07-24
- 예산으로 최대 몇 명의 학생에게 선물을 사줄 수 있는지 구한다.
- 상품 하나의 가격을 50% 할인해서 구매할 수 있다. 배송비는 할인에 포함되지 않는다.
- 상품가격은 짝수로만 입력된다.
- 최소 1개 이상의 상품을 살 수 있다.
- 학생수만큼 반복문을 돈다. 그 안에서 학생수만큼 반복문을 다시 돈다.
- 외부 반복문의 인덱스와 내부 반복문의 인덱스가 같으면 continue한다.
- 예산(m) 이하로 구매 가능한 학생 수를 계산해서 가장 많은 학생 수 케이스를 출력값에 넣는다.
```javascript
function solution2(m, product) {
product.sort((a, b) => a[0] + a[1] - (b[0] + b[1]));
for (let i = 0; i < product.length; i++) {
let totalPay = product[i][0] / 2 + product[i][1];
let productCount = 1;
for (let j = 0; j < product.length; j++) {
if (i === j) {
continue;
}
totalPay += product[j][0] + product[j][1];
if (totalPay > m) {
break;
}
productCount++;
}
if (productCount > answer) {
answer = productCount;
}
}
return answer;
}
let arr = …
```

[정봉찬] 4-4. 졸업선물

---

02. 1, 2차원 배열 탐색/03. 가위바위보/김민영/index.js

✔ 문제 제목: 2-3. 가위바위보
✔ 문제 유형: 
✔ 문제 풀이 날짜: 2024.07.25
각 줄에 각 회의 승자 출력, 비겼을 경우 D를 출력
-
```javascript
for (let i = 0; i < a.length; i++) {
if (a[i] === b[i]) {
answer += 'D\n';
} else if ((a[i] === 1 && b[i] === 3) || (a[i] === 2 && b[i] === 1) || (a[i] === 3 && b[i] === 2)) {
answer += 'A\n';
} else {
answer += 'B\n'
}
}
return answer.trim();
}
```
-
```javascript
```
-

[민영] 2-3. 가위바위보

---

04. 완전탐색(블루투포스)/05. K번째 큰 수/정봉찬/index.js

✔ 문제 제목: K번째 큰 수
✔ 문제 유형: 브루트 포스
✔ 문제 풀이 날짜: 2024-07-25
- 1부터 100사이의 자연수가 적힌 N장의 카드가 있다.
- 같은 숫자의 카드가 여러 장 있을 수 있다.
- 3장의 카드를 뽑아 합한 값을 기록한다.
- 모든 경우의 수를 기록하고 K번째로 큰 수를 출력한다.
- 카드를 내림차순 정렬한다.
- 카드를 3장 뽑아 합한 값을 담을 Set 자료구조 변수에 담는다.
- Set 자료구조 변수를 배열로 변환 후 내림차순 정렬한다.
- 배열의 길이가 k보다 작을 경우 -1을 반환하고 아니라면 k - 1 번째 수를 반환한다.
```javascript
let answer;
const NOT_FOUND = -1;
const sortedCardList = card.sort((a, b) => b - a);
const uniqueCardSumSet = new Set();
const first = sortedCardList[i];
for (let j = i + 1; j < n; j++) {
const second = sortedCardList[j];
for (let k = j + 1; k < n; k++) {
const third = sortedCardList[k];
const sum = first + second + third;
uniqueCardSumSet.add(sum);
}
}
}
const cardSumList = …
```

[정봉찬] 4-5. K번째 큰 수

---

04. 완전탐색(블루투포스)/05. K번째 큰 수/이서인/index.js

✔ 문제 제목: K번째 큰 수
✔ 문제 유형: 부르트 포스
✔ 문제 풀이 날짜: 2024.07.25
- 1~100 자연수가 적힌 카드 중 3장을 뽑아 합한 모든 값을 기록한다.
- 기록한 값 중 K번째로 큰 수를 출력한다.(중복 허용 안함)
- 3중 for문 또는 forEach를 돌려 세 숫자의 합을 구한다.
- Set 객체로 만들어 중복을 없앤 후 스프레드 문법으로 배열로 바꾸고 내림차순 정렬한다.
- 배열 중 k-1 인덱스 요소를 반환한다.
```javascript
let sums = [];
card.forEach((firstCard, i) => {
card.forEach((secondCard, j) => {
if (i === j) return;
card.forEach((thirdCard, k) => {
if (i === k || j === k) return;
sums.push(firstCard + secondCard + thirdCard);
});
});
});
return [...new Set(sums)].sort((a, b) => b - a)[k - 1];
}
```
O(n^3logn)
-
```javascript
return card.flatMap((firstCard, i) =>
card.flatMap((secondCard, j) =>
card
.filter((_, k) => i !== k && j !== k)
.map((thirdCard) => firstCard + …
```

[서인] 4-5. K번째 큰 수

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/이서인/index.js

✔ 문제 제목: 두 배열 합치기
✔ 문제 유형: 배열, 투포인터 알고리즘
✔ 문제 풀이 날짜: 2024.07.26
- 오름차순으로 정렬이 된 두 배열이 주어지면 두 배열을 오름차순으로 합쳐 출력해야 한다.
- 두 배열을 합친 후 sort로 오름차순 정렬한다.
- 1차 풀이
```javascript
return [...arr1, ...arr2].sort((a, b) => a - b);
}
```
- 2차 풀이
```javascript
const answer = [];
let pointer1 = 0;
let pointer2 = 0;
while (pointer1 < arr1.length || pointer2 < arr2.length) {
if (
pointer2 === arr2.length ||
(pointer1 < arr1.length && arr1[pointer1] <= arr2[pointer2])
) {
answer.push(arr1[pointer1++]);
} else {
answer.push(arr2[pointer2++]);
}
}
return answer;
}
```
- O(nlogn)
-
```javascript
const answer = [];
let pointer1 = 0;
let pointer2 = 0;
while (pointer1 !== arr1.length && pointer2 !== arr2.length) {
if …
```

[서인] 5-1. 두 배열 합치기

---

04. 완전탐색(블루투포스)/05. K번째 큰 수/윤아영/index.js

✔ 문제 제목: K번째 큰 수
✔ 문제 유형: 완전탐색
✔ 문제 풀이 날짜: 24-07-25
- N장의 카드 중 3장을 뽑아 합한 값을 기록한다.
- 기록한 값 중 K번째로 큰 수를 출력한다.
- 같은 숫자의 카드가 여러장 있을 수 있다.
- 해당하는 K번째 수가 없다면 -1을 반환한다.
- 합계를 set으로 정의한다.
- 중첩 for문을 돌면서 합계를 set에 추가시킨다.
- 합계의 size와 K가 같다면 해당 합계값을 반환한다.
```javascript
const sums = new Set();
card.sort((a, b) => b - a);
for (let j = i + 1; j < n; j++) {
for (let l = j + 1; l < n; l++) {
const sum = card[i] + card[j] + card[l];
sums.add(sum);
if (sums.size === k) {
return sum;
}
}
}
}
return -1;
}
```
O(n^3)
- 카드에 겹치는 숫자가 있다는 것을 보고 합계가 겹쳐도 되는 줄 알았다.
- 문제를 제대로 읽자!
```javascript
let order = 0;
card.sort((a, b) => b - a);
for (let j = i + 1; j < n; j++) {
for (let l = j + 1; l < n; …
```

[윤아영] 4-5 K번째 큰 수

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/윤아영/index.js

✔ 문제 제목: 두 배열 합치기
✔ 문제 유형: 효율성(투포인터 알고리즘)
✔ 문제 풀이 날짜: 24-07-26
- 두 배열을 오름차순으로 합쳐서 출력한다
- 두 배열을 오름차순으로 정렬이 되어 있다.
- 두 배열을 스프레드 문법을 사용하여 합치고 정렬한다.
```javascript
return [...arr1, ...arr2].sort((a, b) => a - b);
}
```
O(n)
- 투포인터의 의미를 살렸습니다.
```javascript
const answer = [];
let pointer1 = 0;
let pointer2 = 0;
while (pointer1 !== arr1.length && pointer2 !== arr2.length) {
if (arr1[pointer1] < arr2[pointer2]) {
answer.push(arr1[pointer1++]);
} else {
answer.push(arr2[pointer2++]);
}
}
while (pointer1 < arr1.length) {
answer.push(arr1[pointer1++]);
}
while (pointer2 < arr2.length) {
answer.push(arr2[pointer2++]);
}
return answer;
}
```
- 금요일입니다~ 행복한 주말이 곧 다가옵니다~

[윤아영] 5-1 두 배열 합치기

---

04. 완전탐색(블루투포스)/01. 자리수의 합/김유경/index.js

✔ 문제 제목: 자릿수의 합
✔ 문제 유형: 완전 탐색 (블루투포스)
✔ 문제 풀이 날짜: 2024-07-26
- N개의 자연수들의 자릿수의 합을 구하고, 그 중 가장 큰 수를 출력하라
- 같은 수가 나오면 원래 숫자가 가장 큰 걸 출력하라
- 반복문을 돌면서, 자릿수대로 잘라서 더하고 최대값보다 크면 원래의 자연수를 저장해뒀다가, 동점자 나오면 한 번 더 비교해서 업데이트하면 될 듯
```jsx
let maxSum = 0;
let maxNum = 0;
let sum = 0;
(arr[i] + "").split("").forEach((value) => {
sum += +value;
});
if (sum > maxSum || (sum == maxSum && arr[i] > maxNum)) {
maxSum = sum;
maxNum = arr[i];
}
}
return maxNum;
}
let arr = [128, 460, 603, 40, 521, 137, 123];
console.log(solution(7, arr));
```
O(N×M)
- 내장 메서드를 최대한 활용해보려고 했다.
- 객체보단 원시값을 이용한 변수를 사용하자 !
- 처음엔 더한 값들을 배열로 넣었었음

[김유경] 4-1 자릿수의 합

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/이서인/index.js

✔ 문제 제목: 공통원소 구하기
✔ 문제 유형: 투포인터 알고리즘
✔ 문제 풀이 날짜: 2024.07.27
- 두 배열의 공통원소를 오름차순 배열로 출력해야 한다.
- 두 배열을 각각 오름차순 정렬한다.
- 각 포인터가 각 배열의 길이보다 작을 때(while)
- 각 포인터가 가리키는 요소가 같으면 새 배열(answer)에 push
- 각 포인터가 가리키는 요소가 다르면 적절하게 포인터를 움직인다.
```javascript
let pointer1 = 0;
let pointer2 = 0;
arr1.sort((a, b) => a - b);
arr2.sort((a, b) => a - b);
while (pointer1 < arr1.length && pointer2 < arr2.length) {
if (arr1[pointer1] === arr2[pointer2]) {
answer.push(arr1[pointer1]);
pointer1++;
pointer2++;
} else if (arr1[pointer1] < arr2[pointer2]) {
pointer1++;
} else {
pointer2++;
}
}
return answer;
}
```
O(nlogn)
- 초기 배열을 오름차순 정렬을 안하고 요소를 비교해 오답이 나왔다.
```javascript
```
- [pointer1++]는 pointer1 인덱스로 사용한 후 1 커지는 것을 의미합니다.
- 투포인터 알고리즘의 틀을 조금씩 터득하고 …

[서인] 5-2. 공통원소 구하기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/윤아영/index.js

✔ 문제 제목: 공통 원소 구하기
✔ 문제 유형: 효율성(투포인터 알고리즘)
✔ 문제 풀이 날짜: 24-07-28
- 2개의 배열에서 공통 원소를 추출하여 오름차순으로 출력
- 1개의 배열을 Set으로 바꾸기
- 1개의 배열에서 공통으로 가지고 있는 것만 필터링한다.
- 공통 원소를 추출한 배열을 오름차순으로 정렬합니다.
```javascript
const set = new Set(arr1);
return arr2.filter((v) => set.has(v)).sort((a, b) => a - b);
}
```
O(nlogn)
```javascript
let point1 = 0;
let point2 = 0;
arr1.sort((a, b) => a - b);
arr2.sort((a, b) => a - b);
while (point1 < arr1.length && point2 < arr2.length) {
if (arr1[point1] === arr2[point2]) {
answer.push(arr1[point1++]);
point2++;
continue;
}
if (arr1[point1] < arr2[point2]) {
point1++;
continue;
}
point2++;
}
return answer;
}
```

[윤아영] 5-2 공통원소구하기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/이서인/index.js

✔ 문제 제목: 연속 부분수열1
✔ 문제 유형: 슬라이딩 윈도우
✔ 문제 풀이 날짜: 2024.07.29
- N개의 수열에서 연속 부분수열 합이 M이 되는 경우의 수를 구해야 한다.
- 포인터 2개, 부분 배열 합계, 답을 변수로 선언한다.
- pointer2가 배열 길이보다 작을 때, pointer2를 1씩 늘린 수를 배열 인덱스에 대입하며 합한다.
- 합계가 m보다 크고 pointer1이 pointer2보다 작을 때 pointer1에서 1씩 늘린 수를 배열 인덱스에 대입해 합계에서 뺀다.
```javascript
let pointer1 = 0;
let pointer2 = 0;
let sum = 0;
while (pointer2 < arr.length) {
sum += arr[pointer2++]
while (sum > m && pointer1 < pointer2) {
sum -= arr[pointer1++];
}
if (sum === m) {
answer++
}
}
return answer;
}
```
```javascript
let endPointer = 0;
let sum = 0;
for (let startPointer = 0; startPointer < arr.length; startPointer++) {
while (sum < m && endPointer < arr.length) {
sum += arr[endPointer++];
}
if …
```

[서인] 5-3. 연속 부분수열1

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/윤아영/index.js

✔ 문제 제목: 연속부분수열
✔ 문제 유형: 효율성(투포인터알고리즘)
✔ 문제 풀이 날짜: 24-07-29
- n개의 수로 이루어진 수열과 특정 숫자 m이 주어진다.
- 수열 내 연속부분수열의 합이 특정 숫자 M이 되는 경우의 수를 구한다.
- point1은 시작점, point2는 끝점이다.
- 반복문은 point1이 arr.length보다 크거나 같다면 종료된다.
- 반복문 시작에는 항상 arr[point2]를 sum에 더한다.
- sum이 m보다 작고 point2가 arr.length - 1 보다 작다면 point2에 1을 더한다.
- sum이 m보다 크거나 같다면 sum은 0을 재할당, point1은 1증가시키고 point2는 point1과 같도록 재할당한다.
- sum이 m과 같다면 answer를 1증가 시킨다.
```javascript
let sum = 0;
let point1 = 0;
let point2 = 0;
while (point1 < arr.length) {
sum += arr[point2];
if (sum < m && point2 < arr.length - 1) {
point2++;
continue;
}
if (sum === m) {
answer++;
}
sum = 0;
point2 = ++point1;
}
return answer;
}
```
O(n)
- 화이팅!
- 투포인터알고리즘과 슬라이딩윈도우의 차이점
- 부분 배열 길이의 변화의 여부
- 변화가 있다면 투포인터알고리즘, 없다면 슬라이딩윈도우

[윤아영] 5-3 연속부분수열1

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/윤아영/index.js

✔ 문제 제목: 연속부분수열2
✔ 문제 유형: 효율성(투포인터 알고리즘, 슬라이딩 윈도우)
✔ 문제 풀이 날짜:24-07-30
- 연속부분수열의 합이 M이하인 경우의 횟수를 구하세요
- 포인터와 연속수열배열의 길이를 선언합니다.
- 포인터가 끝이거나 연속수열배열이 주어진 배열의 길이와 같다면 반복문을 빠져나온다.
- 해당 포인터에서 연속수열배열의 길이만큼 합계를 구한다
- 해당 합계가 M보다 작다면 answer를 1 증가시킨다.
- 포인터와 연속수열배열의 길이의 합계가 주어진 배열의 길이보다 커진다면 포인터는 0으로 초기화하고 연속수열배열의 길이를 1 증가시킨다.
```javascript
let point1 = 0;
let length = 1;
while (true) {
if (point1 >= arr.length || length > arr.length) break;
let sum = 0;
for (let i = point1; i < point1 + length; i++) {
sum += arr[i];
if (sum > m) {
break;
}
}
point1++;
if (sum <= m) {
answer++;
}
if (point1 + length > arr.length) {
point1 = 0;
length++;
}
}
return answer;
}
```
O(n^2)
- 시간복잡도 O(n^3)
```javascript
let length = 1; …
```

[윤아영] 5-4 연속부분수열2

---

02. 1, 2차원 배열 탐색/03. 가위바위보/백지원/index.js
02. 1, 2차원 배열 탐색/04. 점수 계산/백지원/index.js

✔ 문제 제목: 점수 계산
✔ 문제 유형: 1,2차원 배열 탐색
✔ 문제 풀이 날짜: 07.31
연속으로 맞힌 경우 가산점을 부여한다.
맞춘 문제를 보고 총점을 계산한다.
- 연속으로 맞춘 것에 대한 횟수를 저장하기 위해 additionalPoints 변수를 선언하고 1인 경우 additionalPoints를 1씩 추가한다. 
- answer 변수에 가산점을 더한다.
```javascript
let additionalPoints = 0;
if (arr[i] === 1) {
additionalPoints++;
answer += additionalPoints;
} else {
additionalPoints = 0;
}
}
return answer;
}
let arr = [1, 0, 1, 1, 1, 0, 0, 1, 1, 0];
```
O(n)
-

[지원] 2-4. 점수 계산

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/윤아영/index.js

✔ 문제 제목: 최대 매출
✔ 문제 유형: 효율성 (슬라이딩 윈도우)
✔ 문제 풀이 날짜: 24-07-31
- n개의 배열이 주어집니다 (매출 기록)
- 연속 k일 동안의 최대 매출액을 구하세요.
- 첫 연속 k일 동안의 매출 합계를 sum, maxSales에 할당합니다.
- pointer는 k부터 시작합니다.
- pointer가 n보다 작다면 반복합니다.
- 합계에서 (pointer - k)번째 요소는 빼고 pointer번째 요소는 더합니다.
- maxSales와 sum를 비교해서 큰 수를 선택합니다.
```javascript
function solution(k, arr) {
let pointer = k;
let sum = arr.slice(0, k).reduce((acc, cur) => acc + cur, 0);
let maxSales = sum;
while (pointer < arr.length) {
sum -= arr[pointer - k];
sum += arr[pointer++];
maxSales = Math.max(sum, maxSales);
}
return maxSales;
}
```
O(n)
- 연속된 숫자가 정해져 있어서 pointer 하나를 가지고 계산이 가능하다.
- 화이팅!! 💪

[윤아영] 5-5 최대 매출

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/윤아영/index.js

✔ 문제 제목: 학급 회장
✔ 문제 유형: 효율성(해쉬)
✔ 문제 풀이 날짜: 24-08-01
- 후보 A, B, C, D, E 존재한다.
- 투표 결과가 문자열로 제공된다.
- 받은 투표 수가 가장 많은 후보를 출력한다.
- 반드시 한 명의 학급 회장이 선출되도록 투표 결과가 나온다.
- 학급 회장의 기호와 득표수를 담고 있는 객체를 생성한다.
- 투표 결과 문자열을 배열로 만들어 돌면서 key로 기호를, value로 득표수를 가지는 객체는 생성한다.
- for...in문을 활용해서 객체를 순회하면서 득표수를 비교하여 학생 회장을 재할당한다.
```javascript
const president = { person: null, votes: null };
const result = [...s].reduce((acc, cur) => {
acc[cur] = (acc[cur] || 0) + 1;
return acc;
}, {});
for (candidate in result) {
if (result[candidate] < president.votes) {
continue;
}
president.person = candidate;
president.votes = result[candidate];
}
return president.person;
}
```
O(n)
- 배열을 정렬하는 방법
```javascript
const votingResult = [...s].reduce((acc, cur) => {
acc[cur] = …
```

[윤아영] 5-6 학급 회장

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/이서인/index.js

✔ 문제 제목: 아나그램
✔ 문제 유형: 해쉬
✔ 문제 풀이 날짜: 2024.08.02
- 두 문자열의 구성이 같은지 비교해서 같으면 "YES", 같지 않으면 "NO"를 반환한다.
- 두 문자열의 대소문자를 구분한다.
- 두 문자열의 hash를 각각 만든다.
- hash.size가 같은지 비교한다.
- 각 hash의 키와 값이 같은지 비교한다.
```javascript
const hash1 = new Map();
const hash2 = new Map();
[...str1].forEach((el) => {
hash1.set(el, (hash1.get(el) || 0) + 1);
});
[...str2].forEach((el) => {
hash2.set(el, (hash2.get(el) || 0) + 1);
});
if (hash1.size !== hash2.size) {
return "NO";
}
for (const [key, value] of hash1) {
if (hash2.get(key) !== value) {
return "NO";
}
}
return answer;
}
```
O(n)
- 아직 풀이에 익숙하지 않아 어제 풀이 참조했습니다.
```javascript
if (str1.length !== str2.length) {
return "NO";
}
const anagram1 = new Map();
const anagram2 = new Map(); …
```

[서인] 5-7. 아나그램

---

02. 1, 2차원 배열 탐색/05. 등수구하기/백지원/index.js

✔ 문제 제목: 등수구하기
✔ 문제 유형: 1,2차원 배열 탐색
✔ 문제 풀이 날짜: 08.01
점수를 보고 등수 구하기
- 점수가 높은 사람이 등수가 작으므로 내림차순 정렬
- 해당 배열값의 인덱스를 구하되 인덱스는 0부터 시작하므로 +1
- 등수 출력
```javascript
let sortedScores = [...arr].sort((a, b) => b - a);
const rank = sortedScores.indexOf(arr[i]) + 1;
answer.push(rank);
}
return answer;
}
let arr = [87, 89, 92, 100, 76];
```
O(n)
- 나 코테 너무 어렵당

[지원] 2-5. 등수구하기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/윤아영/index.js

✔ 문제 제목: 아나그램
✔ 문제 유형: 효율성(해쉬)
✔ 문제 풀이 날짜: 24-08-02
- 두 문자열의 구성이 일치하면 아나그램입니다.
- 대소문자를 구분합니다.
- 두 문자열의 길이가 같지 않다면 얼리리턴합니다.
- 반복문을 돌면서 각 문자의 개수를 세어줍니다.
- 문자의 개수를 저장해둔 Map을 돌면서 다른 문자열의 구성과 같은지 확인합니다.
```javascript
if (str1.length !== str2.length) {
return "NO";
}
const anagram1 = new Map();
const anagram2 = new Map();
for (let i = 0; i < str1.length; i++) {
anagram1.set(str1[i], (anagram1.get(str1[i]) || 0) + 1);
anagram2.set(str2[i], (anagram2.get(str2[i]) || 0) + 1);
}
for (const [alphabet, number] of anagram1) {
if (anagram2.get(alphabet) !== number) {
return "NO";
}
}
return "YES";
}
```
O(n)
- map은 키-값 쌍으로 구성되어있다.
- 항상 if문의 (undefined !== undefined)로 평가된다.
```javascript
for (const alphabet of anagram1) {
if (anagram1.get(alphabet) !== …
```

[윤아영] 5-7 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/이서인/index.js

✔ 문제 제목: 모든 아나그램
✔ 문제 유형: 해시 + 슬라이딩 윈도우
✔ 문제 풀이 날짜: 2024.08.03
- S의 부분 문자열이 T의 문자열의 아나그램(키와 값이 같은 hash)이어야 한다.
- 대소문자를 구분해야 한다.
- 슬라이딩 윈도우로 T의 길이와 같은 S의 부분 문자열을 해시로 만든다.
- T의 해시를 만든다.
- S의 해시 중 T의 해시와 같은 구성만 반환한다.
```javascript
// 슬라이딩윈도우로 length 같은 부분 배열 구하고 해시 만들기
let hashes = [];
// t.length와 같은 길이의 부분 배열 구하기
[...s].forEach((_, index) => {
if (index + t.length <= [...s].length) {
let window = [...s].slice(index, index + t.length);
let hash = new Map();
window.forEach((el) => {
hash.set(el, (hash.get(el) || 0) + 1);
});
hashes.push(hash);
}
});
// hash1: 구해야 할 t의 해시
const hash1 = new Map();
[...t].forEach((el) => {
hash1.set(el, (hash1.get(el) || 0) + 1);
});
// hashes를 순회하면서 hash의 키와 값이 hash와 같은지 확인
hashes.forEach((hash) => {
let isMatch = …
```

[서인] 5-8. 모든 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/윤아영/index.js

✔ 문제 제목: 모든 아나그램
✔ 문제 유형: 효율성(투포인터 알고리즘, 슬라이드 윈도우, 해쉬)
✔ 문제 풀이 날짜: 24-08-04
- 두 문자열(s, t)이 주어집니다.
- t문자열과 아나그램이 되는 s의 부분문자열의 개수를 구하세요.
- 아나그램: 문자의 구성이 같은지를 판단한다. 대소문자를 구분한다.
- 문자의 구성을 map으로 관리합니다.
- 아나그램인지 판단해주는 함수를 생성한다.
- 반복문을 돌면서 
- 두 Map의 구성이 같다면 answer 1 증가시킨다.
- 현재 인덱스의 s문자를 sAlphabetMap에 1 증가 시키거나 추가하고
- (현재 인덱스 - t.length) 인덱스의 문자를 sAlphabetMap에 1 감소 시키거나 삭제한다.
```javascript
const tAlphabetMap = new Map();
const sAlphabetMap = new Map();
const isAnagram = (sMap, tMap) => {
if (sMap.size !== tMap.size) {
return false;
}
for (let [key, value] of tMap) {
if (sMap.get(key) !== value) {
return false;
}
}
return true;
};
[...t].forEach((alphabet) => tAlphabetMap.set(alphabet, (tAlphabetMap.get(alphabet) || 0) + 1));
[...s.slice(0, …
```

[윤아영] 5-8 모든 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/정봉찬/index.js

✔ 문제 제목: 모든 아나그램
✔ 문제 유형: 효율성(해쉬, 투포인터, 슬라이딩 윈도우)
✔ 문제 풀이 날짜: 2024-08-03
- S문자열에서 T문자열과 아나그램이 되는 S의 부분문자열의 개수를 구한다.
- 대소문자가 구분된다.
- 부분문자열은 연속된 문자열이어야 한다.
- S문자열의 부분문자열을 담을 해쉬 변수 hash1, T문자열을 담을 해쉬 변수 hash2를 Map 자료구조로 선언한다.
- T문자열을 순회하면서 hash2에 문자를 key로 문자의 개수를 value로 담는다.
```javascript
// const hash1 = new Map();
// const hash2 = new Map();
// const slidingSize = t.length;
// for (const alphabet of t) {
//   hash1.set(alphabet, (hash1.get(alphabet) || 0) + 1);
// }
// for (let i = 0; i < slidingSize; i++) {
//   hash2.set(s[i], (hash2.get(s[i]) || 0) + 1);
// }
// let sp = 0;
// for (let ep = slidingSize; ep < s.length; ep++) {
//   let isAnagram = true;
//   for (const [alphabet, count] of hash2) {
//     if (hash1.get(alphabet) !== count) {
// …
```

[정봉찬] 5-8. 모든 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/정봉찬/index.js

✔ 문제 제목: 연속부분수열2
✔ 문제 유형: 효율성(투포인터 알고리즘)
✔ 문제 풀이 날짜: 2024-08-04
- N개의 수로 이루어진 수열이 있다.
- 연속부분수열의 합이 특정 숫자 M 이하가 되는 경우가 몇 번 있는지 구해라.
- 시작 포인터 변수 startPointer를 0으로 초기화 선언한다.
- 합 변수 sum을 0으로 초기화 선언한다.
- endPointer를 0으로 시작하는 for 반복문을 arr의 길이 만큼 반복한다. 이때 증감식은 endPointer + 1 한다.
- 반복문이 시작되면 sum에 arr[endPointer]를 더한다.
- while 문으로 sum > m && startPointer < endPointer 일 때 sum - arr[startPointer++]을 반복한다.
- while 문이 종료되면 if 문으로 sum <= m 일 때 answer를 answer + endPointer - startPointer + 1 한다.
```javascript
function solution2(m, arr) {
let startPointer = 0;
let sum = 0;
for (let endPointer = 0; endPointer < arr.length; endPointer++) {
sum += arr[endPointer];
while (sum > m && startPointer < endPointer) {
sum -= arr[startPointer++];
}
answer += endPointer - startPointer + 1;
}
return …
```

[정봉찬] 5-4. 연속부분수열2 (재풀이)

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/이서인/재풀이.js
06. 자료구조(스택, 큐)/01. 올바른 괄호/이서인/index.js

✔ 문제 제목: 올바른 괄호
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 2024.08.05
- 괄호의 쌍이 올바르게 위치하면 "YES", 아니면 "NO"를 반환한다.
- for of 문을 순회하며 (일때 stack에 push, )일때 stack에 pop을 한다.
- )요소 시 stack의 길이가 0이면 NO를 반환한다.
- 최종 stack의 길이가 0이면 YES, 아니면 NO를 반환한다.
```javascript
for (const el of s) {
if (el === "(") {
return stack.push(1);
} else if (el === ")") {
if (stack.length === 0) {
return "NO";
}
stack.pop();
}
}
return stack.length === 0 ? "YES" : "NO";
}
```
O(n)
- 처음에 forEach를 써서 모든 요소를 순회해 오답이 나왔다. 메서드 순회 도중에 루프를 멈출 수 없기 때문이다.
-  for...of 문은 순회 도중 조건에 맞는 즉시 반환할 수 있다.
```javascript
const BRACKET_OPEN = '(';
for (const bracket of s) {
if (bracket === BRACKET_OPEN) {
stack.push(bracket);
continue;
}
if (!stack.length) {
return …
```

[서인] 6-1. 올바른 괄호 풀이

---

06. 자료구조(스택, 큐)/01. 올바른 괄호/윤아영/index.js

✔ 문제 제목: 올바른 괄호
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 24-08-05
- 올바른 괄호이면 YES 아니면 NO를 출력한다.
- 반복문을 돌면서 열린 괄호이면 배열에 push해주고
- 닫힌 괄호이면 열린 괄호가 존재하면 pop하고 없다면 NO를 반환한다
- 반복문을 다 돌고 난 뒤 배열에 요소가 남아있다면 NO를 아니면 YES를 반환한다.
```javascript
const openBracket = [];
if (s[i] === "(") {
openBracket.push(s[i]);
continue;
}
if (openBracket[openBracket.length - 1] !== "(") {
return "NO";
}
openBracket.pop();
}
return openBracket.length ? "NO" : "YES";
}
let a = "(()(()))(()";
console.log(solution(a));
```
O(n)
##💡 틀린 이유와 틀린 부분 수정 or 다른 풀이
- 닫힌 괄호일 때 스택에 마지막 요소가 열린 괄호인지를 확인했었는데 배열의 길이로 판단할 수 있다!

[윤아영] 6-1 올바른 괄호

---

06. 자료구조(스택, 큐)/01. 올바른 괄호/정봉찬/index.js

✔ 문제 제목: 올바른 괄호
✔ 문제 유형: 자료구조(스택)
✔ 문제 풀이 날짜: 2024-08-05
- 올바른 괄호이면 "YES", 아니면 "NO"를 출력한다.
- 스택이 될 배열 stack을 선언한다.
- 문자열의 길이만큼 반복문을 돌면서 여는 괄호('(')일 때는 stack에 push하고 닫는 괄호(')')일 때는 stack에서 pop한다.
- 닫는 괄호가 나와서 stack에서 pop하기 전에 stack이 비어있다면 반복문을 종료하고 "NO"를 출력한다.
- 반복문이 종료되었을 때 answer가 비어있지 않다면 "NO"를 출력한다. 그 외에는 "YES"를 출력한다.
```javascript
const BRACKET_OPEN = '(';
for (const bracket of s) {
if (bracket === BRACKET_OPEN) {
stack.push(bracket);
continue;
}
if (!stack.length) {
return 'NO';
}
stack.pop();
}
if (stack.length) {
return 'NO';
}
return answer;
}
let a = '(()(()))(()';
let b = '(())()';
let c = '(()()))';
console.log(solution(a)); // NO
console.log(solution(b)); // YES
console.log(solution(c)); // NO
```
- O(n)
- 점심으로 텐동 …

[정봉찬] 6-1. 올바른 괄호

---

06. 자료구조(스택, 큐)/02. 괄호문자제거/이서인/index.js

✔ 문제 제목: 괄호문자제거
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 2024.08.06
- 주어진 문자열 중 소괄호 안에 있는 문자를 제외하고 반환해야 한다.
- 문자열을 순회하면서 ")" 전까지의 문자열을 stack에 push한다.
- 스택 요소가 "("이 될 때까지 pop한다.
- 스택에서 "("도 pop한다.
```javascript
for (const el of s) {
if (el === ")") {
while (stack.length > 0 && stack[stack.length - 1] !== "(") {
stack.pop();
}
if (stack.length > 0) {
stack.pop();
}
} else {
stack.push(el);
}
}
return stack.join("");
}
```
O(n)
- 코테에 집중하지 못해서 접근 방식이 떠오르지 않았다.
```javascript
const bracket = [];
for (const character of s) {
if (character === "(") {
bracket.push(character);
continue;
}
if (character === ")") {
bracket.pop();
continue;
}
if (!bracket.length) {
answer += character;
}
}
return answer;
}
let str = …
```

[서인] 6-2. 괄호문자제거

---

06. 자료구조(스택, 큐)/02. 괄호문자제거/윤아영/index.js

✔ 문제 제목: 괄호문자제거
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 24-08-06
- 문자열에서 소괄호 사이에 존재하는 모든 문자를 제거하고 남은 문자만 출력
- 열린 괄호를 스택에 쌓아준다.
- 닫힌 괄호가 나오면 스택에서 pop한다.
- 스택에 아무것도 없을 때 문자를 answer에 더한다.
```javascript
const bracket = [];
for (const character of s) {
if (character === "(") {
bracket.push(character);
continue;
}
if (character === ")") {
bracket.pop();
continue;
}
if (!bracket.length) {
answer += character;
}
}
return answer;
}
let str = "(A(BC)D)EF(G(H)(IJ)K)LM(N)";
```
O(n)
- 화이팅!

[윤아영] 6-2 괄호문자제거

---

06. 자료구조(스택, 큐)/02. 괄호문자제거/이서인/index2.js
06. 자료구조(스택, 큐)/03. 크레인 인형뽑기(카카오)/이서인/index.js

✔ 문제 제목: 6-3. 크레인 인형뽑기
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 2024.08.07
- 이중 배열로 구성한 인형뽑기에서 인형을 하나 뽑아 바구니로 옮긴다.
- 인형은 1 * 1 격자 한 칸을 차지하며,  해당 인형이 있던 자리는 요소 0이 된다.
- 인형을 모으는 바구니에 동일한 인형이 연속으로 들어가면 해당 인형은 없어진다.
- 없어진 인형 개수를 구해야 한다.
- 뽑아야 할 열이 들어있는 moves 배열을 순회한다.
- 뽑아야 할 열은 1부터 시작하므로 인덱스에 맞게 - 1을 해서 선언한다.
- 인형뽑기의 행이 있고, 요소가 0이 아닐 때 뽑아야 할 열을 활용해 뽑는 인형을 구한다.
- 뽑은 인형의 위치는 0을 재할당해야 한다.
- 바구니에 동일한 인형이 있을 때 바구니에서 꺼내면서 없어진 인형 개수를 늘린다.
```javascript
let basket = [];
moves.forEach((move) => {
let column = move - 1;
for (let i = 0; i <= board.length; i++) {
if (board[i] !== undefined && board[i][column] !== 0) {
let doll = board[i][column];
board[i][column] = 0;
if (basket.length > 0 && basket[basket.length - 1] === doll) {
basket.pop();
answer += 2;
} else { …
```

[서인] 6-3. 크레인 인형뽑기

---

06. 자료구조(스택, 큐)/03. 크레인 인형뽑기(카카오)/윤아영/index.js

✔ 문제 제목: 크레인 인형뽑기
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 24-08-07
- board가 2차원 배열로 주어진다.
- 크레인을 작동시킨 위치가 담긴 배열 moves가 매개변수로 주어진다.
- 같은 모양의 인형 두 개가 바구니에 연속해서 쌓이게 되면 두 인형은 터뜨려지면서 바구니에서 사라진다.
- moves 배열 반복문을 돌면서 해당 위치의 board를 탐색한다.
- 0이 아닌 숫자가 있을 때 해당 숫자가 바구니의 가장 위의 숫자와 같은지 확인하고
- 같다면 바구니를 pop하고 answer에 2를 더해준다.
- 다르다면 바구니에 해당 숫자를 추가해준다.
```javascript
const basket = [];
for (const move of moves) {
for (let i = 0; i < board.length; i++) {
const currentItem = board[i][move - 1];
if (currentItem === 0) {
continue;
}
if (basket[basket.length - 1] === currentItem) {
basket.pop();
answer += 2;
} else {
basket.push(currentItem);
}
board[i][move - 1] = 0;
break;
}
}
return answer;
}
```
O(n * m)
```javascript
const reverseBoard = …
```

[윤아영] 6-3 크레인 인형뽑기

---

06. 자료구조(스택, 큐)/03. 크레인 인형뽑기(카카오)/정봉찬/index.js

✔ 문제 제목: 크레인 인형뽑기(카카오)
✔ 문제 유형: 자료구조(스택)
✔ 문제 풀이 날짜: 2024-08-07
- N x N 크기의 정사각 격자에서 제일 위에 존재하는 인형부터 바구니에 담을 수 있다.
- 같은 모양의 인형 두 개가 바구니에 연속해서 쌓이게 되면 두 인형은 바구니에서 사라진다.
- 스택 변수 stack을 선언하고 빈 배열로 초기화한다.
- 스택 변수 basket을 선언하고 빈 배열로 초기화한다.
- board를 반복문 돌면서 내부 배열을 거꾸로 반복문 돌면서 stack에 2차원 배열 형태로 담는다. 이때 0은 담지 않는다. 예) board[5][0], board[4][0], board[3][0] ...
- moves를 반복문 돌면서 stack에서 꺼내서 basket에 담는다. 이때 stack에서 꺼낸 값이 basket의 마지막 값과 같다면 basket을 pop하고 answer를 2 더한다.
```javascript
const basket = [];
for (let i = 0; i < board.length; i++) {
const column = [];
for (let j = board.length - 1; j >= 0; j--) {
const item = board[j][i];
if (!item) continue;
column.push(board[j][i]);
}
stack.push(column);
}
for (let i = 0; i < moves.length; …
```

[정봉찬] 6-3. 크레인 인형뽑기(카카오)

---

06. 자료구조(스택, 큐)/04. 후위식 연산/이서인/index.js

✔ 문제 제목: 후위식 연산
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 2024.08.08
- 후위 연산식의 연산 결과를 출력해야 한다.
- 정규표현식으로 검사해 숫자는 stack에 push 한다.
- 연산자는 stack에서 숫자 2개를 pop한 후 그에 맞게 연산한다.
```javascript
const REGEX = /^[0-9]$/;
[...s].forEach((el) => {
if (REGEX.test(el)) {
stack.push(el * 1);
} else {
let a = stack.pop();
let b = stack.pop();
switch (el) {
case "+":
stack.push(b + a);
break;
case "-":
stack.push(b - a);
break;
case "*":
stack.push(b * a);
break;
case "/":
stack.push(b / a);
break;
}
}
});
return stack[0];
}
```
O(n)
- 연산을 어떻게 해야할지 생각이 안났다.
```javascript
const calculation = (operation, num1, num2) => {
switch (operation) {
case "+":
return +num1 + +num2;
case "-":
return num1 - num2;
case "*":
return num1 * num2;
case "/":
return …
```

[서인] 6-4. 후위식 연산

---

06. 자료구조(스택, 큐)/04. 후위식 연산/윤아영/index.js

✔ 문제 제목: 후위식 연산
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 24-08-08
- 후위연산식을 연산한 결과를 출력합니다.
- 반복문으로 문자열을 돌며 숫자라면 stack에 push하고 아니라면 연산을 합니다.
```javascript
const calculation = (operation, num1, num2) => {
switch (operation) {
case "+":
return +num1 + +num2;
case "-":
return num1 - num2;
case "*":
return num1 * num2;
case "/":
return num1 / num2;
}
};
for (const char of s) {
if (Number.isInteger(+char)) {
stack.push(+char);
continue;
}
const [num1, num2] = stack.splice(stack.length - 2, 2);
stack.push(calculation(char, num1, num2));
}
return stack[0];
}
let str = "352+*9-";
```
O(n * m)
- Array.prototype.splice()의 시간복잡도는 O(n)이라고 한다.
- 이 문제의 경우 Array.prototype.pop()으로 대체할 수 있을 것 같기도? 아니면 인덱스로?

[윤아영] 6-4 후위식 연산

---

06. 자료구조(스택, 큐)/04. 후위식 연산/정봉찬/index.js

✔ 문제 제목: 후위식 연산
✔ 문제 유형: 자료구조(스택)
✔ 문제 풀이 날짜: 2024-08-08
- 후위연산식이 주어지면 연산한 결과를 출력한다.
- 식은 1~9의 숫자와 +, -, *, / 연산자로만 이루어진다.
- 스택이 될 변수 stack을 선언하고 빈배열로 초기화한다.
- 사칙연산을 연산하는 함수인 operator를 정의한다.
- 후위연산식 문자열을 for ... of 문으로 순회하면서 스택에 담는다.
- 스택에 담을 때 연산자가 나오면 스택에서 숫자 두 개를 꺼내 operator 함수로 연산한 결과를 다시 스택에 담는다.
- 반복문이 종료된 후 스택에 남은 숫자가 후위연산식의 결과다.
```javascript
let answer;
function operator(x, op, y) {
switch (op) {
case '+':
return x + y;
case '-':
return x - y;
case '*':
return x * y;
case '/':
return x / y;
}
}
for (const op of s) {
if (Number(op)) {
stack.push(Number(op));
continue;
}
const y = stack.pop();
const x = stack.pop();
stack.push(operator(x, op, y));
}
answer = stack.pop();
return answer;
}
let str = '352+*9-';
```
- …

[정봉찬] 6-4. 후위식 연산

---

06. 자료구조(스택, 큐)/01. 올바른 괄호/이서인/index2.js
06. 자료구조(스택, 큐)/05. 쇠막대기/이서인/index.js

✔ 문제 제목: 쇠막대기
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 2024.08.09
- ()일 때 레이저가 발사돼 쇠막대기가 분리된다.
- 레이저 발사 시 ()이전 ((( 개수만큼 분리된 쇠막대기가 추가된다.
- (를 stack에 push한다.
- (뒤에 )가 연속으로 나오면 stack에서 pop하면서 쇠막대기 분리 개수(stack.length)를 answer에 더한다.
- )뒤에 )가 나오면 1만 answer에 더한다.
```javascript
[...s].forEach((el, index) => {
if (el === "(") {
stack.push(el);
} else {
stack.pop();
if (s[index - 1] === "(") {
answer += stack.length;
} else {
answer += 1;
}
}
});
return answer;
}
```
O(n)
- 이것도 어떻게 스택으로 풀어야 할지 감이 안 잡혀서 유튜브 보고 구현 과정 이해했습니다.
```javascript
const bars = [];
if (s[i] === "(") {
bars.push(s[i]);
continue;
}
bars.pop();
if (s[i - 1] === "(") {
answer += bars.length;
continue;
}
answer += 1;
} …
```

[서인] 6-5. 쇠막대기

---

06. 자료구조(스택, 큐)/05. 쇠막대기/윤아영/index.js

✔ 문제 제목: 쇠막대기
✔ 문제 유형: 스택
✔ 문제 풀이 날짜: 24-08-09
- 레이저는 여는 괄호 닫는 괄호의 인접한 쌍 '()' 으로 표현된다
- 쇠막대기는 여는 괄호와 닫는 괄호로 표현된다.
- 쇠막대기를 위로 겹쳐 놓고 레이저를 위에서 수직으로 발사하여 쇠막대기를 자른다.
- 각 쇠막대기를 자르는 레이저는 적어도 하나 존재한다.
- 잘려진 쇠막대기 조각의 총 개수를 구하라
- 반복문을 돌면서 해당 요소가 열린 괄호라면 stack에 push한다.
- 닫힌 괄호라면 스택의 마지막 요소 pop하고 직전의 괄호가 열린 괄호인지 확인하고 맞다면 레이저로, 아니라면 막대기의 끝으로 여긴다.
- 레이저라면 현재 존재하는 막대기 개수만큼 answer에 추가
- 막대기의 끝이라면 answer에 1 추가
```javascript
const bars = [];
if (s[i] === "(") {
bars.push(s[i]);
continue;
}
bars.pop();
if (s[i - 1] === "(") {
answer += bars.length;
continue;
}
answer += 1;
}
return answer;
}
let a = "()(((()())(())()))(())";
console.log(solution(a)); // 17
let b = "(((()(()()))(())()))(()())";
console.log(solution(b)); // 24
``` …

[윤아영] 6-5 쇠막대기

---

06. 자료구조(스택, 큐)/06. 공주구하기/이서인/index.js

✔ 문제 제목: 공주구하기
✔ 문제 유형: 원형 큐
✔ 문제 풀이 날짜: 2024.08.10
- 왕자 N명이 원형으로 앉아있을 때 3을 외친 왕자는 빠진다.
- 왕자 1명이 남을 때 까지 이를 반복하고, 마지막 남은 왕자의 번호를 출력해야 한다.
- Index + 1을 요소로 가지는 왕자 배열을 생성한다.
- 왕자 배열 요소가 1개 남을 때까지 제외해야 하는 인덱스를 갱신하며 배열에서 제거한다.
- 제외해야 하는 인덱스는 + k -1을 해야 나오는데, 원형으로 순회하니까 배열 길이로 나눠준 나머지 값으로 갱신한다.
```javascript
function solution(n, k) {
const princes = Array.from({length: n}, (_, index) => index + 1);
let excludeIndex = 0;
while(princes.length > 1) {
excludeIndex = (excludeIndex + k - 1) % princes.length;
princes.splice(excludeIndex, 1);
}
return princes[0];
}
```
O(n)
- stack으로 풀려고 했는데, 안돼서 봤더니 큐라는 친구를 사용해도 되는 단원이더라고요ㅎㅎ...
```javascript
const prices = Array.from({ length: n }, (_, i) => i + 1);
while (prices.length !== 1) { …
```

[서인] 6-6 공주구하기

---

06. 자료구조(스택, 큐)/06. 공주구하기/윤아영/index.js

✔ 문제 제목: 공주구하기
✔ 문제 유형: 큐
✔ 문제 풀이 날짜: 24-08-11
- n 명의 왕자가 존재한다.
- 동그랗게 앉아 1번부터 차례대로 번호를 외치고 K(특정 숫자)를 외치면 그 번호를 부른 왕자는 제외되고 그 왕자 다음부터 다시 1부터 번호를 외친다.
- 마지막까지 남은 왕자를 출력하세요.
- 왕자가 한 명이 될 때까지 반복하면서 k번째 숫자 전까지 첫번째 사람을 가장 뒤로 보냅니다.
- k 번째 왕자는 shift하고 그 다음 왕자부터 다시 숫자를 셉니다.
```javascript
const prices = Array.from({ length: n }, (_, i) => i + 1);
while (prices.length !== 1) {
prices.push(prices.shift());
}
prices.shift();
}
return prices[0];
}
console.log(solution(8, 3));
```
O(n * k)

[윤아영] 6-6 공주구하기

---

06. 자료구조(스택, 큐)/05. 쇠막대기/정봉찬/index.js

✔ 문제 제목: 쇠막대기
✔ 문제 유형: 자료구조(스택)
✔ 문제 풀이 날짜: 2024-08-09
- 레이저는 여는 괄호와 닫는 괄호의 인접한 쌍 ' ( ) '으로 표현된다.
- 쇠막대기는 왼쪽 끝은 여는 괄호 ' ( '로, 오른쪽 끝은 닫힌 괄호 ' ) '로 표현된다.
- 각 쇠막대기를 자르는 레이저는 적어도 하나 존재한다.
- 레이저는 어떤 쇠막대기의 양 끝점과도 겹치지 않는다.
- 쇠막대기는 자신보다 긴 쇠막대기 위에만 놓일 수 있다. 끝점은 겹치지 않는다.
- 스택이 될 변수 stack을 선언하고 빈배열로 초기화한다.
- 매개변수 s를 for 문으로 s의 길이만큼 반복문을 돈다.
- '('가 나왔을 때 stack에 push하고 continue한다.
- ')'가 나왔을 때 직전 값이 '('면 레이저로 stack에서 pop하고 스택의 길이만큼 answer에 더하고 continue한다.
- ')'가 나왔을 때 직전 값이 ')'면 쇠막대기의 끝으로 stack에서 pop하고 answer에 1을 더한다.
```javascript
const BRACKET_OPEN = '(';
const curr = s[i];
const prev = s[i - 1];
if (curr === BRACKET_OPEN) {
stack.push(curr);
continue;
}
if (prev === BRACKET_OPEN) {
stack.pop();
answer += …
```

[정봉찬] 6-5. 쇠막대기

---

06. 자료구조(스택, 큐)/07. 교육과정설계/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/이서인/index.js

✔ 문제 제목: 선택정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.12
- 주어진 배열을 오름차순으로 정렬하되 선택정렬 기법을 사용한다.
- 최소값의 인덱스를 선언하고, for문으로 순회한다.
- 최소값이 순회 중인 배열 요소보다 크면 최소값의 인덱스를 해당 배열 요소의 인덱스로 재할당한다.
- 배열 요소 인덱스가 현재 최소값 인덱스와 같지 않다면, 최소값을 배열 요소로 재할당한다.
```javascript
let minIndex = i;
for (let j = i + 1; j < arr.length; j++) {
if (arr[minIndex] > arr[j]) {
minIndex = j;
}
}
if (minIndex !== i) {
let swap = arr[minIndex];
arr[minIndex] = arr[i];
arr[i] = swap;
}
}
return arr;
}
```
O(n^2)
-
```javascript
const minValue = Math.min(...arr.slice(i + 1));
if (arr[i] <= minValue) {
continue;
}
const index = arr.indexOf(minValue);
arr[index] = arr[i];
arr[i] = minValue;
}
return answer;
}
let arr = …
```

[서인] 7-1. 선택정렬

---

06. 자료구조(스택, 큐)/07. 교육과정설계/이서인/index.js

✔ 문제 제목: 교육과정설계
✔ 문제 유형: 큐(큐인데 배열로 풀었다...)
✔ 문제 풀이 날짜: 2024.08.12
- 교육과정을 설계할 때 필수 교육을 순서에 맞게 포함해야 한다.
- 교육과정을 배열로 변환해 요소가 필수 교육 배열 요소와 같은지 순서에 맞게 판별하는 식을 만든다.
- 판별식이 truthy면 answer 배열에 필수 교육 요소의 인덱스를 push한다.
- answer의 길이와 필수 교육 배열의 길이가 같고, answer의 요소가 해당 요소의 인덱스와 같으면 YES를 반환한다.
```javascript
let needIndex = 0;
const isNeedCourse = (el) => el === need[needIndex];
[...plan].forEach((el) => {
if (isNeedCourse(el)) {
answer.push(needIndex);
needIndex++;
console.log(answer);
}
});
return answer.length === need.length &&
answer.every((val, index) => val === index)
? "YES"
: "NO";
}
```
O(n)
```javascript
const queue = [...need];
const planArr = [...plan];
for (const el of planArr) {
if (queue.length > 0 && el === …
```

[서인] 6-7. 교육과정설계

---

06. 자료구조(스택, 큐)/07. 교육과정설계/정봉찬/index.js

✔ 문제 제목: 교육과정설계
✔ 문제 유형: 해쉬, 큐
✔ 문제 풀이 날짜: 2024-08-12
- 총 과목은 A, B, C, D, E, F, G가 있다. 여기서 필수과목은 순서대로 꼭 수업계획을 짜야한다.
- 예를 들어 C, B, A가 필수과목이면 C, B, D, A, G, E는 제대로 된 설계이지만 C, G, E, A, D, B는 잘 못 설계된 수업계획이다.
- 수업설계가 잘 됐으면 "YES", 아니면 "NO"를 출력한다.
- ✅ 일단 해쉬로 풀어보기
- 해쉬 변수 hash를 선언한다.
- need와 일치 비교할 변수 myPlan을 선언하고 빈배열로 초기화한다.
- need를 for ... of로 돌면서 Hash에 담는다.
- plan을 반복문 돌면서 hash에 있으면 myPlan에 push한다.
- 반복문이 끝나면 myPlan을 join하고 need와 일치 비교 후에 같으면 "YES" 아니면 "NO"를 return한다.
```javascript
const hash = new Map();
const myPlan = [];
for (const subject of need) {
hash.set(subject, 1);
}
for (const subject of plan) {
if (!hash.get(subject)) {
continue;
}
myPlan.push(subject);
}
if (!(need === myPlan.join(''))) {
answer = 'NO';
}
return answer;
}
let a = …
```

[정봉찬] 6-7. 교육과정설계

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/정봉찬/index.js

✔ 문제 제목: 선택정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024-08-12
- N개의 숫자가 입력되면 오름차순으로 정렬하여 출력하는 프로그램을 작성하세요.
- 정렬하는 방법은 선택정렬입니다.
- answer의 길이 - 1 만큼 반복문을 돈다.
- 반복문 안에서 가장 작은 값을 저장할 변수 minValue을 선언하고 현재 인덱스의 요소로 초기화한다.
- 반복문 안에서 최소값 인덱스를 저장할 변수 minIndex를 선언하고 현재 인덱스로 초기화한다.
- 반복문 안에서 현재 인덱스 + 1부터 answer의 길이만큼 중첩 반복문을 돈다.
- 중첩 반목문에서 minValue, minIndex를 계속 갱신한다.
- 중첩 반복문이 종료되면 현재 인덱스 값과 minValue 인덱스 값을 치환한다.
```javascript
for (let i = 0; i < answer.length - 1; i++) {
let minIndex = i;
for (let j = i + 1; j < answer.length; j++) {
if (answer[j] >= answer[minIndex]) {
continue;
}
minIndex = j;
}
[answer[i], answer[minIndex]] = [answer[minIndex], answer[i]];
}
return answer;
}
let arr = [13, 5, 11, 7, 23, 15];
```
- O(n^2)
- 시작된 두 문제 풀이 …

[정봉찬] 7-1. 선택정렬

---

06. 자료구조(스택, 큐)/07. 교육과정설계/윤아영/index.js

✔ 문제 제목: 교육과정설계
✔ 문제 유형: 큐
✔ 문제 풀이 날짜: 24-08-12
- 필수 과목이 주어집니다. (순서도 지켜야합니다)
- 수업을 적절하게 계획했는지 확인합니다.
- 교육과정을 shift() 하면서 필수과목의 첫번째와 같다면 필수과목도 shift 합니다.
- 필수 과목 배열이 비면 YES 반환하고 아니면 NO를 반환한다.
```javascript
const needArray = [...need];
const planArray = [...plan];
for (let i = 0; i < plan.length; i++) {
if (!needArray.length) {
return "YES";
}
if (planArray.shift() !== needArray[0]) {
continue;
}
needArray.shift();
}
return needArray.length ? "NO" : "YES";
}
let a = "CBA";
let b = "CBDAGE";
```
O(n)

[윤아영] 6-7 교육과정설계

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/윤아영/index.js

✔ 문제 제목: 선택 정렬
✔ 문제 유형: 선택 정렬
✔ 문제 풀이 날짜: 24-08-12
- n개의 숫자들을 오름차순으로 정렬하세요
- 반복문을 돌면서 해당 인덱스와 인덱스 뒤에 숫자들 중 가장 작은 수와 위치를 바꾼다.
```js
const minValue = Math.min(...arr.slice(i + 1));
if (arr[i] <= minValue) {
continue;
}
const index = arr.indexOf(minValue);
arr[index] = arr[i];
arr[i] = minValue;
}
return answer;
}
let arr = [13, 5, 11, 7, 23, 15];
```
O(n^2)
- 선택 정렬이 Array.prototype.sort가 이루어지는 방법인 것 같습니다.
- 두 문제 화이팅!!

[윤아영] 7-1 선택 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/이서인/index.js

✔ 문제 제목: 버블정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.13
- 버블정렬을 사용해 배열 오름차순 정렬한다.
- 인접한 요소를 비교해 더 큰 값을 오른쪽에 위치하게 한다.
```javascript
for (let i = 0; i < arr.length - 1; i++) {
for (let j = 0; j < arr.length - 1 - i; j++)
if (arr[j] > arr[j + 1]) {
}
}
return answer;
}
```
O(n^2)
-
```javascript
for (let j = 0; j < arr.length - 1; j++) {
if (arr[j] < arr[j + 1]) {
continue;
}
}
}
return answer;
}
```
- 버블 정렬은 배열 요소를 순회해 인접한 요소의 값을 비교해 정렬하는 기법이다. 구현은 쉽지만 효율은 낮다. 버블처럼 제일 큰 값이 배열 끝으로 가므로 버블 정렬이라고 한다.

[서인] 7-2. 버블정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/이서인/index.js

✔ 문제 제목: Special Sort
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.13
- 배열 중 음의 정수를 왼쪽에, 양의 정수는 오른쪽에 정렬해야 한다.
- 기존 정수의 순서는 바뀌지 않고, 0은 배열에 포함하지 않는다.
- 버블 정렬
```javascript
for (let i = 0; i < arr.length - 1; i++) {
for (let j = 0; j < arr.length - 1 - i; j++) {
if (arr[j] > 0 && arr[j + 1] < 0) {
}
}
}
return answer;
}
```
O(n^2)
-
```javascript
const minusArr = [...arr].filter((el) => el <= 0);
const plusArr = [...arr].filter((el) => el > 0);
return [...minusArr, ...plusArr];
```
-

[서인] 7-3. Special Sort

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/윤아영/index.js

✔ 문제 제목: 버블 정렬
✔ 문제 유형: 버블 정렬
✔ 문제 풀이 날짜: 24-08-13
- 버블 정렬 방법을 사용해 오름차순으로 정렬하세요
- 해당 인덱스와 다음 인덱스의 숫자를 비교하여 작다면 위치를 바꿔줍니다.
- 배열의 길이 - 1 만큼 반복합니다.
```javascript
for (let j = 0; j < arr.length - 1; j++) {
if (arr[j] < arr[j + 1]) {
continue;
}
}
}
return answer;
}
```
O(n^2)

[윤아영] 7-2 버블 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/윤아영/index.js

✔ 문제 제목: Special Sort
✔ 문제 유형: 버블 정렬
✔ 문제 풀이 날짜: 24-08-13
- 음수는 왼쪽에 양수는 오른쪽에 정렬하되 기존의 순서에는 변함이 없어야한다.
- 버블 정렬를 활용하여 정렬한다.
```javascript
for (let i = 0; i < arr.length - 1; i++) {
for (let j = 0; j < arr.length - i - 1; j++) {
if (arr[j] > 0 && arr[j + 1] < 0) {
[arr[j + 1], arr[j]] = [arr[j], arr[j + 1]];
}
}
}
return answer;
}
let arr = [1, 2, 3, -3, -2, 5, 6, -6];
```
O(n^2)
```javascript
const positive = arr.filter((num) => num > 0);
const negative = arr.filter((num) => num < 0);
return [...negative, ...positive];
}
```
- 두 번째 반복문에서 처음에는 `arr.length - 1`을 했었는데 `arr.length - i - 1`도 가능했다. 근데 이유를 모르겠다.

[윤아영] 7-3 Special Sort

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/이서인/index.js

✔ 문제 제목: 삽입 정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.14
- 주어진 배열을 삽입 정렬 기법을 사용해 오름차순 정렬한다.
- 배열을 순회하며 이미 정렬된 요소와 비교해 적절한 위치에 삽입한다.
```javascript
for (let j = i; j > 0; j--) {
if (arr[j] >= arr[j - 1]) {
break;
}
if (arr[j] < arr[j - 1]) {
[arr[j], arr[j - 1]] = [arr[j - 1], arr[j]];
}
}
}
return answer;
}
```
O(n^2)
-
```javascript
```
- 같은 듯 다른 정렬 기법
- break 문: 반복문을 즉시 탈출하고 반복문 바로 뒤의 문장으로 제어를 이동시킨다. 반복문에서 특정 조건이 충족되면 반복을 중지하고 반복문을 탈출한다.
- continue 문: 현재 반복을 중지하고 다음 반복을 실행한다.

[서인] 7-4. 삽입 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/이서인/index.js

✔ 문제 제목: LRU
✔ 문제 유형: LRU 알고리즘
✔ 문제 풀이 날짜: 2024.08.14
- 캐시메모리의 size만큼 배열 요소를 가질 수 있고, 배열 길이 이상일 때 최신 데이터가 들어오면 오래된 데이터가 pop된다.
- 같은 값의 데이터가 들어올 때 최신 데이터로 교체된다.
- 중복 요소를 제거하고, 최신 값을 삽입한다.
- 배열 길이 이상일 땐 오래된 요소를 pop한다.
```javascript
function solution(size, arr) {
let answer = Array.from({ length: size }, () => 0);
if (answer.includes(arr[i])) {
answer = answer.filter((item) => item !== arr[i]);
}
if (answer.length >= size) {
answer.pop();
}
answer.unshift(arr[i]);
}
return answer;
}
```
O(n*m)
-
```javascript
function solution(size, arr) {
let answer = Array.from({ length: size }, () => 0);
const task = arr[i];
const cachedTaskIndex = answer.indexOf(task);
if (cachedTaskIndex !== -1) { …
```

[서인] 7-5. LRU

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/윤아영/index.js

✔ 문제 제목: 삽입정렬
✔ 문제 유형: 삽입정렬
✔ 문제 풀이 날짜: 24-08-14
- 현재 인덱스의 값을 앞의 인덱스 값들과 비교하면서 현재 인덱스 값이 이전 값보다 작다면 순서를 바꾼다.
- 현재 인덱스 값(arr[i])와 이전 인덱스 값(arr[i - 1])의 값을 비교한다.
- arr[i]가 더 작다면 순서를 바꾸고 크거나 같다면 반복문을 빠져나온다.
```javascript
for (let j = i; j > 0; j--) {
if (arr[j] >= arr[j - 1]) {
break;
}
if (arr[j] < arr[j - 1]) {
[arr[j], arr[j - 1]] = [arr[j - 1], arr[j]];
}
}
}
return arr;
}
let arr = [11, 7, 5, 6, 10, 9];
```
O(n^2)
- 정렬의 방법은 다양하고 어떤 순간에 어떤 알고리즘을 선택해야할까?
- [정렬 알고리즘](https://hyo-ue4study.tistory.com/68)

[윤아영] 7-4 삽입정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/윤아영/index.js

✔ 문제 제목: LRU(Least Recently Used)
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 24-08-15
- 캐시 사이즈가 주어졌을 때 최근에 사용된 작업부터 차례대로 출력합니다.
- for문을 돌면서 answer에 작업을 추가합니다.
- 만약에 이미 존재하는 작업이라면 기존에 존재하는 작업을 없애고 앞에 추가합니다.
```javascript
function solution(size, arr) {
if (answer.includes(arr[i])) {
answer = [arr[i], ...answer.filter((num) => num !== arr[i])];
continue;
}
answer.unshift(arr[i]);
}
return answer.slice(0, size);
}
let arr = [1, 2, 3, 2, 6, 2, 3, 5, 7];
console.log(solution(5, arr));
```
O(n^2)
```javascript
function solution(size, arr) {
return arr.filter((num, i) => arr.lastIndexOf(num) === i).reverse().slice(0, size);
}
```
- 정렬로 구분되어 있는 문제인데 어떻게 정렬을 해야 할 지 모르겠네요

[윤아영] 7-5 LRU

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/정봉찬/index.js

✔ 문제 제목: 삽입정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024-08-14
- N개의 숫자가 입력되면 오름차순으로 정렬하여 출력한다.
- 삽입정렬을 활용한다.
- i = 1 부터 배열의 길이만큼 반복문을 선언한다. 증감식은 i++
- j = i - 1부터 0 보다 크거나 같은 조건으로 중첩 반복문을 선언한다. 증감식은 j--
- 중첩 반복문에서 arr[j]의 값과 arr[j + 1]의 값을 비교해서 arr[j + 1]이 작다면 arr[j]와 arr[j + 1]의 값을 교체한다.
```javascript
for (let j = i - 1; j >= 0; j--) {
if (arr[j] < arr[j + 1]) {
continue;
}
}
}
return answer;
}
let arr = [11, 7, 5, 6, 10, 9];
```
- O(n^2)
- 오늘부터 휴가입니다~ 🏖️
- 서인님 PR을 보고 `n회전 + 1` 만큼은 오름차순 정렬이 되어 있으니까 `continue`가 아닌 `break`를 쓰면 더 좋을 거 같다고 느꼈습니다!

[정봉찬] 7-4. 삽입정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/이서인/index.js

✔ 문제 제목: 장난꾸러기 현수
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.15
- 오름차순 배열인데, 오름차순에 부합하지 않는 요소의 인덱스 + 1인 값을 구해야 한다.
- 오름차순 배열을 구한다.
- map, filter 메서드로 기존 배열과 오름차순 배열을 비교하고, 오름차순에 부합하지 않는 요소의 인덱스 + 1을 반환한다.
```javascript
const sortedArr = [...arr].sort((a, b) => a - b);
answer = arr
.map((person, index) => {
return person !== sortedArr[index] ? index + 1 : -1;
})
.filter((index) => index !== -1);
return answer;
}
```
O(nlogn)
-
```javascript
answer.push(arr.findIndex((element, index) => element >= arr[index + 1]) + 1);
answer.push(
arr.findLastIndex((element, index) => element >= arr[index - 1] + 1)
);
return answer;
}
```
- 현수야 장난치지 말자

[서인] 7-6. 장난꾸러기 현수

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/이서인/index.js

✔ 문제 제목: 좌표 정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 2024.08.16
- 좌표 첫 번째 요소를 비교해 오름차순 정렬한다.
- 좌표 첫 번째 요소가 동일하면 두 번째 요소로 오름차순 정렬한다.
- 버블 정렬
```javascript
for (let i = 0; i < answer.length - 1; i++) {
for (let j = 0; j < answer.length - 1 - i; j++) {
if (answer[j][0] > answer[j + 1][0]) {
[answer[j], answer[j + 1]] = [answer[j + 1], answer[j]];
} else if (
answer[j][0] === answer[j + 1][0] &&
answer[j][1] > answer[j + 1][1]
) {
[answer[j], answer[j + 1]] = [answer[j + 1], answer[j]];
}
}
}
return answer;
}
```
```javascript
// 수정한 풀이
for (let i = 0; i < answer.length - 1; i++) {
for (let j = 0; j < answer.length - 1 - i; j++) {
if (answer[j][0] < answer[j + 1][0]) {
continue;
}
if (answer[j][1] < answer[j + 1][1]) { …
```

[서인] 7-7. 좌표 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/윤아영/index.js

✔ 문제 제목: 장난꾸러기 현수
✔ 문제 유형: 정
✔ 문제 풀이 날짜: 24-08-15
- 키가 작은 학생부터 반 번호 1번부터 N번까지 부여합니다.
- 현수는 자기보다 키 작은 짝꿍과 자리를 바꿉니다.
- 이렬ㄹ로 서있는 키 정보가 주어질 때 현수가 받은 번호와 짝궁이 받은 번호를 차례대로 출력하세요
- 현수의 번호를 구할 때는 반복문을 돌면서 뒷사람의 키가 앞사람키보다 작을 때 현수의 번호를 알 수 있습니다.
- 짝궁의 번호는 반복문을 뒤에서부터 둘면서 앞사람의 키가 뒤사람보다 클 때 짝궁의 번호를 알 수 있습니다.
```javascript
if (arr[i] < arr[i + 1]) {
continue;
}
answer.push(i + 1);
break;
}
for (let i = arr.length - 1; i > 0; i--) {
if (arr[i - 1] <= arr[i]) {
continue;
}
answer.push(i + 1);
break;
}
return answer;
}
let arr = [120, 125, 152, 130, 135, 135, 143, 127, 160];
let arr2 = [120, 130, 150, 150, 130, 150];
console.log(solution(arr2));
```
O(n)
- 조건문이 적절하지 않았다.
- 키가 같은 사람이 여러 명일때 적절하지 않은 답이 …

[윤아영] 7-6 장난꾸러기 현수

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/윤아영/index.js

✔ 문제 제목: 회의실 배정
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 24-08-16
- 한 개의 회의실이 존재합니다.
- 각 회의에 대한 시간 시간과 끝나는 시간이 주어집니다.
- 각 회의가 겹치지 않게 하면서 회의실을 사용할 수 있는 최대 수의 회의를 찾으세요
- 각 회의 시간에 따라 정렬합니다.
- 이중 for문을 돕니다.
- time(끝나는 시간)을 선언합니다.
- time이 null이거나 시작 시간과 같다면 time을 해당 회의의 끝나는 시간으로 재할당하고 스케쥴에 추가합니다.
- 스케쥴의 길이가 가장 긴 것을 answer로 반환합니다.
```javascript
function solution(meeting) {
meeting.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
for (let i = 0; i < meeting.length; i++) {
const schedule = [];
let time = null;
if (meeting.length - i < answer) {
break;
}
for (let j = i; j < meeting.length; j++) {
const [start, end] = meeting[j];
if (!time || start === time) {
time = end;
schedule.push(meeting[j]);
}
}
answer = Math.max(answer, schedule.length);
}
return answer;
}
let arr = [
[1, 4],
[2, 3],
[3, 5],
[4, …
```

[윤아영] 7-8 회의실 배정

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/윤아영/index.js

✔ 문제 제목: 좌표 정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 24-08-15
- 평면상의 좌표가 주어지면 모든 좌표를 오름차순으로 정렬하는 프로그램
- 정렬 기준은 x값에 의해서 정렬하고 x값이 같다면 y 값에 의해 정렬합니다.
- sort 메서드를 사용했습니다.
```javascript
return arr.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
}
let arr = [
[2, 7],
[1, 3],
[1, 2],
[2, 5],
[3, 6],
];
```
O(nlogn)

[윤아영] 7-7 좌표 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/윤아영/index.js

✔ 문제 제목: 결혼식
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 24-08-19
- 피로연에 참석하는 친구들의 도착 시간과 떠나는 시간이 이중 배열의 형태로 주어집니다.
- 동시에 존재하는 최대 인원수를 구하세요
- 떠나는 시간을 기준으로 정렬합니다.
- 떠나는 시간과 현재 수용 인원, 최대 수용 인원을 선언합니다.
- 배열을 돌면서 떠나는 시간과 현재 손님의 오는 시간을 비교하여 끝나는 시간이 더 늦다면 현재 수용 인원을 늘리고 최대 수용 인원은 업데이트합니다.
- 오는 시간이 더 늦거나 같다면 해당 손님의 떠나는 시간으로 떠나는 시간으로 업데이트하고 현재 수용 인원도 줄입니다. 
```javascript
function solution(times) {
times.sort((a, b) => a[1] - b[1] || a[0] - b[1]);
let people = 0;
let endTime = times[0][1];
for (const [start, end] of times) {
if (endTime > start) {
people++;
answer = Math.max(answer, people);
continue;
}
people--;
endTime = end;
}
return answer;
}
let arr = [
[14, 18],
[12, 15],
[15, 20],
[20, 30],
[5, 14],
];
```
O(nlogn)
- 주어진 times를 돌면서 해당 시간(인덱스)에 …

[윤아영] 7-9 결혼식

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/윤아영/index.js

✔ 문제 제목: 이분 검색
✔ 문제 유형: 이분 검색
✔ 문제 풀이 날짜: 24-08-19
- 이분 검색을 활용하여 정렬된 배열에서 target이 몇 번째에 있는지 구하세요
- 중복된 값은 존재하지 않습니다
- 배열을 정렬합니다.
- 검색할 시작점과 끝점을 선언합니다.
- 중간점에 위치한 요소가 target과 같다면 인덱스 + 1을 반환합니다.
- 중간점에 위치한 요소가 target보다 크다면 끝점을 중간점 - 1로 재할당합니다.
- 중간점에 위치한 요소가 target보다 작다면 시작점을 중간점 + 1로 재할당합니다.
- 중간점은 다시 검사할 필요가 없기 때문에 끝점 혹은 시작점은 중간점 - 1, 중간점 + 1로 재할당해줍니다.
- 만약 시작점이 끝점보다 크다면 배열에 해당 타겟이 없다고 판단하고 반복문을 멈추고 -1을 반환합니다.
```javascript
arr.sort((a, b) => a - b);
let left = 0;
let right = arr.length - 1;
const middle = Math.floor((left + right) / 2);
if (arr[middle] === target) {
return middle + 1;
}
if (arr[middle] > target) {
right = middle - 1;
continue;
}
left = middle + 1;
}
return -1;
}
let arr = [23, 87, 65, 12, 57, 32, 99, 81];
``` …

[윤아영] 7-10 이분 검색

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js

✔ 문제 제목: 회의실 배정
✔ 문제 유형: 그리디
✔ 문제 풀이 날짜: 2024.08.16
- 회의실을 예약한 미팅의 시작 시간과 끝 시간이 배열 요소로 주어진다.
- 시간이 겹치지 않게 회의실을 사용할 수 있는 최대 미팅 수를 구해야한다.
- 회의 끝 시간을 기준으로 오름차순 정렬한다.
- 이전 회의 끝 시간보다 다음 회의 시작 시간이 크거나 같으면 이전 회의 시간을 다음 회의 시간의 끝 시간으로 재할당하고, answer에 1을 더한다.
```javascript
function solution(meeting) {
let preEnd = 0;
const sortedArr = meeting.sort((a, b) =>
a[1] === b[1] ? a[0] - b[0] : a[1] - b[1]
);
sortedArr.forEach((time) => {
const [start, end] = time;
if (start >= preEnd) {
preEnd = end;
answer++;
}
});
return answer;
}
```
O(nlogn)
-
```javascript
function solution(meeting) {
meeting.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
for (let i = 0; i < meeting.length; i++) {
let count = 1;
let endTime = meeting[i][1];
for (let j = i + 1; j < meeting.length; j++) {
if …
```

[서인] 7-8. 회의실 배정

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/이서인/index.js

✔ 문제 제목: 결혼식
✔ 문제 유형: 정렬(?)
✔ 문제 풀이 날짜: 2024.08.16
- 하객들의 결혼식 피로연 참가 시간(입장, 퇴장)을 요소로 담은 배열이 있다.
- 피로연장에 동시에 존재하는 최대 하객 수를 구해야 한다.
- 시간 배열을 입장 시간으로 오름차순 정렬한다.
- 이전 하객의 퇴장시간보다 현재 하객(요소)의 입장 시간 - 1이 크거나 같으면 동시 존재 하객 수를 1부터 다시 시작해야 하고, 그렇지 않으면 기존 동시 존재 하객 수에 1을 더한다.
- 이전 하객의 퇴장시간을 현재 하객 퇴장시간으로 재할당하고, 동시 존재 하객 수와 기존 답을 비교해 더 큰 수로 답을 갱신한다.
```javascript
function solution(times) {
let preEnd = 0;
let currentPeople = 0;
const sortedTimes = times.sort((a, b) => a[1] - b[1] || a[0] - b[0]);
sortedTimes.forEach((time) => {
const [start, end] = time;
if (start >= preEnd - 1) {
currentPeople = 1;
} else {
currentPeople += 1;
}
preEnd = end;
answer = Math.max(answer, currentPeople);
});
return answer;
}
```
O(nlogn)
- sort 콜백함수를 잘못 썼다. 입장 시간과 이전 하객의 퇴장 시간을 비교할 때 조건문을 잘못 썼다. …

[서인] 7-9. 결혼식

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/이서인/index.js

✔ 문제 제목: 이분검색
✔ 문제 유형: 이분검색
✔ 문제 풀이 날짜: 2024.08.17
- N개의 수를 오름차순 정렬한 후 이분검색으로 M이 몇 번째에 있는지 출력해야 한다.
- 배열을 오름차순으로 정렬한다.
- 왼쪽, 오른쪽 인덱스를 변수로 선언한다.
- 중간 인덱스도 변수로 선언한다.
- 중간 인덱스의 요소가 M과 같으면 정답으로 반환한다.
- 중간 인덱스의 요소가 M보다 크면 오른쪽 인덱스를 중간 인덱스 - 1로 조정한다.
- 중간 인덱스의 요소가 M보다 작으면 왼쪽 인덱스를 중간 인덱스 + 1로 조정한다.
```javascript
let left = 0;
let right = arr.length - 1;
arr.sort((a, b) => a - b);
let mid = Math.floor((left + right) / 2);
if (arr[mid] === target) {
answer = mid + 1;
break;
}
if (arr[mid] > target) {
right = mid - 1;
}
if (arr[mid] < target) {
left = mid + 1;
}
}
return answer;
}
```
O(nlogn)
-
```javascript
arr.sort((a, b) => a - b);
const binarySearch = (target, arr, start, end) => {
const …
```

[서인] 7-10. 이분검색

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/이서인/index.js

✔ 문제 제목: 뮤직비디오
✔ 문제 유형: 이분검색(결정 알고리즘)
✔ 문제 풀이 날짜: 2024.08.18
- 각 노래의 재생 시간이 배열 요소로 주어지고, 레코드 수가 주어진다.
- 레코드에 적절히 배분했을 때 레코드가 필요한 최소 용량을 구해야 한다.
- 노래 리스트 중 가장 긴 노래를 시작 지점으로 둔다.(DVD 1개라고 가정)
- 노래 리스트의 합을 끝 지점으로 둔다.(DVD 노래 수만큼이라고 가정)
- while 문을 돌면서 현재 노래를 추가했을 때 sum이 mid를 초과하면 다음 DVD로 넘어가야 하므로 새 DVD를 시작한다.
- 현재 노래를 추가해도 sum이 mid를 초과하지 않으면 그 노래를 현재 DVD에 추가한다.
- 마지막으로 계산된 sum 값을 DVD 배열에 추가한다.
- 현재 사용한 DVD 개수가 목표 개수와 같으면 DVD에 저장된 값들 중 최대 값을 answer에 저장하고 break문으로 루프 종료한다.
- 현재 사용한 DVD 개수가 목표 개수보다 작다면 end를 mid - 1로 줄이고, 현재 사용한 DVD 개수가 목표 개수보다 많다면 start를 mid + 1로 증가시켜 탐색 범위를 넓힌다.
```javascript
let start = Math.max(...songs);
let end = arr.reduce((a, b) => a + b, 0);
let DVD = [];
while (start <= end) {
let mid = parseInt((start + end) / 2);
let sum = …
```

[서인] 7-11. 뮤직비디오

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/이서인/index.js

✔ 문제 제목: 마구간 정하기
✔ 문제 유형: 이분탐색
✔ 문제 풀이 날짜: 2024.08.20
- N개의 마구간에 C마리의 말을 넣어야 한다.
- 각 마구간에 한 마리의 말만 넣을 수 있다.
- 두 말 사이 거리 중 최대값을 구해야한다.
- 말 count 함수를 정의한다.
- 가장 첫 번째 마구간에 말을 둬야 한다.
- 현재 위치부터 마지막에 위치한 말의 거리가 주어진 distance 값(mid)보다 크거나 같다면 그 위치에 말이 있어야 하므로 말의 위치를 옮긴다.
- 이분탐색을 활용한 solution 함수를 정의한다.
- 오름차순 정렬한 후 말이 각 거리이상 떨어져있다고 가정하고 mid를 구한다.
- 말의 수(count(positions, mid))가 주어진 수 이상일 대 탐색 범위가 더 커야 말들이 멀리 떨어진 최적의 거리를 구할 수 있으므로 start 포인트를 옮겨준다.
- 거리가 너무 멀어지면 말이 주어진 수만큼 들어가지 못하기 때문에 end를 옮겨 더 적은 거리를 탐색하게 범위를 좁힌다.
```javascript
function count(positions, distance) {
let cnt = 1;
let lastPosition = positions[0];
for (let i = 1; i < positions.length; i++){
if (positions[i] - lastPosition >= distance) {
cnt++;
lastPosition = positions[i]
}
}
return cnt;
}
function solution(c, stable) {
stable.sort((a, …
```

[서인] 7-12. 마구간 정하기

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/이서인/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/01. 재귀함수/이서인/index.js

✔ 문제 제목: 재귀함수
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024.08.20
- 자연수 n이 입력되면 1부터 n까지 출력해야 한다.
- n이 0보다 크면 answer 배열에 unshift 한다.
- 그리고 n - 1을 재귀함수의 인수로 넣어 호출한다.
```javascript
let answer = []
if (L > 0) {
answer.unshift(L)
DFS(L - 1)
}
}
DFS(n);
console.log(answer.join(' '))
}
```
O(n)
-
```javascript
if (L < 1) {
return;
}
DFS(L - 1);
console.log(L);
}
DFS(n);
}
solution(3);
```
```javascript
if (L === 1) {
return L;
}
return `${DFS(L - 1)} ${L}`;
}
console.log(DFS(n));
}
solution(3);
```
- 이제 어렵지만 단골 출제되는 DFS, BFS 시작인가요

[서인] 8-1. 재귀함수

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/정봉찬/index.js

✔ 문제 제목: 이분검색
✔ 문제 유형: 이분검색
✔ 문제 풀이 날짜: 2024-08-17
- N개의 수를 오름차순으로 정렬한 후 M이 몇 번째에 있는지 구하라.
- 중복값은 없다.
- Array.prototype.sort 메서드로 오름차순 정렬한다.
- start, end, mid를 선언하고 각가 0, arr.length - 1, Math.floor((start + end) / 2)로 초기화한다.
- target !== arr[mid]의 조건으로 while문을 작성한다.
- start가 end보다 크다면 break로 while문을 중단한다.
- target이 arr[mid]의 값보다 크거나 작은지에 따라 start, end, mid를 설정한다.
```javascript
let answer;
arr.sort((a, b) => a - b);
let start = 0;
let end = arr.length - 1;
let mid = Math.floor((start + end) / 2);
while (target !== arr[mid]) {
if (start > end) {
break;
}
if (target > arr[mid]) {
start = mid + 1;
} else {
end = mid - 1;
}
mid = Math.floor((start + end) / 2);
}
answer = mid + 1;
return answer;
}
let arr = [23, 87, 65, 12, 57, 32, 99, 81]; …
```

[정봉찬] 7-10. 이분검색

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/01. 재귀함수/정봉찬/index.js

✔ 문제 제목: 재귀함수
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024-08-18
- 자연수 N을 재귀함수를 이용하여 1부터 N까지를 출력하시오.
- 실행 컨텍스트 스택의 개념을 활용해서 DFS(L - 1)을 실행 후 console.log(L)을 출력한다.
- L < 1 조건이면 return으로 함수를 종료한다.
- DFS(L - 1)의 실행 컨텍스트가 스택에 push되면 console.log(L)의 렉시컬 스코프는 현재 실행중인 컨텍스트가 아니기 때문에 보류된다.
```javascript
if (L < 1) {
return;
}
DFS(L - 1);
console.log(L);
}
DFS(n);
}
solution(3);
```
- ?
- 새로운 섹션이 시작됐어요. 파이팅! 👋

[정봉찬] 8-1. 재귀함수

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/윤아영/index.js

✔ 문제 제목: 이진수 출력(재귀)
✔ 문제 유형: 재귀 함수
✔ 문제 풀이 날짜: 24-08-20
- 10진수 N이 입력되면 2진수로 변환하여 출력합니다.
- 재귀함수를 이용합니다.
- n / 2 < 1 작아질 때까지 함수를 재귀 호출합니다.
```javascript
const convertBinary = (n) => {
if (n / 2 < 1) {
return n % 2;
}
return `${convertBinary(Math.floor(n / 2))}${n % 2}`;
};
return +convertBinary(n);
}
console.log(solution(11));
```
O(logn)

[윤아영] 8-2 이진수 출력(재귀)

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/윤아영/index.js

✔ 문제 제목: 뮤직비디오
✔ 문제 유형: 이분 검색
✔ 문제 풀이 날짜: 24-08-20
- m개의 DVD를 만들 때 필요한 최소 크기를 구하세요.
- count 함수를 정의합니다.
- 해당 크기로 dvd를 만들다면 몇 개의 dvd를 만들 수 있는지 세어줍니다.
- 이분 검색을 하면서 count가 정해진 개수보다 적다면 크기를 줄이고 크다면 늘립니다.
```javascript
const count = (songs, length) => {
let count = 1;
let sum = 0;
for (const song of songs) {
if (sum + song > length) {
count++;
sum = song;
continue;
}
sum += song;
}
return count;
};
let answer;
let left = Math.max(...songs);
let right = songs.reduce((acc, cur) => acc + cur, 0);
const middle = Math.floor((left + right) / 2);
if (count(songs, middle) <= m) {
answer = middle;
right = middle - 1;
continue;
}
left = middle + 1;
}
return answer;
}
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
console.log(solution(3, arr));
```
O(nlogn)
- …

[윤아영] 7-11 뮤직비디오

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/윤아영/index.js

✔ 문제 제목: 마구간 정하기
✔ 문제 유형: 이분 검색
✔ 문제 풀이 날짜: 24-08-21
- n개의 마구간이 수직선상에 있습니다.
- c마리의 말을 가지고 있는데 말들은 최대한 떨어뜨려서 배치하고 싶습니다.
- 가장 가까운 두 말의 거리를 출력합니다.
- 마구간 배열을 정렬합니다.
- count 함수를 정의합니다.
- 마구간 배열과 최소 간격을 매개변수로 받습니다. 
- 현재 말의 위치와 다음 말의 거리가 최소 간격을 넘어갈 때, count를 1 증가시키고 현재 말의 위치를 업데이트 시킵니다.
- count와 말을 개수를 비교하면서 이분 탐색합니다.
```javascript
const count = (stable, space) => {
let count = 1;
let currentPoint = stable[0];
for (let i = 1; i < stable.length; i++) {
if (stable[i] - currentPoint >= space) {
count++;
currentPoint = stable[i];
}
}
return count;
};
function solution(c, stable) {
let answer;
stable.sort((a, b) => a - b);
let left = stable[0];
let right = stable[stable.length - 1];
const middle = Math.floor((left + right) / 2);
if (count(stable, middle) >= c) {
answer = …
```

[윤아영] 7-12 마구간 정하기

---

03. 문자열 탐색/01. 회문문자열/김보경/index.js
03. 문자열 탐색/02. 유효한 팰린드롬/김보경/index.js
03. 문자열 탐색/03. 숫자만 추출/김보경/index.js
03. 문자열 탐색/04. 가장 짧은 문자거리/김보경/index.js
03. 문자열 탐색/05. 문자열 압축/김보경/index.js

✔ 문제 제목: 코딩테스트 섹션 3
✔ 문제 유형: 몰?루
✔ 문제 풀이 날짜: 8월 20일
- 4, 5번 문제가 조금 난이도가 있었지만 클리어 해버렸슴둥
- for문 사용
```javascript
// 여기에 코드 작성해주세요 !
```
-
```javascript
```
- 다른 풀이가 있다면 지적 부탁드려요!

[김보경] 섹션 3 문제 풀이

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/이서인/index.js

✔ 문제 제목: 이진수 출력(재귀)
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024.08.21
- 재귀함수를 이용해 10진수 n을 이진수로 출력해야 한다.
- n가 0이 되기 전까지 n을 2로 나눈 나머지를 answer에 더해주며 해당 함수를 재귀호출한다.
- 이때 n은 2로 나눈 몫으로 재할당한다.
```javascript
if (n > 0) {
answer = n % 2
n = parseInt(n / 2)
answer = solution(n) + answer;
}
return answer
}
```
O(logn) => n이 2의 거듭제곱으로 줄어들므로, 호출 횟수는 logn에 비례한다.
-
```javascript
if (L === 1) {
return 1;
}
return DFS(Math.trunc(L / 2)) + '' + (L % 2);
}
answer = DFS(n);
return answer;
}
```
- 알듯 말듯한 느낌

[서인] 8-2. 이진수 출력(재귀)

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/03. 이진트리순회/이서인/index.js

✔ 문제 제목: 이진트리순회
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.08.21
- 이진트리를 전위순회, 후위순회로 구현해야 한다.
- 노드가 v보다 크면 탐색하지 않는다.
- 그렇지 않으면 왼쪽 자식 노드(v * 2), 오른쪽 자식 노드(v * 2 + 1), 루트 노드(v)로 순회한다.
```javascript
// 전위 순회
function DFS(v) {
if (v > 7) return;
else {
answer += (v + ' ');
DFS(v * 2);
DFS(v * 2 + 1);
}
}
DFS(n);
return answer;
}
// 후위 순회
function DFS(v) {
if (v > 7) return;
else {
DFS(v * 2);
DFS(v * 2 + 1);
answer += (v + ' ');
}
}
DFS(n);
return answer;
}
```
O(n) => 트리 노드 수에 비례
- 텍스트론 알겠는데, 저걸 어떤 식으로 구현할지 모르겠어서 답지 참고
```javascript
```
- 봉찬님의 정리 노트가 많은 도움이 됐습니다. 감사합니다!
- 전위 순회(preorder): 부모 노드 -> 왼쪽 자식 노드 -> 오른쪽 자식 노드
- 중위 순회(inorder): 왼쪽 자식 노드 -> 부모 노드 -> 오른쪽 자식 노드
- 후위 순회(postorder): 왼쪽 자식 노드 -> 오른쪽 자식 …

[서인] 8-3. 이진트리순회

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/04. 부분집합 구하기/윤아영/index.js

✔ 문제 제목: 부분 집합 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-08-22
- 1 ~ N 까지 원소를 갖는 집합의 부분 집합을 모두 출력합니다.
- 인덱스와 path를 매개변수로 받는 DFS 함수를 정의합니다.
- 모든 부분 집합을 구해야하기 때문에 answer.push(path)를 해줍니다.
- 현재 인덱스에서 유효 범위까지 반복문을 돌면서 재귀 함수를 호출해줍니다.
```javascript
const numbers = Array.from({ length: n }, (_, i) => i + 1);
const DFS = (index, path) => {
answer.push(path);
for (let i = index; i < n; i++) {
DFS(i + 1, [...path, numbers[i]]);
}
};
DFS(0, []);
return answer;
}
console.log(solution(3));
```
?
- DFS를 모두 복수하는 그날까지 화이팅!

[윤아영] 8-4 부분집합 구하기(복습예정)

---

04. 완전탐색(블루투포스)/01. 자리수의 합/김보경/index.js
04. 완전탐색(블루투포스)/02. 뒤집은 소수/김보경/index.js
04. 완전탐색(블루투포스)/03. 멘토링/김보경/index.js
04. 완전탐색(블루투포스)/04. 졸업선물/김보경/index.js
04. 완전탐색(블루투포스)/05. K번째 큰 수/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/김보경/index.js

✔ 문제 제목:
- 04번 졸업 선물은 좀 어려웠는데 테스트 케이스가 더 있으면 어떻게되었을지 잘 모르겠네요
✔ 문제 유형:
- 완전탐색(부르트포스)
✔ 문제 풀이 날짜: 08.26
- 모든 경우의 수를 계산 혹은 고려
- for문 때려박아보리기~
```javascript
let result = [];
product.sort(
(a, b) =>
a.reduce((acc, el) => acc + el, 0) - b.reduce((acc, el) => acc + el, 0)
);
for (let i = 0; i < product.length; i++) {
let count = 0;
let limit = m;
let hasCouponProduct = [...product];
hasCouponProduct[i][0] = hasCouponProduct[i][0] / 2;
hasCouponProduct.sort(
(a, b) =>
a.reduce((acc, el) => acc + el, 0) - b.reduce((acc, el) => acc + el, 0)
);
for (let j = 0; j < hasCouponProduct.length; j++) {
if (i === j) continue;
let price = hasCouponProduct[j].reduce((acc, el) => acc + el, 0);
if (limit > price) {
limit - price;
count++;
} else if (limit < price) …
```

[김보경] 섹션4 부르트포스 문제 풀이

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/03. 이진트리순회/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/04. 부분집합 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/05. 합이 같은 부분집합/이서인/index.js

✔ 문제 제목: 합이 같은 부분집합
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.08.23
- 주어진 배열을 부분집합 2개로 나눴을 때 각 부분집합의 합이 동일하면 YES를 출력한다. 동일하지 않으면 NO를 출력한다.
- 배열 요소 전체 합을 구한다.
- 하위 문제: 첫 번째 요소를 포함하거나 포함하지 않는 부분집합을 만든다.
- 베이스 케이스: 부분집합 합이 전체 합의 반에 도달하면 return 한다. / 부분집합 합이 전체 합의 반보다 크면 함수를 종료한다. / 인덱스가 배열 길이 이상이면 함수를 종료한다.
- 재귀 케이스: 다음 요소를 포함하거나 포함하지 않는 경우를 재귀 호출한다.
```javascript
let answer = 'NO';
const totalSum = arr.reduce((a, b) => a + b, 0);
function DFS(index, currentSum) {
if (currentSum > totalSum / 2) return;
if (currentSum === totalSum / 2) {
answer = 'YES';
return;
}
if (index >= arr.length) return;
DFS(index + 1, currentSum + arr[index]);
DFS(index + 1, currentSum)
}
DFS(0, 0)
return answer;
}
```
O(2^n)
- 배열 합을 가지고 풀이하는 것까진 접근했는데, 하위 문제를 도출하는 것부터 막혔다. 어려워
```javascript
function …
```

[서인] 8-5. 합이 같은 부분집합

---

02. 1, 2차원 배열 탐색/01. 큰 수 출력하기/노은수/index.js

✔ 문제 유형: 배열 순회, 배열 탐색
✔ 문제 풀이 날짜: 7월 24일
- for 문 순회
- for 문과 if 문을 통해: 제어문으로 설계했습니다.
```javascript
if (arr[i - 1] < arr[i]) {
}
}
return answer;
}
```
-  O(n), n은 배열의 개수, 따라서 O(100), 약 1/1,000,000 초
-
```javascript
```
-

[노은수] 2장 1차원 배열 1번 문제

---

02. 1, 2차원 배열 탐색/06. 격자판 최대합/백지원/index.js

✔ 문제 제목: 격자판 최대합
✔ 문제 유형: 1,2차원 배열
✔ 문제 풀이 날짜: 2024.09.01
각 행, 열, 대각선의 합 중 가장 큰 합을 출력
- 각 행의 합과 각 열의 합을 구한다.
- Math.max를 사용하여 최대값을 갱신한다.
- 각 대각선의 합을 구한다
- 갱신된 최대값과 각 대각선의 합을 Math.max를 통해 비교하여 최대값을 갱신한다.
```javascript
let n = arr.length;
let row_sum = 0;
let col_sum = 0;
for (let j = 0; j < n; j++) {
row_sum += arr[i][j]; // i번째 행 합
col_sum += arr[j][i]; // i번째 열 합
}
answer = Math.max(answer, row_sum, col_sum);
}
let diag1_sum = 0; // 좌상단=>우하단 대각선
let diag2_sum = 0; // 우상단=>좌하단 대각선
diag1_sum += arr[i][i];
diag2_sum += arr[i][n - i - 1];
}
answer = Math.max(answer, diag1_sum, diag2_sum);
return answer;
}
let arr = [
[10, 13, 10, 12, 15],
[12, 39, 30, 23, 11],
[11, 25, …
```

[지원] 2-6. 격자판 최대합

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/07. 최대점수 구하기/정봉찬/index.js

✔ 문제 제목: 최대점수 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024-08-21
- 제한시간 안에 최대점수를 얻을 수 있도록 해야 한다.
- 재귀함수의 매개변수로 idx(인덱스), time(시간), sum(점수합)을 받는다.
- 문제를 풀 때와 풀지 않았을 때를 나눈다.
- time > m 일 때 함수를 종료한다.
- 모든 탐색이 종료되면(idx === ps.length) answer와 sum 중에서 큰 값을 answer에 할당한다.
```javascript
function solution(m, ps, pt) {
function DFS(idx, time, sum) {
if (time > m) {
return;
}
if (idx === ps.length) {
answer = Math.max(answer, sum);
return;
}
DFS(idx + 1, time + pt[idx], sum + ps[idx]);
DFS(idx + 1, time, sum);
}
DFS(0, 0, 0);
return answer;
}
let ps = [10, 25, 15, 6, 7];
let pt = [5, 12, 8, 3, 4];
console.log(solution(20, ps, pt)); // 41
```
- O(logn)
- 연속된 문제들의 풀이가 비슷해서 비교적 쉽게 해결했습니다.

[정봉찬] 8-7. 최대점수 구하기

---

02. 1, 2차원 배열 탐색/07. 봉우리/백지원/index.js

✔ 문제 제목: 봉우리
✔ 문제 유형: 1,2차원 배열
✔ 문제 풀이 날짜: 2024.09.03
상하좌우 비교했을 때 보다 숫자가 크면 봉우리로 취급되는데 그 때의 봉우리의 갯수를 구하기
- 테두리에 0을 추가해서 값을 비교할 때 범위를 벗어나지 않도록 함
- 상하좌우 값과 비교했을 때 해당 위치가 값이 더 크면 봉우리의 갯수(answer)을 1 추가
```javascript
let n = arr.length;
let dx = [-1, 1, 0, 0];
let dy = [0, 0, -1, 1];
let outlineArr = new Array(n + 2).fill(0).map(() => new Array(n + 2).fill(0));
for (let j = 0; j < n; j++) {
outlineArr[i + 1][j + 1] = arr[i][j];
}
}
// 봉우리 탐색
for (let i = 1; i <= n; i++) {
for (let j = 1; j <= n; j++) {
let isPeak = true; // 초기값을 봉우리로
// 상하좌우 탐색
for (let k = 0; k < 4; k++) {
let nx = i + dx[k];
let ny = j + dy[k];
if (outlineArr[nx][ny] >= outlineArr[i][j]) {
isPeak = false;
break;
}
}
if (isPeak) answer++;
}
}
return …
```

[지원] 2-7. 봉우리

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/김보경/index.js

✔ 문제 제목: 05-06. 학급 회장(해쉬)
✔ 문제 유형: 해쉬테이블
✔ 문제 풀이 날짜: 08.28
- key value 로 투표 결과를 count 하여 max값을 추출
1. if ... in 문을 사용하여 count 객체 생성
2. for ... in문을 사용한 배열 순회
```javascript
let answer;
let countResults = {};
[...s].forEach((el) => {
if (el in countResults) {
countResults[el]++;
} else {
countResults[el] = 1;
}
});
let maxValue = 0;
for (let key in countResults) {
if (countResults[key] > maxValue) {
maxValue = countResults[key];
answer = key;
}
}
return answer;
}
let str = "BACBACCACCBDEDE";
```
- 몰?루
- 테스트케이스가 없어서 예외케이스를 모르겠습니다...
```javascript
```
- for ... in문은 순서가 보장되지 않는다!
- Object[key] = value 를 기억하고 활용하자

[김보경] 05-06. 학급 회장(해쉬)

---

02. 1, 2차원 배열 탐색/07. 봉우리/백지원/index.js
03. 문자열 탐색/01. 회문문자열/백지원/index.js

✔ 문제 제목: 회문문자열
✔ 문제 풀이 날짜: 2024.09.03
회문 문자열인 경우 YES, 아닌 경우 NO 출력
- answer의 기본값을 YES로 둔다.
- 대소문자 구분을 하지 않기 위해 모두 소문자로 바꾼다.
- n과 n-i-1의 위치의 문자열을 비교한다.
- 하나라도 다르면 회문 문자열이 아니므로 NO를 출력하고 break를 통해 for문을 빠져나온다.
```javascript
let n = s.length;
s = s.toLowerCase();
for (let i = 0; i < Math.floor(n / 2); i++) {
if (s[i] !== s[n - i - 1]) {
answer = "NO";
break;
}
}
return answer;
}
let str = "goooG";
```
O(n)
- break 까먹지 않기

[지원] 3-1. 회문문자열

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/06. 바둑이 승차/윤아영/index.js

✔ 문제 제목: 바둑이 승차
✔ 문제 유형: 깊이 우선 탐색
✔ 문제 풀이 날짜: 24-08-27
- 트럭의 최대 적재량 : C
- 트럭에 태울 바둑이들 무게: W
- 태울 수 있는 가장 무거운 무게를 구하세요
- DFS를 활용하여 각 경우의 수의 합계를 구해 해당 합계가 최대 적재량보다 작다면 현재 answer과 비교하여 큰값으로 answer를 초기화 합니다.
```javascript
function solution(c, arr) {
const temp = (values, index) => {
const sum = values.reduce((acc, cur) => acc + cur, 0);
if (sum > c) {
return;
}
answer = Math.max(answer, sum);
for (let i = index; i < arr.length; i++) {
temp([...values, arr[i]], i + 1);
}
};
temp([], 0);
return answer;
}
let arr = [81, 58, 42, 33, 61];
console.log(solution(259, arr));
```

[윤아영] 8-6 바둑이 승차

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/06. 바둑이 승차/윤아영/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/07. 최대점수 구하기/윤아영/index.js

✔ 문제 제목: 최대점수 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-08-27
- 각 문제를 푸는데 걸리는 시간과 점수가 주어집니다.
- 제한 시간 M안에 N개의 문제 중 얻을 수 있는 최대 점수를 구한다.
- 해당 시간이 걸리면 푸는 걸로 간주한다.
- DFS 함수를 만들어 모든 조합을 비교합니다.
- 푸는 데 걸리는 시간이 M보다 커진다면 반복문에서 continue 해줍니다.
- 각 점수의 합과 answer를 비교하여 큰 값으로 재할당해줍니다.
```javascript
function solution(m, ps, pt) {
const DFS = (index, scores, times) => {
const timesSum = times.reduce((acc, cur) => acc + cur, 0);
if (timesSum > m) {
return true;
}
const scoresSum = scores.reduce((acc, cur) => acc + cur, 0);
answer = Math.max(answer, scoresSum);
for (let i = index; i < ps.length; i++) {
if (DFS(i + 1, [...scores, ps[i]], [...times, pt[i]])) {
continue;
}
}
};
DFS(0, [], []);
return answer;
}
let ps = [10, 25, 15, 6, 7];
let pt = [5, 12, 8, 3, 4]; …
```

[윤아영] 8-7 최대점수 구하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/07. 최대점수 구하기/이서인/index.js

✔ 문제 제목:최대점수 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.03
- 문제와 해당 문제 풀이 시간이 주어진다.
- 제한 시한 내 얻을 수 있는 최대 점수를 구해야 한다.
- 현재 고려 중인 index, 현재까지 걸린 시간, 현재까지 점수를 매개변수로 받는 DFS 함수를 정의한다.
- 현재까지 문제푸는 데 걸린 시간이 주어진 제한 시간보다 크면 함수를 종료한다.
- 기존 답과 현재까지 점수 중 최대 값을 답으로 재할당한다.
- 현재 고려 중인 index가 문제 배열 길이와 같으면 함수를 종료한다.
- 문제를 풀었을 때와 풀지 않았을 때를 고려해 최대 점수를 계산한다.
```javascript
function solution(m, ps, pt) {
function DFS(index, currentTime, currentScore) {
if (currentTime > m) return;
answer = Math.max(answer, currentScore)
if (index === pt.length) return;
DFS(index + 1, currentTime + pt[index], currentScore + ps[index])
DFS(index + 1, currentTime, currentScore)
}
DFS(0, 0, 0)
return answer;
}
```
O(2^n)
-
```javascript
function solution(m, ps, pt) {
let answer = …
```

[서인] 8-7. 최대점수 구하기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/김보경/index.js

✔ 문제 제목: 05-07 아나그램
✔ 문제 유형: 해쉬테이블
✔ 문제 풀이 날짜: 09.04
- 문자열 구성이 동일하면 yes출력
- 그런거 없이 일단 풀이
```javascript
let str1Count = {};
let str2Count = {};
if (str1.length !== str2.length) return "NO";
[...str1].forEach((el) => {
if (el in str1Count) {
str1Count[el]++;
} else {
str1Count[el] = 1;
}
});
[...str2].forEach((el) => {
if (el in str2Count) {
str2Count[el]++;
} else {
str2Count[el] = 1;
}
});
let str1Result = [];
let str2Result = [];
for (let key in str1Count) {
let count = key + str1Count[key];
str1Result.push(count);
}
for (let key in str2Count) {
let count = key + str2Count[key];
str2Result.push(count);
}
str1Result.sort().join("");
str2Result.sort().join("");
return str1Result.includes(str2Result) ? answer : "NO";
}
let a = "AbaAeCe"; …
```

[김보경] 05-07 아나그램

---

02. 1, 2차원 배열 탐색/04. 점수 계산/김민영/index.js

✔ 문제 제목: 2-4. 점수 계산
✔ 문제 유형:
✔ 문제 풀이 날짜: 2024.09.05
-
```javascript
let count = 0;
if (arr[i] === 1) {
answer += count + 1;
count++;
} else {
count = 0;
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 2-4. 점수 계산

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/08. 중복순열/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/09. 동전교환/이서인/index.js

✔ 문제 제목: 동전교환
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.05
- 최소의 동전으로 주어진 금액을 맞춰야 한다.
- 현재 금액과 동전 배열의 index를 매개변수로 설정한다.
- 현재 금액이 크면 함수를 종료하고, 현재 금액이 주어진 금액과 같으면 기존 동전 개수와 비교해 더 작은 수로 재할당한다.
- 동전 배열을 순회하며 현재 금액에 추가한다.
```javascript
let answer = Number.MAX_SAFE_INTEGER;
function DFS(currentSum, index) {
if (currentSum > m) return;
if (currentSum === m) {
answer = Math.min(answer, index);
return
}
DFS(currentSum + arr[i], index + 1);
}
}
DFS(0, 0)
return answer;
}
```
O(2^n)
- for문 안쓰려고 다르게 풀었는데 스택오버플로우가 발생했슴다.
```javascript
arr.sort((a, b) => b - a);
let money = m;
if (!money) break;
answer += Math.floor(money / arr[i]);
money %= arr[i];
}
return …
```

[서인] 8-9. 동전교환

---

02. 1, 2차원 배열 탐색/05. 등수구하기/김민영/index.js

✔ 문제 제목: 2-5. 등수구하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 2024.09.07
-
```javascript
let sortArr = [...arr].sort((a, b) => b - a);
answer.push(sortArr.indexOf(arr[i]) + 1);
}
return answer;
}
```
-
```javascript
let sortArr = [...arr].sort((a, b) => b - a);
return arr.map((num) => sortArr.indexOf(num) + 1)
}
```
-

[민영] 2-5. 등수구하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js

✔ 문제 제목: 순열 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.06
- 순열을 구해야한다.(중복 안됨)
- 중복 순열을 구하는 것과 같다. #202 
- 중복 순열 풀이에서 중복 조합만 조건문으로 걸러주면 된다.
```javascript
function DFS(index, part = "") {
if (part.length > 1 && part[0] === part[1]) return;
if (index === m) return part && answer.push(part);
arr.forEach(el => {
DFS(index + 1, part + el)
})
}
DFS(0, "")
return answer.join("\n") + "\n" + answer.length;
}
```
O(2^n)
-
```javascript
if (array.length === m) {
answer.push(array);
return;
}
for(let i = index; i < arr.length; i++) {
DFS(i + 1, [...array, arr[i]]);
}
}
DFS(0, []);
for (let i = 0; i < answer.length; i++) {
console.log(answer[i]);
}
return answer.length;
}
```
-분명히 전날 많이 …

[서인] 8-10. 순열 구하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js

✔ 문제 제목: 팩토리얼
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024.09.07
- 자연수 n의 팩토리얼을 구해야 한다.
- n이 1이 될 때까지 처음 n에 n-1을 재귀함수를 활용해 곱한다.
```javascript
if (n === 1) return 1;
return n * solution(n - 1)
}
```
- O(n)
-
```javascript
```
- 이전 DFS 문제보다 쉬운 느낌~ 다음 문제들은 어떨까요?

[서인] 8-11. 팩토리얼

---

02. 1, 2차원 배열 탐색/07. 봉우리/김민영/index.js

✔ 문제 제목: 2-7. 봉우리
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.10
-
```javascript
for (j = 0; j < arr[0].length; j++) {
let top = i > 0 ? arr[i - 1][j] : 0;
let bottom = i < arr.length - 1 ? arr[i + 1][j] : 0;
let left = j > 0 ? arr[i][j - 1] : 0;
let right = j < arr[0].length - 1 ? arr[i][j + 1] : 0;
if (arr[i][j] > Math.max(top, bottom, left, right)) {
answer++;
}
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 2-7. 봉우리

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/06. 바둑이 승차/윤아영/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/09. 동전교환/윤아영/index.js

✔ 문제 제목: 동전교환
✔ 문제 유형: 
✔ 문제 풀이 날짜: 24-08-28
- 거스름돈을 가장 적은의 동전으로 교환 해주려고 한다.
- 거슬러 줄 동전의 최소 개수를 출력한다.
- 동전의 단위를 내림차순으로 정렬
- for문을 돌면서 answer에는 각 동전의 나눈 값의 몫을 더하고 나머지는 money에 재할당한다.
- money가 0이 되면 break한다.
```javascript
arr.sort((a, b) => b - a);
let money = m;
if (!money) break;
answer += Math.floor(money / arr[i]);
money %= arr[i];
}
return answer;
}
let arr = [1, 2, 5];
console.log(solution(15, arr));
```
O(n)
- 
```javascript
```
- 가장 큰 금액부터 나누면 되지 않을까라는 생각을 for문으로 풀어봤습니다.
- 이후 중복 순열로 풀어봐야겠죠..?

[윤아영] 8-9 동전교환

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/윤아영/index.js

✔ 문제 제목: 뮤직비디오 
✔ 문제 유형: 이분검색
✔ 문제 풀이 날짜: 24-08-28
- m개의 DVD를 만들 때 필요한 최소 크기를 구하세요.
- count 함수를 정의합니다.
- 해당 크기로 dvd를 만들다면 몇 개의 dvd를 만들 수 있는지 세어줍니다.
- 이분 검색을 하면서 count가 정해진 개수보다 적다면 크기를 줄이고 크다면 늘립니다.
```javascript
const count = (songs, length) => {
let tracks = 1;
let lengthOfSongs = 0;
for (let i = 0; i < songs.length; i++) {
lengthOfSongs += songs[i];
if (lengthOfSongs > length) {
tracks++;
lengthOfSongs = songs[i];
}
}
return tracks;
};
let answer = Number.MAX_SAFE_INTEGER;
let left = Math.max(...songs);
let right = songs.reduce((acc, cur) => acc + cur, 0);
const middle = Math.floor((left + right) / 2);
if (count(songs, middle) > m) {
left = middle + 1;
continue;
}
right = middle - 1;
answer = Math.min(answer, middle);
}
return …
```

[윤아영] 7-11 뮤직비디오 (복습풀이)

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/06. 바둑이 승차/윤아영/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/윤아영/index.js

✔ 문제 제목: 순열 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 23-09-02
- 10개이하의 N개의 자연수가 주어지고 이 중 M개를 뽑아 나열하는 방법을 모두 출력하세요
- 순열을 구하세요 (중복 없이 순서에 상관 있게)
- DFS 함수를 재귀적으로 실행합니다.
- 경우의 수를 가지는 배열과 뽑히고 남은 배열을 넘겨주어 순열을 계산합니다.
- 배열의 수가 M이 되면 해당 경우의 수를 answer에 추가합니다.
```javascript
const DFS = (array, restArray) => {
if (array.length === m) {
answer.push(array);
return;
}
for (let i = 0; i < restArray.length; i++) {
DFS([...array, restArray[i]], [...restArray.slice(0, i), ...restArray.slice(i + 1)]);
}
};
DFS([], arr);
for (let i = 0; i < answer.length; i++) {
console.log(answer[i]);
}
return answer.length;
}
let arr = [3, 6, 9];
console.log(solution(2, arr));
```
?
- 순열이 아닌 조합을 구했다.
```javascript …
```

[윤아영] 8-10 순열 구하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/윤아영/index.js

✔ 문제 제목: 팩토리얼
✔ 문제 유형: 재귀
✔ 문제 풀이 날짜: 24-09-04
- 팩토리얼을 구하세요
- n! = n * (n - 1) * (n - 2) * ... * 2 * 1
- n이 1이 될 때까지 재귀적으로 함수를 호출합니다.
```javascript
if (n === 1) return 1;
return n * solution(n - 1);
}
console.log(solution(5));
```
O(n)
- 예전에는 팩토리얼 푸는 거 어려웠었는데 외운 듯 습득한 듯 풀 수 있어서 그래도 성장했구나 싶습니다.

[윤아영] 8-11 팩토리얼

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/12. 조합수(메모이제이션)/윤아영/index.js

✔ 문제 제목: 조합수(메모이제이션)
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-09-06
- 다음 공식을 사용하여 조합수를 구해주는 프로그램을 작성하세요
- ![image](https://github.com/user-attachments/assets/1b9679b7-da66-49f6-924a-2db229b2aee9)
- 이미 해당 위치에 값이 있다면 그 값을 반환하고
- n === r이 같거나 r === 0 인 경우 조합수는 하나밖에 없다.
```javascript
function solution(n, r) {
let dy = Array.from({length: 35}, () => new Array(35).fill(0));
const DFS=(n, r) => {
if (dy[n][r] > 0) return dy[n][r];
if (n === r || r ===0) return 1;
return dy[n][r] = DFS(n - 1, r - 1) + DFS(n - 1, r)
}
return DFS(n, r);
}
console.log(solution(5, 3));
console.log(solution(33, 19));
```
?
- 공식을 줘도 풀지를 못하네요,, ㅎㅎ
- 분명 매일 하나씩 풀자고 했다던 나는 어디있나요

[윤아영] 8-12 조합수 (복습예정)

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/윤아영/index.js

✔ 문제 제목: 조합 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-09-06
- 조합 구하기
- 재귀적으로 실행합니다.
```javascript
function solution(n, m) {
if (array.length === m) {
answer.push(array);
return;
}
for (let i = index; i <= n; i++) {
DFS(i + 1, [...array, i]);
}
};
DFS(1, []);
return answer;
}
console.log(solution(4, 2));
```
- 화이팅!

[윤아영] 8-14 조합 구하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/15. 수들의 조합/윤아영/index.js

✔ 문제 제목: 수들의 조합
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-09-06
- 조합의 합이 임의의 정수 m의 배수인 개수는 몇 개인지 출력한다.
- 재귀적으로 호출하면서 조합배열의 길이가 k개인 경우 합계를 구하고 m의 배수라면 answer에 1을 더한다.
```javascript
function solution(n, k, arr, m) {
if (array.length === k) {
answer = array.reduce((acc, cur) => acc + cur, 0) % m === 0 ? answer + 1 : answer;
return;
}
for (let i = index; i < arr.length; i++) {
DFS(i + 1, [...array, arr[i]]);
}
};
DFS(0, []);
return answer;
}
let arr = [2, 4, 5, 8, 12];
console.log(solution(5, 3, arr, 6));
```
?
- 밀린 문제를 풀었습니다!!

[윤아영] 8-15 수들의 조합

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/김보경/index.js

✔ 문제 제목: 연속부분수열1
✔ 문제 유형: 투포인터
✔ 문제 풀이 날짜: 09.11
- 배열의 연속 수열의 합이 m이되는 경우의 수 출력
- rt, lt와 sum stack을 사용한 투포인터 순회
```javascript
const solution2 = (m, arr) => {
let lt = 0;
let rt = 0;
let sum = 0;
while (rt < arr.length) {
if (sum < m) {
sum += arr[rt++];
} else if (sum === m) {
answer++;
sum -= arr[lt++];
} else {
sum -= arr[lt++];
}
}
return answer;
};
```
- 아래 처음 풀었던 이중 for문에서 투포터인터로 다시 풀이를 진행해봤습니다.
```javascript
let sumStack = arr[i];
for (let j = i + 1; j < arr.length; j++) {
if (sumStack < m) {
sumStack = sumStack + arr[j];
} else if (sumStack === m) {
answer++;
break;
} else {
break;
}
}
}
return answer;
}
```
- 다중 for문과 투포인터 사용에서 오는 시간복잡도 차이 인식

[김보경] 05-03 연속부분수열1

---

03. 문자열 탐색/01. 회문문자열/김민영/index.js

✔ 문제 제목: 3-1. 회문문자열
✔ 문제 유형: 
✔ 문제 풀이 날짜: 24.09.12
-
```javascript
return s.toLowerCase() === s.toLowerCase().split('').reverse().join('') ? 'YES' : 'NO';
}
```
-
```javascript
```
-

[민영] 3-1. 회문문자열

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/김보경/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/김보경/index.js
06. 자료구조(스택, 큐)/01. 올바른 괄호/김보경/index.js
06. 자료구조(스택, 큐)/02. 괄호문자제거/김보경/index.js

✔ 문제 제목: 05-08 모든 아나그램
✔ 문제 유형: 투포인터 & 슬라이딩 윈도우 & 해쉬
✔ 문제 풀이 날짜: 09.12
- 투포인터 & 슬라이딩 윈도우 & 해쉬를 사용한 콤비네이션
- 개인적으로 너무 힘들었읍니다.
- 투포인터 & 슬라이딩 윈도우 & 해쉬를 사용한 알잘딱 풀이
- 사실  풀이를 봐도 이해하기 힘들어서 겨우겨우 풀었습니다.
```javascript
let sH = new Map();
let tH = new Map();
[...t].forEach((el) => {
sH.set(el, (tH.get(el) || 0) - 1);
});
console.log(sH);
let len = t.length - 1;
for (let rt = 0; rt < len; rt++) {
sH.set(s[rt], (sH.get(s[rt]) || 0) + 1);
if (sH.get(s[rt]) === 0) {
sH.delete(s[rt]);
}
}
let lt = 0;
for (let rt = len; rt < s.length; rt++) {
sH.set(s[rt], (sH.get[rt] || 0) + 1);
if (sH.get(s[rt]) === 0) sH.delete(s[rt]);
if (sH.size === 0) answer++;
sH.set(s[lt], (sH.get(s[lt]) || 0) - 1);
if (sH.get(s[lt]) === 0) sH.delete(s[lt]);
lt++;
}
}
let a = "bacaAacba"; …
```

[김보경] 05-08 모든 아나그램

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/12. 조합수(메모이제이션)/이서인/index.js

✔ 문제 제목: 조합수
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024.09.08
- 조합 공식을 쓰지 않고 조합수를 구한다.
- n은 전체 항목, r은 선택할 항목입니다.
- r === 0, r === n일 때 조합의 수는 1입니다.
- 현재 항목을 선택하는 경우와 현재 항목을 선택하지 않는 경우의 조합수를 계산합니다.
- 현재 항목을 선택하면 남은 항목 중에서 r - 1개를 선택해야 합니다.
- 현재 항목을 선택하지 않으면 남은 항목 중에서 r개를 선택해야 합니다.
- 모든 경우의 수를 더해 답을 구합니다.
- 해당 함수를 호출해 조합수를 계산합니다.
```javascript
function solution(n, r) {
if (r === 0 || n === r) return 1;
return solution(n - 1, r -1) + solution(n - 1, r)
}
```
O(2^n)
-
```javascript
function solution(n, r) {
let dy = Array.from({length: 35}, () => new Array(35).fill(0));
const DFS=(n, r) => {
if (dy[n][r] > 0) return dy[n][r];
if (n === r || r ===0) return 1;
return dy[n][r] = DFS(n - 1, r - 1) + DFS(n - 1, r)
}
return DFS(n, r);
}
console.log(solution(5, 3));
console.log(solution(33, 19));
```
- 어렵지만 …

[서인] 8-12. 조합수(메모이제이션)

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/정봉찬/index.js

✔ 문제 제목: 수열 추측하기
✔ 문제 유형: 재귀
✔ 문제 풀이 날짜: 2024-09-05
- 가장 윗줄에 1부터 N까지의 숫자가 한 개씩 적혀 있다.
- 둘째 줄부터 차례대로 파스칼의 삼각형처럼 위의 두개를 더한 값이 저장되게 된다.
- N과 가장 밑에 있는 숫자가 주어져 있을 때 가장 윗줄에 있는 숫자를 구하라.
- 답이 여러가지가 나오는 경우에는 사전순으로 가장 앞에 오는 것을 출력.
- N(1<=N<=10), F(F<=1,000,000)
- 복습예정
```javascript
function solution(n, f) {
let answer;
const dy = Array.from({ length: n + 1 }, () =>
Array.from({ length: n + 1 }, () => 0)
);
const ch = Array.from({ length: n + 1 }, () => 0);
const p = Array.from({ length: n }, () => 0);
const b = Array.from({ length: n }, () => 0);
let isFinished = 0;
function combination(_n, _r) {
if (dy[_n][_r] > 0) {
return dy[_n][_r];
}
if (_r === 0 || _n === _r) {
return 1;
}
return (dy[_n][_r] = combination(_n - 1, _r - 1) + combination(_n - 1, _r));
}
b[i] = …
```

[정봉찬] 8-13. 수열 추측하기(복습예정)

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/02. 경로탐색(DFS)/정봉찬/index.js

✔ 문제 제목: 경로탐색(DFS)
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024-09-07
- 방향그래프가 주어지면 1번 정점에서 N번 정점으로 가는 모든 경로의 가지 수를 출력하는 프로그램을 작성하세요.
- 정점의 수 N(1<=N<=20), 간선의 수 M
- 인접행렬 그래프를 정점 + 1 만큼의 크기로 이중배열을 만든다. 이중배열의 값은 0으로 초기화한다.
- 방문한 노드를 저장할 ch 배열을 선언하고 0으로 초기화한다.
- arr을 반복문 돌면서 그래프의 값을 1로 할당한다.
- 재귀 함수로 출발 노드와, 도착 노드를 받는다.
- 도착 노드가 n에 도달하면 answer를 1 더하고 함수를 종료한다.
- 1부터 n만큼의 반복문을 돌면서 현재 출발 노드가 갈 수 없는 요소의 경우 continue한다.
- 이미 방문한 요소의 경우에도 continue한다.
- 그 외에는 방문 처리하고 DFS(출발 노드 + 1, 도착 노드)로 재귀 탐색한다.
- 재귀 탐색이 끝나면 방문 처리를 0으로 변경한다.
```javascript
const graph = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(0));
const ch = Array.from({ length: n + 1 }, () => 0);
for (const [start, end] of arr) {
graph[start][end] = 1;
}
function DFS(L, end) {
if (end === n) { …
```

[정봉찬] 9-2. 경로탐색(DFS)

---

03. 문자열 탐색/02. 유효한 팰린드롬/김민영/index.js

✔ 문제 제목: 3-2. 유효한 팰린드롬
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.14
-
```javascript
const cleanedString = s
.replace(/[\{\}\[\]\/?.,;:|\)*~`!^\-_+<>@\#$%&\\\=\(\'\"]/g, '')
.replace(/[0-9]/g, '')
.replace(/\s+/g, '')
.toLowerCase();
return cleanedString === cleanedString.split('').reverse().join('') ? 'YES' : 'NO';
}
```
- 정규식이 너무 어려워서 봉찬님 풀이보고 수정했슴당
```javascript
const cleanedString = s
.toLowerCase()
.replace(/[^a-z]/g, '')
return cleanedString === [...cleanedString].reverse().join('') ? 'YES' : 'NO';
}
```
- 이걸 못 봐서 한참 해맸어요 😔
- 📝 : 문제 대충 읽는 습관 고치기 ,,

[민영] 3-2. 유효한 팰린드롬

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/이서인/index.js

✔ 문제 제목: 수열 추측하기
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 2024.09.09
- 가장 윗줄에 1부터 N까지 숫자가 적혀있다.
- 둘째 줄부터 차례대로 파스칼의 삼각형처럼 위의 두 숫자를 더한 값이 저장된다.
- N과 가장 밑의 숫자가 주어져 있을 때 가장 윗줄에 있는 숫자를 구하는 프로그램을 작성해야 한다.
- 단, 여러 답이 나오면 사전 순으로 가장 앞에 오는 것을 출력해야 한다.
- answer, flag(해를 찾았는지 여부 표시), dy(조합 수를 저장할 배열), ch(숫자의 사용 여부를 기록하는 배열), p(현재 조합을 저장하는 배열), b(조합 계수를 저장하는 배열)을 변수로 선언한다.
- 조합 수를 계산하고, 결과를 dy 배열에 저장한다.
- DFS는 L(현재 깊이)가 n(맨 윗 숫자의 개수)에 도달하고, sum(합)이 f(맨 밑 숫자)와 같으면 현재 조합을 answer에 저장한다.
- 가능한 숫자를 선택하고, 선택한 숫자에 재귀적으로 DFS를 호출한다.
- 조합 계수를 미리 계산해 b배열에 저장한다.
- DFS를 호출한다.
```javascript
function solution(n, f) {
let answer = null;
let flag = false;
let dy = Array.from(Array(n + 1), () => Array(n + 1).fill(0));
let ch = Array(n + 1).fill(0);
let p = Array(n);
let b = Array(n);
function combi(n, r) {
if (dy[n][r] > 0) return …
```

[서인] 8-13. 수열 추측하기

---

03. 문자열 탐색/03. 숫자만 추출/김민영/index.js

✔ 문제 제목: 3-3. 숫자만 추출
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.16
-
```javascript
return +(str.replaceAll(/[^0-9]/g, ''));
}
```
- 숫자 정규식 더 간략하게 수정
```javascript
return +(str.replaceAll(/\D/g, ''));
}
```
-

[민영] 3-3. 숫자만 추출

---

03. 문자열 탐색/02. 유효한 팰린드롬/백지원/index.js

✔ 문제 풀이 날짜: 2024.09.14
앞으로 읽어도 거꾸로 읽어도 똑같으면 YES, 똑같지 않으면 NO 출력,
단 알파벳 이외의 문자는 무시
- 알파벳을 모두 소문자로 바꾸고 정규식 표현으로 알파벳 이외의 문자는 무시
- 처음과 끝을 차례로 비교하며 다를 경우 바로 NO 출력
- 모두 같을 경우 YES 출력
```javascript
// 알파벳 이외의 문자는 무시
s = s.toLowerCase().replace(/[^a-z]/g, "");
let n = s.length;
for (let i = 0; i < n / 2; i++) {
if (s[i] !== s[n - i - 1]) answer = "NO";
break;
}
return answer;
}
let str = "found7, time: study; Yduts; emit, 7Dnuof";
```
O(n)
-  정규식도 기본적인거는 외워두는게 좋을듯

[지원] 3-2. 유효한 팰린드롬

---

03. 문자열 탐색/02. 유효한 팰린드롬/백지원/index.js
03. 문자열 탐색/03. 숫자만 추출/백지원/index.js

✔ 문제 풀이 날짜: 2024.09.14
문자열에서 숫자만 추출하고 제일 처음이 0인 경우 0 삭제
- 공백이 아닌 것을 추출하고 isNaN 함수를 사용하여 숫자만 추출
- 10진수로 변환해서 제일 앞에 있는 0 제거
```javascript
for (let s of str) {
if (!isNaN(s) && s != " ") answer += s;
}
return parseInt(answer, 10);
}
let str = "g0en2T0s8eSoft";
```
O(n)
- for of 문도 자주 써보아야겠다

[지원] 3-3. 숫자만 추출

---

03. 문자열 탐색/04. 가장 짧은 문자거리/김민영/index.js

✔ 문제 제목: 3-4. 가장 짧은 문자거리
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.18
-
```javascript
let p = 100;
for (i = 0; i < s.length; i++) {
if (s[i] === t) {
p = 0;
} else {
p++;
}
answer[i] = p;
}
p = 100;
for (i = s.length - 1; i >= 0; i--) {
if (s[i] === t) {
p = 0;
} else {
p++;
}
answer[i] = Math.min(answer[i], p);
}
return answer;
}
```
-
```javascript
```
- 풀이 참고헤서 풀었습니다.

[민영] 3-4. 가장 짧은 문자거리

---

03. 문자열 탐색/05. 문자열 압축/김민영/index.js

✔ 문제 제목: 3-5. 문자열 압축
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.20
-
```javascript
let cnt = 1;
for (i = 0; i < s.length; i++) {
if (s[i] === s[i - 1]) {
cnt++;
} else {
if (cnt > 1) {
answer += cnt;
}
answer += s[i];
cnt = 1;
}
}
return answer;
}
```
- 마지막 숫자가 누락되는 문제 해결
```javascript
let cnt = 1;
for (i = 1; i <= s.length; i++) {
if (s[i] === s[i - 1]) {
cnt++;
} else {
answer += s[i - 1];
if (cnt > 1) {
answer += cnt;
}
cnt = 1;
}
}
return answer;
}
```
-

[민영] 3-5. 문자열 압축

---

04. 완전탐색(블루투포스)/01. 자리수의 합/김민영/index.js

✔ 문제 제목: 4-1. 자리수의 합
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.22
-
```javascript
let maxSum = 0;
let maxNum = 0;
for (num of arr) {
let digitSum = String(num).split('').reduce((sum, digit) => sum + Number(digit), 0);
if (digitSum > maxSum || (digitSum === maxSum && num > maxNum)) {
maxSum = digitSum;
maxNum = num;
}
}
return maxNum;
}
```
-
```javascript
```
- 풀이 참고해서 풀었습니다.

[민영] 4-1. 자리수의 합

---

04. 완전탐색(블루투포스)/02. 뒤집은 소수/김민영/index.js

✔ 문제 제목: 4-2. 뒤집은 소수
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.24
-
```javascript
for (num of arr) {
let x = +(String(num).split('').reverse().join(''))
let isPrime = true;
if (x === 1) {
isPrime = false;
}
for (i = 2; i <= Math.sqrt(x); i++) {
if (x % i === 0) {
isPrime = false;
}
}
if (isPrime) {
answer.push(x);
}
}
return answer;
}
```
-
```javascript
for (num of arr) {
let x = +(String(num).split('').reverse().join(''))
let isPrime = true;
if (x === 1) {
continue;
}
for (i = 2; i <= Math.sqrt(x); i++) {
if (x % i === 0) {
isPrime = false;
break;
}
}
if (isPrime) {
answer.push(x);
}
}
return answer;
}
```
- `let isPrime = true;` 부분 풀이 참고했습니다.
---
- `continue`:  현재 반복의 나머지 코드를 건너뛰고, 다음 반복을 계속 실행
- `break`: 반복문을 완전히 …

[민영] 4-2. 뒤집은 소수

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/이서인/index.js

✔ 문제 제목: 조합 구하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.09
- 조합들과 조합 수를 출력한다.
- 길이가 m인 부분집합을 elements 배열에 push한다.
- 요소가 n보다 크면 함수를 종료한다.
- 요소를 부분집합에 포함하거나 포함하지 않는 경우의 수를 모두 탐색한다.
```javascript
function solution(n, m) {
let elements = []
function DFS(el, part = "") {
if (part.length === m) {
elements.push(part);
return;
}
if (el > n) return;
DFS(el + 1, part + el)
DFS(el + 1, part);
}
DFS(1);
return [...elements, elements.length].join("\n")
}
```
O(2^n)
-
```javascript
function solution(n, m) {
if (array.length === m) {
answer.push(array);
return;
}
for (let i = index; i <= n; i++) {
DFS(i + 1, [...array, i]);
}
};
DFS(1, []);
return answer;
}
console.log(solution(4, 2));
```
- 앞에 풀었던 조합수 구하기와 부분집합 구하기 풀이를 참고해서 풀려고 했는데 부분집합 구하기만 사용해도 됐어요...ㅎ 오히려 …

[서인] 8-14. 조합 구하기

---

04. 완전탐색(블루투포스)/03. 멘토링/김민영/index.js

✔ 문제 제목: 4-3. 멘토링
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.26
-
```javascript
function solution(test) {
const N = test[0].length; // 학생 수 (테스트 결과의 길이)
// 모든 학생 쌍을 고려
for (let mentor = 1; mentor <= N; mentor++) {
for (let mentee = 1; mentee <= N; mentee++) {
if (mentor === mentee) continue; // 멘토와 멘티가 같으면 건너뛰기
let isValid = true;
// M개의 테스트 결과를 확인
for (let i = 0; i < test.length; i++) {
const mentorRank = test[i].indexOf(mentor) + 1; // 1-based index
const menteeRank = test[i].indexOf(mentee) + 1; // 1-based index
if (mentorRank >= menteeRank) {
isValid = false;
break; // 조건을 만족하지 않으면 중단
}
}
if (isValid) answer++; // 조건을 만족하는 경우 카운트
}
}
return answer;
}
```
-
```javascript
```
- 풀이 참고해서 풀었습니다.

[민영] 4-3. 멘토링

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/15. 수들의 조합/이서인/index.js

✔ 문제 제목: 수들의 조합
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.09
- n개의 정수 중 k개를 뽑는 조합의 합이 m의 배수인 조합의 개수를 구한다.
- 배열 요소 개수가 k일 때 parts에 push한다.
- index가 n이상이면 함수를 종료한다.
- part에 배열 요소를 추가하거나 추가하지 않는 경우의 수를 모두 탐색한다.
- parts 요소(부분집합)의 합이 m으로 나눠 떨어지는 요소만 filter한다.
```javascript
function solution(n, k, arr, m) {
let parts = [];
function DFS(index, part = [], count = 0) {
if (count === k) {
parts.push(part.slice());
return;
}
if (index >= n) return;
DFS(index + 1, part.concat(arr[index]), count + 1);
DFS(index + 1, part, count);
}
DFS(0,[])
return parts.filter(el => el.reduce((a, b) => a + b, 0) % m === 0).length
}
```
O(2^n)
-
```javascript
function solution(n, k, arr, m) {
function DFS(L, idx, sum) {
if (L === k) {
if (sum % m === 0) {
answer++;
}
return;
}
for (let i = idx; i < n; i++) { …
```

[서인] 8-15. 수들의 조합

---

04. 완전탐색(블루투포스)/04. 졸업선물/김민영/index.js

✔ 문제 제목: 4-4. 졸업선물
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.28
-
```javascript
let sortProduct = [...product].sort((a, b) => (a[0] + a[1]) - (b[0] + b[1]));
for (i = 0; i < sortProduct.length; i++) {
let cnt = 1;
let money = m - sortProduct[i][1] - sortProduct[i][0] / 2;
for (j = 0; j < sortProduct.length; j++) {
if (i === j) {
continue;
}
money = money - sortProduct[j][0] - sortProduct[j][1];
if (money < 0) {
break;
} else {
cnt += 1;
}
}
answer = Math.max(answer, cnt);
}
return answer;
}
```
- else 문 수정
```javascript
let sortProduct = [...product].sort((a, b) => (a[0] + a[1]) - (b[0] + b[1]));
for (i = 0; i < sortProduct.length; i++) {
let cnt = 1;
let money = m - sortProduct[i][1] - sortProduct[i][0] / 2; …
```

[민영] 4-4. 졸업선물

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/15. 수들의 조합/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/02. 경로탐색(DFS)/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/03. 경로탐색(인접리스트)/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/04. 미로탐색/이서인/index.js

✔ 문제 제목: 미로탐색
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.11
- 7*7 격자판 미로를 탈출하는 경로의 가지 수를 출력한다.
- 출발점은 격자의 (1, 1) 좌표이고, 도착점은 (7, 7)좌표이다.
- 격자판의 1은 벽이고, 0은 통로(간선)이다.
- 방문 여부를 표시하는 2차원 배열을 만든다.
- DFS 함수
- x, y가 도착점(n-1, n-1)에 도달하면 answer에 1을 더한다.
- 현재 요소의 방문 여부를 true로 재할당한다.
- 상하좌우 방향 변수를 선언한다.
- directions를 순회하며 현재 요소의 행과 열에 방향 백터를 방향 배열을 사용해 조건에 맞는 nx, ny를 구한다.
- 조건은 nx, ny는 board.length보다 작아야 하고, 0이상이어야 한다. / 방문하지 않았어야 하며, 통로(0)이어야 한다.
- 해당 순회 이후 방문 여부를 false로 재할당 한다.
- 초기값을 0으로 정한다.
```javascript
function solution(board) {
const n = board.length;
const visited = Array.from({ length: n }, () => Array(n).fill(false));
function DFS(x, y) {
if (x === n - 1 && y === n - 1) {
answer++;
return;
}
visited[x][y] = true;
const directions = [
[-1, 0],
[1, 0],
[0, -1],
[0, 1]
];
for (const …
```

[서인] 9-4. 미로탐색

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/10. 순열 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/11. 팩토리얼/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/15. 수들의 조합/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/02. 경로탐색(DFS)/이서인/index.js

✔ 문제 제목: 경로탐색(DFS)
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 2024.09.10
- 방향그래프에서 1부터 n 정점까지 가는 모든 경로의 수를 구한다.
- 0으로 초기화된 인접 행렬(그래프)을 만든다. (1부터 시작이므로 n+1 사용)
- 방문 여부를 표시하는 visited 변수를 선언한다.(무한 루프 방지)
- arr의 시작 노드(s), 끝 노드(e)를 순회하며 간선 여부를 표시한다.
- DFS 함수
- DFS 매개변수가 n 정점과 같을 때 answer에 1을 추가하고 함수를 종료한다.
- for문을 순회하면서 간선이 있고, 방문하지 않은 요소를 방문했다고 재할당 한 뒤 DFS를 재귀 호출해 해당 노드를 계속(n이 될 때까지) 탐색한다.
- 이를 완료하고 방문한 요소를 방문하지 않았다고 재할당한다.(다른 경로를 탐색하기 위한 백트래킹)
```javascript
const graph = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(0));
const visited = new Array(n + 1).fill(false);
for (const [s, e] of arr) {
graph[s][e] = 1;
}
function DFS(v) {
if (v === n) {
answer++;
return;
}
for (let i = 1; i <= n; i++) {
if (graph[v][i] === 1 && !visited[i]) {
visited[i] = true; …
```

[서인] 9-2. 경로탐색(DFS)

---

04. 완전탐색(블루투포스)/05. K번째 큰 수/김민영/index.js

✔ 문제 제목: 4-5. K번째 큰 수
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.09.30
-
```javascript
let answer;
let arr = new Set;
for (i = 0; i < n; i++) {
for (j = i + 1; j < n; j++) {
for (x = j + 1; x < n; x++) {
arr.add(card[i] + card[j] + card[x]);
}
}
}
answer = Array.from(arr).sort((a, b) => b - a);
return answer[k - 1];
}
```
-
```javascript
```
- 풀이봤습니다 ㅠㅠ 섹션 4는 다 다시 풀어봐야할 거 같아요 🤦🏻‍♀️

[민영] 4-5. K번째 큰 수

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/14. 조합 구하기/이서인/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/15. 수들의 조합/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/02. 경로탐색(DFS)/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/03. 경로탐색(인접리스트)/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/04. 미로탐색/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/05. 이진트리 넓이우선탐색(BFS)/이서인/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/06. 송아지 찾기(BFS)/이서인/index.js

✔ 문제 제목: 송아지 찾기(BFS)
✔ 문제 유형: BFS
✔ 문제 풀이 날짜: 2024.09.17
- 현수는 한 번의 점프로 앞으로 1, 뒤로 1, 앞으로 5를 이동할 수 있다.
- 최소 몇 번의 점프로 현수가 송아지의 위치까지 갈 수 있는지 구하는 프로그램을 작성한다.
- 점프 방향 배열을 선언한다.
- 방문 여부를 담을 배열을 만든다.
- 큐 배열을 생성한다.
- 큐에 초기값[현수의 위치, 0(점프 수)]을 push하고, 초기 현수 위치의 방문을 재할당한다.
- 큐에서 현재 위치와 점프 수를 꺼낸다.
- 현재 위치가 송아지 위치와 같으면 점프 수를 반환한다.
- 점프 방향 배열을 순회하면서 현재 위치와 방향을 더한 값을 다음 위치로 선언한다.
- 다음 위치가 좌표 위에 있고, 방문하지 않았었다면 방문 표시를 하고 queue에 점프 수와 함께 push한다.
```javascript
function solution(s, e) {
const directions = [1, -1, 5];
const visited = new Array(10001).fill(false);
const queue = [];
queue.push([s, 0]);
visited[s] = true;
while (queue.length) {
const [current, jumps] = queue.shift();
if (current === e) return jumps;
for (let direction of directions) {
const next = current + direction;
if (next >= 0 && next <= …
```

[서인] 9-6. 송아지 찾기(BFS)

---

03. 문자열 탐색/04. 가장 짧은 문자거리/백지원/index.js

✔ 문제 제목: 가장 짧은 문자거리
✔ 문제 풀이 날짜: 2024.10.04
문자열 s와 문자 t가 주어지는데 그 때 문자열 s의 각 문자가 문자 t와 떨어진 거리를 순서대로 출력
- 첫번째 문자부터 마지막 문자까지 t와 떨어진 거리 계산
- 마지막 문자부터 첫번째 문자까지 t와 떨어진 거리 계산
- 둘 중 더 작은 숫자를 각각 출력
```javascript
let n = s.length;
let p = 0;
if (s[i] === t) p = 0;
else p++;
answer.push(p);
}
for (let i = n - 1; i >= 0; i--) {
if (s[i] === t) p = 0;
else p++;
answer[i] = Math.min(answer[i], p);
}
return answer.join(" ");
}
let str = "teachermode";
console.log(solution(str, "e"));
```
O(n)

[지원] 3-4. 가장 짧은 문자거리

---

03. 문자열 탐색/04. 가장 짧은 문자거리/백지원/index.js
03. 문자열 탐색/05. 문자열 압축/백지원/index.js

✔ 문제 제목: 문자열 압축
✔ 문제 풀이 날짜: 2024.10.04
문자열의 문자가 연속적으로 반복되면 반복되는 문자+반복횟수 표기, 반복횟수가 1이면 반복되는 문자만 표기
- 다음 문자와 해당 문자를 비교하여 같으면 cnt++
- 같지 않은 경우에 cnt가 1보다 큰 경우만 문자와 반복횟수 출력
- cnt가 1이면 문자만 출력
```javascript
let cnt = 1;
if (s[i] === s[i + 1]) {
cnt++;
} else {
answer += s[i];
if (cnt > 1) answer += cnt;
cnt = 1;
}
}
return answer;
}
let str = "KKHSSSSSSSE";
```
O(n)

[지원] 3-5. 문자열 압축

---

03. 문자열 탐색/05. 문자열 압축/백지원/index.js
04. 완전탐색(블루투포스)/01. 자리수의 합/백지원/index.js

✔ 문제 제목: 자리수의 합
✔ 문제 유형: 완전탐색(블루트포스)
✔ 문제 풀이 날짜: 2024.10.04
각 자리수의 합이 더 큰 숫자 구하되, 합이 같은 경우 더 큰 수 출력
- reduce 함수를 통해 각 자리수의 합을 구하는 digitSum 함수 생성
- digitSum을 통해 arr의 모든 숫자에 대한 각 자리수의 합을 구하고 그 합이 maxSum보다 더 큰 경우 maxSum을 sum으로 갱신
- 또는 sum이 maxSum과 같은 경우 answer보다 진행중인 숫자가 더 큰 경우 answer을 진행중인 숫자로 갱신
```javascript
function digitSum(num) {
return num
.toString()
.split("")
.reduce((acc, curr) => acc + parseInt(curr), 0);
}
let maxSum = 0;
let sum = digitSum(arr[i]);
if (sum > maxSum || (sum === maxSum && arr[i] > answer)) {
maxSum = sum;
answer = arr[i];
}
}
return answer;
}
let arr = [128, 460, 603, 40, 521, 137, 123];
console.log(solution(7, arr));
```
O(n)
- reduce 함수 응용 어렵다 ㅜ.ㅜ 공부하기

[지원] 4-1. 자리수의 합

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/김민영/index.js

✔ 문제 제목: 5-1. 두 배열 합치기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.04
-
```javascript
return [...arr1, ...arr2].sort((a, b) => a - b);
}
```
-
```javascript
```
-

[민영] 5-1. 두 배열 합치기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/김민영/index.js

✔ 문제 제목: 5-2. 공통원소구하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.06
-
```javascript
let n = arr1.length;
let m = arr2.length;
let p1 = 0;
let p2 = 0;
arr1.sort((a, b) => a - b);
arr2.sort((a, b) => a - b);
while (p1 < n && p2 < m) {
if (arr1[p1] !== arr2[p2]) {
arr1[p1] < arr2[p2] ? p1++ : p2++;
} else {
answer.push(arr1[p1]);
p1++;
p2++;
}
}
return answer;
}
```
-
```javascript
```
- 투포인터 알고리즘이 뭔지 몰라서 `5-1. 두 배열 합치기` 풀이 참고하고 풀었는데 이렇게 푸는 거 맞나요 ,,?

[민영] 5-2. 공통원소구하기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/김민영/index.js

✔ 문제 제목: 5-3. 연속부분수열1
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.08
-
```javascript
let sum = 0;
let lt = 0;
for (let rt = 0; rt < arr.length; rt++) {
sum += arr[rt];
while (sum > m) {
sum -= arr[lt];
lt++;
}
if (sum === m) {
answer++;
}
}
return answer;
}
```
-
```javascript
```
- 풀이 참고했습니다 ㅠㅠ

[민영] 5-3. 연속부분수열1

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/김민영/index.js

✔ 문제 제목: 5-4. 연속부분수열2
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.10
-
```javascript
// [...arr].map(num => num <= m && answer++);
let lP = 0;
let sum = 0;
sum += arr[i];
while (sum > m) {
sum -= arr[lP];
lP++;
}
// answer++;
answer += (i - lP + 1);
}
return answer;
}
```
-
```javascript
```
- 주석대로 풀었었는데 뭔가 맘에 안 들어서 gpt 도움을 받았더니 `answer += (i - lP + 1);`로 피드백을 받았는데 이 부분이 이해가 가질 않아요 ,,!

[민영] 5-4. 연속부분수열2

---

04. 완전탐색(블루투포스)/02. 뒤집은 소수/김유경/index.js

✔ 문제 유형: 완전 탐색 (블루투포스)
✔ 문제 풀이 날짜: 2024.10.12 (토)
분석을 특별히 할 필요가 없는 것 같다.
소수를 판별할 때의 조건이 어떻게 될 지 생각해봐야하는 것 정도..?
일단 2보다는 커야하고, for문을 돌면서 나머지가 0이 되는게 있으면 소수가 아니니까 그렇게 판별하면 될 것 같다.
-> for문을 정의할 때 i의 초기값을 2로 두고, n < i 라고 하면 1과 자기자신은 빠지니까
- 일단 뒤집으려면 자연수를 나눠서 뒤집은 다음 붙여서 숫자로 변환하면 될 것 같음
- 뒤집어진 숫자를 가지고 소수 판별 함수를 거치도록 하면 되지 않을까?
```javascript
const reverseNumber = (n) =>
Number(n.toString().split("").reverse().join(""));
const checkIsDecimal = (n) => {
if (n < 2) return false;
for (let i = 2; i < n; i++) {
if (n % i === 0) return false;
}
return true;
};
// 뒤집고, isDecimal일 것만 남겨서 return
return arr.map(reverseNumber).filter(checkIsDecimal);
}
let arr = [32, 55, 62, 20, 250, 370, 200, 30, 100];
```
O(m * (d + n))
처음에는 뒤집은 애들을 모아둔 …

[김유경] 4-2 뒤집은 소수

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/김민영/index.js

✔ 문제 제목: 5-5. 최대 매출
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.12
-
```javascript
function solution(k, arr) {
let sum = 0;
for (i = 0; i < k; i++) {
sum += arr[i];
}
answer = sum;
for (i = k; i < arr.length; i++) {
sum = sum + arr[i] - arr[i - k];
answer = Math.max(answer, sum);
}
return answer;
}
```
-
```javascript
```
-

[민영] 5-5. 최대 매출

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/김민영/index.js

✔ 문제 제목: 5-6. 학습 회장(해쉬)
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.14
-
```javascript
let votes = new Map([
['A', 0],
['B', 0],
['C', 0],
['D', 0],
['E', 0]
]);
for (x of s) {
votes.set(x, votes.get(x) + 1);
}
let maxVotes = 0;
let winner = '';
for (let [key, value] of votes) {
if (value > maxVotes) {
maxVotes = value;
winner = key;
}
}
return winner;
}
```
-
```javascript
```
- 풀이 참고했습니다 😔

[민영] 5-6. 학습 회장(해쉬)

---

04. 완전탐색(블루투포스)/03. 멘토링/김유경/index.js

✔ 문제 제목: 멘토링
✔ 문제 유형: 완전 탐색 (블루투포스)
✔ 문제 풀이 날짜: 2024.10.13 (일)
- 모든 시험 결과에서 등수가 높은 애들만 멘토가 될 수 있을 때 조합의 수를 구해라
- 경우의 수를 먼저 구하고, 안될 때마다 빼는 식으로 구해보려고 했으나, 중복되는 경우를 처리하기 어려워서 다시 생각함
- 모든 시험에서의 가능한 조합을 구해서, 시험의 횟수만큼 중복되는 애들만 셀까 싶기도 했는데, 3중 반복문 맞나 싶었다.
- 학생 수는 먼저 주어지니까, 학생 수랑 경우에 수 먼저 구한 다음에 매 시험마다 indexOf가 크면 멘토 못하게 빼야하나..?
⇒ 결국에는 잘 못풀겠어서 gpt 선생님한테 답 받았습니다.
```js
function countMentoringPairs(N, M, testResults) {
let count = 0;
// 학생 간 가능한 모든 짝을 확인
for (let mentor = 1; mentor <= N; mentor++) {
for (let mentee = 1; mentee <= N; mentee++) {
if (mentor === mentee) continue;
let validPair = true;
console.log(mentor, mentee);
// 각 시험에서 mentor가 mentee보다 등수가 앞서는지 확인
for (let i = 0; i < M; i++) {
let mentorRank = testResults[i].indexOf(mentor);
let menteeRank = testResults[i].indexOf(mentee);
if …
```

[김유경] 4-3 멘토링

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/김민영/index.js

✔ 문제 제목: 5-7. 아나그램
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.16
-
```javascript
let aMap = new Map();
let bMap = new Map();
for (x of str1) {
if (aMap.has(x)) {
aMap.set(x, aMap.get(x) + 1)
} else {
aMap.set(x, 1)
}
}
for (y of str2) {
if (bMap.has(y)) {
bMap.set(y, bMap.get(y) + 1)
} else {
bMap.set(y, 1)
}
}
for ([key, value] of aMap) {
if (value !== bMap.get(key)) {
answer = 'NO'
break;
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 5-7. 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/김민영/index.js

✔ 문제 제목: 5-8. 모든 아나그램
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.19
-
```javascript
let tMap = new Map();
for (x of t) {
if (tMap.has(x)) {
tMap.set(x, tMap.get(x) + 1)
} else {
tMap.set(x, 1)
}
}
for (i = 0; i <= s.length - tMap.size; i++) {
let sMap = new Map();
let str = s.substr(i, tMap.size)
for (y of str) {
if (sMap.has(y)) {
sMap.set(y, sMap.get(y) + 1)
} else {
sMap.set(y, 1)
}
}
let cnt = 0;
for ([key, value] of sMap) {
if (value !== tMap.get(key)) {
break;
}
cnt += 1;
if (cnt === tMap.size) {
answer += 1;
}
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 5-8. 모든 아나그램

---

06. 자료구조(스택, 큐)/01. 올바른 괄호/김민영/index.js

✔ 문제 제목: 6-1. 올바른 괄호
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.21
-
```javascript
if (s.length % 2 !== 0) { return 'NO' }
let cnt = 0;
for (i = 0; i < s.length; i++) {
s[i] === '(' ? cnt += 1 : cnt -= 1;
}
return cnt === 0 ? 'YES' : 'NO'
}
```
-
```javascript
```
-

[민영] 6-1. 올바른 괄호

---

06. 자료구조(스택, 큐)/02. 괄호문자제거/김민영/index.js

✔ 문제 제목: 6-2. 괄호문자제거
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.23
-
```javascript
for (x of s) {
if (x === ')') {
while (answer.pop() !== '(');
} else {
answer.push(x);
}
}
return answer.join('');
}
```
-
```javascript
```
- 풀이 참고했습니다.

[민영] 6-2. 괄호문자제거

---

06. 자료구조(스택, 큐)/03. 크레인 인형뽑기(카카오)/김민영/index.js

✔ 문제 제목: 6-3. 크레인 인형뽑기(카카오)
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.25
-
```javascript
let basket = [];
for (i = 0; i < moves.length; i++) {
for (j = 0; j < board.length; j++) {
if (board[j][moves[i] - 1] !== 0) {
basket.push(board[j][moves[i] - 1]);
board[j][moves[i] - 1] = 0;
break;
}
}
if (basket.length > 1 && basket[basket.length - 2] === basket[basket.length - 1]) {
basket.pop();
basket.pop();
answer += 2;
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 6-3. 크레인 인형뽑기(카카오)

---

04. 완전탐색(블루투포스)/02. 뒤집은 소수/백지원/index.js

✔ 문제 유형: 완전탐색(블루투포스)
✔ 문제 풀이 날짜: 2024.10.04
주어진 숫자를 뒤집고 소수인 것 출력
- 소수 판별 함수 isPrime 함수 작성 - 2부터 Math.sqrt(num) 이하까지의 수로 나누어떨어지지 않으면 소수로 판별
- 배열의 숫자를 모두 뒤집음 - reverse()
- isPrime 함수를 호출해서 소수를 판별하고 answer 출력
```javascript
function isPrime(num) {
if (num < 2) return false;
for (let i = 2; i <= Math.sqrt(num); i++) {
if (num % i === 0) return false;
}
return true;
}
let revInt = parseInt(arr[i].toString().split("").reverse().join(""));
if (isPrime(revInt)) {
answer.push(revInt);
}
}
return answer;
}
let arr = [32, 55, 62, 20, 250, 370, 200, 30, 100];
```
O(n)
- reverse()

[지원] 4-2. 뒤집은 소수

---

06. 자료구조(스택, 큐)/04. 후위식 연산/김민영/index.js

✔ 문제 제목: 6-4. 후위식 연산
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.27
-
```javascript
for (let x of s) {
if (!isNaN(x)) {
answer.push(+x);
} else {
let rt = answer.pop();
let lt = answer.pop();
if (x === "+") {
answer.push(lt + rt);
} else if (x === "-") {
answer.push(lt - rt);
} else if (x === "*") {
answer.push(lt * rt);
} else if (x === "/") {
answer.push(lt / rt);
}
}
}
return +answer;
}
```
-
```javascript
```
- 풀이 참고했슴다

[민영] 6-4. 후위식 연산

---

04. 완전탐색(블루투포스)/02. 뒤집은 소수/백지원/index.js
04. 완전탐색(블루투포스)/03. 멘토링/백지원/index.js

✔ 문제 제목: 멘토링
✔ 문제 유형: 완전탐색
✔ 문제 풀이 날짜: 10.28
멘토 멘티 짝으로 나올 수 있는 수 구하기
- 멘토 등수 구하기
- 멘티 등수 구하기
- 등수 비교
```javascript
function solution(test) {
const N = test[0].length; // 학생 수
for (let mentor = 1; mentor <= N; mentor++) {
for (let mentee = 1; mentee <= N; mentee++) {
if (mentor !== mentee) {
let isMentorValid = true;
for (let i = 0; i < test.length; i++) {
const mentorRank = test[i].indexOf(mentor) + 1;
const menteeRank = test[i].indexOf(mentee) + 1;
if (mentorRank >= menteeRank) {
isMentorValid = false;
break;
}
}
if (isMentorValid) answer++;
}
}
}
return answer;
}
let arr = [
[3, 4, 1, 2],
[4, 3, 2, 1],
[3, 1, 4, 2],
];
```
O(N^3*M)
- 3412를 등수로 바꾸지 않고 숫자비교를 해서 계속 답이 틀리게 나왓다.
- 나보다 프로그램이 더 똑똑하니까 프로그램 욕하지 말 것..

[지원] 4-3. 멘토링

---

04. 완전탐색(블루투포스)/04. 졸업선물/백지원/index.js

✔ 문제 제목: 졸업선물
✔ 문제 유형: 완전탐색
예산 내에 선물을 줄 수 있는 최대 학생 수 구하기
- 예산 내 최대한 많은 학생에게 선물 주기 위해 오름차순 정렬
- 할인된 상품 먼저 구매
- 나머지 상품 구매
- 예산이 초과되기 전까지 count++
```javascript
// 상품가격 + 배송비 오름차순 (예산 내 최대한 많은 학생에게 선물을 주기 위해)
let sortArr = product.sort((a, b) => {
let totalA = a[0] + a[1];
let totalB = b[0] + b[1];
return totalA - totalB;
});
// idx번 학생 => 할인된 가격 적용
for (let idx = 0; idx < sortArr.length; idx++) {
let sum = 0;
let count = 0; // 선물 줄 수 있는 학생 수
sum += sortArr[idx][0] / 2 + sortArr[idx][1];
count++;
for (let i = 0; i < sortArr.length; i++) {
if (idx === i) continue;
sum += sortArr[i][0] + sortArr[i][1];
if (sum > m) break;
count++;
if (sum === m) break;
}
answer = Math.max(answer, count);
}
return answer;
}
let arr = [
[6, 6],
[2, …
```

[지원] 4-4. 졸업선물

---

04. 완전탐색(블루투포스)/04. 졸업선물/백지원/index.js
04. 완전탐색(블루투포스)/05. K번째 큰 수/백지원/index.js

✔ 문제 제목: K번째 큰 수
✔ 문제 유형: 완전탐색
카드 3장을 골라 더했을 때 K번째 큰 경우의 숫자 구하기
- Set으로 중복 제거 객체 생
- 3중 for문
- s를 배열로 변환
```javascript
let s = new Set();
for (let j = i + 1; j < n; j++) {
for (let l = j + 1; l < n; l++) {
s.add(arr[i] + arr[j] + arr[l]);
}
}
}
// s 배열로 변환
return [...s].sort((a, b) => b - a)[k - 1];
}
let arr = [13, 15, 34, 23, 45, 65, 33, 11, 26, 42];
console.log(solution(10, 3, arr));
```
O(N^3)
-

[지원] 4-5. K번째 큰 수

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/백지원/index.js

✔ 문제 제목: 공통원소구하기
✔ 문제 유형: 효율성
두 배열의 공통 원소 오름차순으로 구하기
- 두 배열 오름차순 정렬
- 포인터 p1, p2 정의
- 원소가 같으면 두 포인터 모두 증가
- arr1의 원소가 arr2의 원소보다 작으면 arr1의 포인터 증가
- 그 외 arr2의 포인터 증가
```javascript
let p1 = 0,
p2 = 0;
arr1.sort((a, b) => a - b);
arr2.sort((a, b) => a - b);
while (p1 < arr1.length && p2 < arr2.length) {
if (arr1[p1] === arr2[p2]) {
answer.push(arr1[p1]);
p1++;
p2++;
} else if (arr1[p1] < arr2[p2]) {
p1++;
} else {
p2++;
}
}
return answer;
}
let a = [1, 3, 9, 5, 2];
let b = [3, 2, 5, 7, 8];
```
O(N)
- 이중포문 사용 없이 할 수 있어서 시간 복잡도 개선 가능
- 5-1번도 수정하겟습니다 :)

[지원] 5-2. 공통원소구하기

---

04. 완전탐색(블루투포스)/04. 졸업선물/백지원/index.js
04. 완전탐색(블루투포스)/05. K번째 큰 수/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/백지원/index.js

✔ 문제 제목: 두 배열 합치기
✔ 문제 유형: 효율성
배열 합쳐서 오름차순으로 출력
- concat 함수로 배열 합치기
- 오름차순 정렬
```javascript
const newArr = arr1.concat(arr2).sort((a, b) => a - b);
console.log(newArr);
return answer;
}
let a = [1, 3, 5];
let b = [2, 3, 6, 7, 9];
```
O((N+M)log(N+M))
-

[지원] 5-1. 두 배열 합치기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/백지원/index.js

✔ 문제 제목: 최대 매출
✔ 문제 유형: 효율성 - 슬라이디윈도우
✔ 문제 풀이 날짜: 10.30
가장 큰 연속 3개 합
- sum 초기값 구하기
- 다음 sum과 이전 sum 중 더 큰 값 answer로 업데이트
```javascript
function solution(k, arr) {
let sum = 0;
for (let i = 0; i < k; i++) {
sum += arr[i];
}
answer = sum;
for (let i = k; i < arr.length; i++) {
sum += arr[i] - arr[i - k];
answer = Math.max(answer, sum);
}
return answer;
}
let a = [12, 15, 11, 20, 25, 10, 20, 19, 13, 15];
console.log(solution(3, a));
```
O(N)
-

[지원] 5-5. 최대 매출

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/백지원/index.js

✔ 문제 제목: 연속부분수열1
✔ 문제 유형: 효율성 
연속하는 수를 더했을 때 주어진 합의 값이 나오는 경우의 수
- p2 포인터 기준으로 증가시키기
- sum 값이 주어진 합보다 크면 p1 포인터가 가리키는 값을 뺌
- p1++
- sum과 주어진 합의 값이 같으면 answer 증가
```javascript
let p1 = 0;
let sum = 0;
for (let p2 = 0; p2 < arr.length; p2++) {
sum += arr[p2];
while (sum > m) {
sum -= arr[p1];
p1++;
}
if (sum === m) answer++;
}
return answer;
}
let a = [1, 2, 1, 3, 1, 1, 1, 2];
console.log(solution(6, a));
```
O(N)
- 처음에는 sum<m인 경우 포인터가 가리키는 값을 더하고 sum>m인 경우 sum을 0으로 초기화하고 포인터 값을 증가시키고, 그 외의 경우(sum===m)에는 answer++을 하는 로직을 작성
- sum을 0으로 초기화함으로써 중간에 놓치는 경우가 발생
- 포인터 하나만 사용하는 방식으로는 문제가 있음
- 바보엿다 흥,,

[지원] 5-3. 연속부분수열1

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/백지원/index.js

✔ 문제 제목: 연속부분수열2
✔ 문제 유형: 효율성
✔ 문제 풀이 날짜: 10.30
연속된 수열의 합이 m 이하인 경우
- sum이 주어진 합 m보다 큰 경우 p1 포인터에 해당하는 값을 -
- p1 증가
- 그 외 answer에 구간만큼 더하기 (이하이므로)
```javascript
let p1 = 0;
let sum = 0;
for (let p2 = 0; p2 < arr.length; p2++) {
sum += arr[p2];
while (sum > m) {
sum -= arr[p1];
p1++;
}
answer += p2 - p1 + 1;
}
return answer;
}
let a = [1, 3, 1, 2, 3];
console.log(solution(5, a));
```
O(N)
- 합이 정확히 M인 경우 카운트하는 이전 문제와는 달리
- M 이하인 모든 구간의 개수를 구하는 것은 answer++가 아닌 구간의 갯수를 이미하는 p2-p1+1을 answer에 더해야함
- 이 전 문제에서 sum>m인 경우 while문을 쓴 이유는 한 번 초과한 상태에서 구간을 여러 번 축소해야 할 수 있기 때문
- sum===m인 경우 if문을 쓴 이유는 m인 경우를 확인하고 한 번만 카운트해야하기 때문

[지원] 5-4. 연속부분수열2

---

06. 자료구조(스택, 큐)/05. 쇠막대기/김민영/index.js

✔ 문제 제목: 6-5. 쇠막대기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.10.29
-
```javascript
for (i = 0; i < s.length; i++) {
if (s[i] === '(') {
stack.push('(');
} else {
stack.pop();
if (s[i - 1] === '(') {
answer += stack.length;
} else {
answer += 1;
}
}
}
return answer;
}
```
-
```javascript
```
- 풀이 참고했슴다 ..

[민영] 6-5. 쇠막대기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/백지원/index.js

✔ 문제 제목: 아나그램
✔ 문제 유형: 효율성 - 해쉬
✔ 문제 풀이 날짜: 10.30
문자 구성이 같으면 YES, 아니면 NO 출력 
- 첫 번째 단어에 대해 key와 value 값 저장
- 두 번째 단어를 돌면서 첫 번째 단어에 해당 알파벳이 존재하지 않거나 갯수가 0인 경우 단어가 다르므로 NO 출력
- 그 외의 경우 value 값 -1
```javascript
let alpha1 = new Map();
for (let alpha of str1) {
if (alpha1.has(alpha)) {
alpha1.set(alpha, alpha1.get(alpha) + 1);
} else {
alpha1.set(alpha, 1);
}
}
for (let alpha of str2) {
if (!alpha1.has(alpha) || alpha1.get(alpha) === 0) {
return "NO";
}
alpha1.set(alpha, alpha1.get(alpha) - 1);
}
return answer;
}
let a = "AbaAeCe";
let b = "baeeACA";
```
O(N+M)
- 두 번째 포문 작성에서 막혔음 
- 같은 문자인지 확인할 때 비교 말고도 감소시켜서 확인할 수 있는 방법도 있다.
- 얼리리턴

[지원] 5-7. 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/백지원/index.js
06. 자료구조(스택, 큐)/01. 올바른 괄호/백지원/index.js
06. 자료구조(스택, 큐)/02. 괄호문자제거/백지원/index.js
06. 자료구조(스택, 큐)/03. 크레인 인형뽑기(카카오)/백지원/index.js

✔ 문제 제목: 크레인 인형뽑기(카카오)
✔ 문제 유형: 자료구조 - 스택
✔ 문제 풀이 날짜: 10.31
move에 따라 인형을 뽑고 스택에 같은 인형이 맞닿으면 인형 제거
그 때 제거된 인형의 총 갯수
- 해당 위치가 0이 아닌 경우(인형이 있는 경우)
- 스택의 가장 위에 위치한 것과 인형이 일치하면 pop하고 인형이 두 개 터지므로 answer += 2
- 일치하지 않으면 푸시
```javascript
for (let move of moves) {
let col = move - 1;
// 쌓여있는 상태 확인해야하므로 행 탐색
for (let row = 0; row < board.length; row++) {
if (board[row][col] !== 0) {
let doll = board[row][col];
board[row][col] = 0;
if (stack[stack.length - 1] === doll) {
stack.pop();
answer += 2;
} else {
stack.push(doll);
}
break; // board[row][col] !== 0가 성립하면 반복문 종료 => 인형을 뽑았으므로
}
}
}
return answer;
}
let a = [
[0, 0, 0, 0, 0],
[0, 0, 1, 0, 3],
[0, 2, 5, 0, 1],
[4, 2, 4, 4, 2],
[3, 5, 1, 3, 1],
];
let b = [1, 5, 3, 5, 1, 2, 1, 4]; …
```

[지원] 6-3. 크레인 인형뽑기(카카오)

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/04. 연속부분수열2/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/05. 최대 매출/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/백지원/index.js

✔ 문제 제목: 모든 아나그램
✔ 문제 유형: 효율성 - 투포인터, 해쉬, 슬라이딩윈도우
✔ 문제 풀이 날짜: 10.30
S단어에 T문자열과 아나그램이 되는 부분 문자열 개수 출력
부분 문자열은 연속된 문자열
- tMap 셋팅
- sMap len-1 만큼 셋팅
- 슬라이딩 윈도우로 탐색
- 새 문자 추가
- 두 해시맵이 같은지 비교하는 함수 작성
- 현재 윈도우와 T의 문자 빈도가 같으면 answer++
- 윈도우 맨 앞 문자 제거
```javascript
let tMap = new Map();
let sMap = new Map();
for (let char of t) {
tMap.set(char, (tMap.get(char) || 0) + 1);
}
let len = t.length;
for (let i = 0; i < len - 1; i++) {
sMap.set(s[i], (sMap.get(s[i]) || 0) + 1);
}
let p1 = 0;
for (let p2 = len - 1; p2 < s.length; p2++) {
sMap.set(s[p2], (sMap.get(s[p2]) || 0) + 1);
if (compareMaps(sMap, tMap)) answer++;
sMap.set(s[p1], sMap.get(s[p1]) - 1);
if (sMap.get(s[p1]) === 0) sMap.delete(s[p1]);
p1++;
}
return answer;
}
// 두 해시맵이 같은지 비교
function …
```

[지원] 5-8. 모든 아나그램

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/백지원/index.js
06. 자료구조(스택, 큐)/01. 올바른 괄호/백지원/index.js

✔ 문제 제목: 올바른 괄호
✔ 문제 유형: 자료구조 - 스택
✔ 문제 풀이 날짜: 10.31
괄호 쌍이 맞으면 YES, 맞지 않으면 NO 출력
- 왼쪽 괄호가 나올 때마다 스택에 추가
- 오른쪽 괄호를 만나면 스택 맨 위의 괄호를 꺼내 비교
- 스택이 비어있다면 올바른 괄호 X (괄호쌍이 안맞으므로)
- 문자열 모두 탐색한 뒤에도 스택에 괄호가 남아있다면 괄호 쌍이 맞지 않으므로 NO 출력 
```javascript
for (let char of s) {
if (char === "(") {
stack.push(char);
} else {
if (stack.length === 0) return "NO";
stack.pop();
}
}
return stack.length === 0 ? "YES" : "NO";
}
let a = "(()(()))(()";
console.log(solution(a));
```
O(N)
-

[지원] 6-1. 올바른 괄호

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/06. 학급 회장(해쉬)/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/07. 아나그램/백지원/index.js
05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/08. 모든 아나그램/백지원/index.js
06. 자료구조(스택, 큐)/01. 올바른 괄호/백지원/index.js
06. 자료구조(스택, 큐)/02. 괄호문자제거/백지원/index.js

✔ 문제 제목: 괄호문자제거
✔ 문제 유형: 자료구조 - 스택
✔ 문제 풀이 날짜: 10.31
괄호 포함 괄호 안의 문자 제거 후 남은 문자 출력 
- )를 만나면 (가 나올 때까지 모든 문자 제거
- 그 외에는 스택에 추가
- join()
```javascript
for (let char of s) {
if (char === ")") {
while (stack.pop() !== "(");
} else {
stack.push(char);
}
}
return stack.join("");
}
let str = "(A(BC)D)EF(G(H)(IJ)K)LM(N)";
```
O(N)
-

[지원] 6-2. 괄호문자제거

---

06. 자료구조(스택, 큐)/06. 공주구하기/김민영/index.js

✔ 문제 제목: 6-6. 공주구하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.1
-
```javascript
let arr = Array.from({ length: n }, (_, i) => i + 1);
while (arr.length > 1) {
arr.push(arr.shift());
}
arr.shift();
}
return arr[0];
}
```
-
```javascript
```
- 풀이 참고했슴다

[민영] 6-6. 공주구하기

---

06. 자료구조(스택, 큐)/04. 후위식 연산/백지원/index.js

✔ 문제 제목: 후위식 연산
✔ 문제 유형: 자료구조 - 스택
✔ 문제 풀이 날짜: 11.02
후위식 연산 결과 출력
- 빈 스택 생성
- 피연산자를 만나면 스택에 push
- 연산자를 만나면 두 개의 숫자를 pop하는데 먼저 pop한 숫자를 오른쪽 피연산자, 그 다음 pop한 숫자를 왼쪽 피연산자로 사용
- 계산 결과를 stack에 다시 push
- 스택에 남은 하나의 값이 최종 결과
```javascript
let answer;
for (let char of s) {
if (!isNaN(char)) {
stack.push(Number(char));
} else {
const right = stack.pop();
const left = stack.pop();
switch (char) {
case "+":
stack.push(left + right);
break;
case "-":
stack.push(left - right);
break;
case "*":
stack.push(left * right);
break;
case "/":
stack.push(left / right);
break;
}
}
}
return stack.pop();
}
let str = "352+*9-";
```
O(N)
-

[지원] 6-4. 후위식 연산

---

06. 자료구조(스택, 큐)/06. 공주구하기/김민영/index.js

✔ 문제 제목: 6-6. 공주구하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.3
-
```javascript
let arr = Array.from({ length: n }, (_, i) => i + 1);
while (arr.length > 1) {
arr.push(arr.shift());
}
arr.shift();
}
return arr[0];
}
```
-
```javascript
```
- 불필요한 변수 있는 거 발견해서 다시 올려용 ,,

[민영] 6-6. 공주구하기 수정

---

06. 자료구조(스택, 큐)/05. 쇠막대기/백지원/index.js

✔ 문제 제목: 쇠막대기
✔ 문제 유형: 자료구조 - 스택 
✔ 문제 풀이 날짜: 11.03
쇠막대기를 레이저로 잘랐을 때 생기는 쇠막대기 조각 수
- (를 만나면 stack에 push
- )를 만나면 pop하고
- 이전이 (인 경우 스택의 길이만큼 조각 추가
- 이전이 )인 경우 +1
```javascript
if (s[i] === "(") {
stack.push("(");
} else {
stack.pop();
if (s[i - 1] === "(") {
answer += stack.length;
} else {
answer += 1;
}
}
}
return answer;
}
let a = "()(((()())(())()))(())";
console.log(solution(a));
```
O(N)
- 저런 생각을 어떻게 하지..?
- 저런 생각 == 
```javascript
if (s[i - 1] === "(") {
answer += stack.length;
} else {
answer += 1;
}
```

[지원] 6-5. 쇠막대기

---

06. 자료구조(스택, 큐)/05. 쇠막대기/백지원/index.js
06. 자료구조(스택, 큐)/06. 공주구하기/백지원/index.js

✔ 문제 제목: 공주구하기
✔ 문제 유형: 자료구조 - 큐
✔ 문제 풀이 날짜: 11.03
마지막 남은 왕자 번호 구하기
- 큐에 왕자 번호 삽입
- 큐에 왕자의 번호가 1개가 될 때까지 반복
- 앞의 왕자를 빼서 뒤로 넣기를 k-1번 반복
- 큐 젤 앞 번호 빼기 == k번째 외치는 왕자 제거
- 큐 첫번째 인덱스 값 출
```javascript
const queue = [];
// for문 대신 (i=요소의 인덱스)
// const queue = new Array(n).fill(0).map((_, i) => i + 1);
for (let i = 1; i <= n; i++) {
queue.push(i);
}
while (queue.length > 1) {
queue.push(queue.shift());
}
queue.shift();
}
return queue[0];
}
console.log(solution(8, 3));
```
O(N) => 초기화
O(N-1) => while문
O(K-1) => for문
O(N) => queue.shift()
O(N) + O((N-1)*(K-1)*N) = O(N*K)
- 옛날에 백준에서 풀었던 조세퍼스(? 문제 비슷한 것 같다.

[지원] 6-6. 공주구하기

---

06. 자료구조(스택, 큐)/05. 쇠막대기/백지원/index.js
06. 자료구조(스택, 큐)/06. 공주구하기/백지원/index.js
06. 자료구조(스택, 큐)/07. 교육과정설계/백지원/index.js

✔ 문제 제목: 교육과정설계
✔ 문제 유형: 자료구조 - 큐
✔ 문제 풀이 날짜: 11.04
해당 필요대로 순서와 과목을 무조건 필수적으로 듣는지 확인
- queue 배열을 need로 생성
- 포문을 돌면서 큐에 포함되어 있고,
- 큐에서 하나를 뽑았을 때의 문자와 일치하지 않으면 NO 출력
- 큐의 길이가 0보다 크면 필수과목을 다 들은 것이 아니므로 NO 출력
- 그 외는 YES
```javascript
const queue = Array.from(need);
for (let char of plan) {
if (queue.includes(char)) {
if (char != queue.shift()) return "NO";
}
}
if (queue.length > 0) return "NO";
return answer;
}
let a = "CBA";
let b = "CBDAGE";
```
O(M) => 큐 초기
O(N) => 포문
O(K) => queue.includes(char)
O(M+N*K)
-

[지원] 6-7. 교육과정설계

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/백지원/index.js

✔ 문제 제목: 버블정렬
✔ 문제 유형: 정렬과 그리디
✔ 문제 풀이 날짜: 11.05
오름차순 정렬
- 최소값을 가진 인덱스 정의
- 다음 인덱스 값부터 비교하여 최소값을 가진 인덱스 업뎃
- 최소값 인덱스가 변경되었다면 위치 바꾸기
```javascript
let minIdx = i; // 최소값을 가진 인덱스
for (let j = i + 1; j < arr.length; j++) {
if (arr[minIdx] > arr[j]) {
minIdx = j;
}
}
if (minIdx !== i) {
let temp = arr[minIdx];
arr[minIdx] = arr[i];
arr[i] = temp;
}
}
return arr;
}
let arr = [13, 5, 11, 7, 23, 15];
```
O(N^2)
- 여기서 푼건 버블 정렬이 아니라 선택 정렬이고 선택 정렬에 올린게 버블 정렬 풀이였다. 🍃

[지원] 7-2. 버블정렬

---

06. 자료구조(스택, 큐)/07. 교육과정설계/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/백지원/index.js

✔ 문제 제목: 선택정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 11.04
숫자가 작은 것부터 큰 순으로 배열
- 앞 뒤 숫자 비교 후 앞이 크다면 위치 바꾸기
```javascript
for (let i = 0; i < arr.length - 1; i++) {
for (let j = 0; j < arr.length - i - 1; j++) {
if (arr[j] > arr[j + 1]) {
let temp = arr[j];
arr[j] = arr[j + 1];
arr[j + 1] = temp;
}
}
}
return answer;
}
let arr = [13, 5, 11, 7, 23, 15];
```
O(N^2)
-

[지원] 7-1. 선택정렬

---

06. 자료구조(스택, 큐)/07. 교육과정설계/김민영/index.js

✔ 문제 제목: 6-7. 교육과정설계
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.4
-
```javascript
let x = [];
for (i of plan) {
if (need.indexOf(i) !== -1) {
x.push(i)
}
}
return x.join('') === need ? 'YES' : 'NO'
}
```
-
```javascript
```
-

[민영] 6-7. 교육과정설계

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/백지원/index.js

✔ 문제 제목: 좌표 정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 11.06
좌표 정렬
- sort하는데 x좌표가 같으면 y좌표 오름차순 정렬
- 그 외는 x좌표 오름차순 정렬
```javascript
arr.sort((a, b) => {
if (a[0] === b[0]) {
return a[1] - b[1];
}
return a[0] - b[0];
});
return arr;
}
let arr = [
[2, 7],
[1, 3],
[1, 2],
[2, 5],
[3, 6],
];
```
O(NlogN)
-

[지원] 7-7. 좌표 정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js

✔ 문제 제목: Special Sort
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 11.05
음수를 앞으로, 양수를 뒤로
- 음수 필터링
- 양수 필터링
- 차례대로 반환
```javascript
const negative = arr.filter((num) => num < 0);
const positive = arr.filter((num) => num > 0);
return [...negative, ...positive];
}
let arr = [1, 2, 3, -3, -2, 5, 6, -6];
```
O(N)
-

[지원] 7-3. Special Sort

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/백지원/index.js

✔ 문제 제목: 삽입정렬
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 11.05
삽입정렬로 오름차순 정렬
- 현재값 지정
- j가 0보다 크고 특정 값이 현재 값보다 크면 현재 값에 특정 값 삽입
- j--
- while문이 끝나면 j+1 자리에 current 값 삽입
```javascript
// i = 현재 삽입할 요소
let current = arr[i];
let j = i - 1; // 0 1 2 3 4
while (j >= 0 && arr[j] > current) {
arr[j + 1] = arr[j];
j--;
}
arr[j + 1] = current;
}
return answer;
}
let arr = [11, 7, 5, 6, 10, 9];
```
O(N^2) => 1 + 2 + 3 + ... + (n - 1) 
-

[지원] 7-4. 삽입정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/백지원/index.js

✔ 문제 제목: LRU
✔ 문제 유형: 캐싱 
✔ 문제 풀이 날짜: 11.06
LRU 알고리즘 구현
- 캐시 안에 존재하면 기존 위치에서 제거
- 해당 캐시의 크기를 넘어서면 제일 앞 제거
- 캐시안에 존재하던, 존재하지 않던, 크기를 넘어서던 공통으로 값 추가
- reverse
```javascript
function solution(size, arr) {
let answer = Array.from({ length: size }, () => 0);
// for (let i = 0; i < arr.length; i++) {
//   if (!answer.includes(arr[i])) {
//     answer.push(arr[i]);
//   } else {
//     for (let j = 0; j < answer.length; j++)
//       if (answer[j] === arr[i]) {
//         answer.splice(j, 1);
//         answer.push(arr[i]);
//       }
//   }
// }
// return answer.reverse().splice(0, size);
const idx = answer.indexOf(arr[i]);
if (idx !== -1) {
answer.splice(idx, 1);
} else if (answer.length >= size) {
answer.shift();
}
}
return …
```

[지원] 7-5. LRU

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/백지원/index.js

✔ 문제 제목: 장난꾸러기 현수
✔ 문제 유형: 정렬
✔ 문제 풀이 날짜: 11.06
현수와 현수와 자리 바꾼 친구의 번호 출력
- 키 순으로 배열 정렬
- 원래 배열과 비교했을 때 값이 다른 인덱스 구하기
- 번호이므로 인덱스+1 출력
```javascript
const sortedArr = [...arr].sort((a, b) => a - b);
if (arr[i] !== sortedArr[i]) {
answer.push(i + 1);
}
}
return answer;
}
let arr = [120, 125, 152, 130, 135, 135, 143, 127, 160];
```
O(NlogN) => sort()
O(N) => 포문
O(NlogN)
- 앞뒤 비교만으로 안되는 이유는 자리바꿈이 연속적이지 않은 경우는 잡아내지 못하기 때문

[지원] 7-6. 장난꾸러기 현수

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/01. 선택정렬/김민영/index.js

✔ 문제 제목: 7-1. 선택정렬
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.6
-
```javascript
return arr.sort((a, b) => a - b);
}
```
-
```javascript
```
-

[민영] 7-1. 선택정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/02. 버블정렬/김민영/index.js

✔ 문제 제목: 7-2. 버블정렬
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.8
-
```javascript
let noSwaps;
for (let i = arr.length; i > 0; i--) {
noSwaps = true;
for (let j = 0; j < i - 1; j++) {
if (arr[j] > arr[j + 1]) {
noSwaps = false;
}
}
if (noSwaps) break;
}
return arr;
}
```
-
```javascript
```
- 풀이 참고했서요

[민영] 7-2. 버블정렬

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/김민영/index.js

✔ 문제 제목: 7-3. Special Sort
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.11
-
```javascript
let negative = [];
let positive = [];
for (num of arr) {
num < 0 ? negative.push(num) : positive.push(num);
}
return [...negative, ...positive];
}
```
-
```javascript
```
-

[민영] 7-3. Special Sort

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/백지원/index.js

✔ 문제 제목: 이분검색
✔ 문제 유형: 이분검색
✔ 문제 풀이 날짜: 11.14
정렬된 상태에서의 배열에서 주어진 숫자가 몇 번째에 존재하는지 출력
- 오름차순 정렬
- start, end, mid 포인트 선언
- start, end 포인트가 서로 앞뒤가 바뀌지 않는 동안 반복
- target과 mid 포인트 값이 일치하면 인덱스가 아닌 번째를 출력해야하므로 mid+1
- target이 mid 포인트 값보다 작으면 end값을 mid 앞으로 변경
- 그 외에는 start 값을 mid 뒤로 변경
- target 값을 못찾으면 -1 반환 
```javascript
const sortArr = arr.sort((a, b) => a - b);
let start = 0;
let end = sortArr.length - 1;
while (start <= end) {
let mid = parseInt((start + end) / 2);
if (target === arr[mid]) return mid + 1;
else {
if (target < arr[mid]) {
end = mid - 1;
} else {
start = mid + 1;
}
}
}
return -1;
}
let arr = [23, 87, 65, 12, 57, 32, 99, 81];
console.log(solution(32, arr));
```
O(NlogN) => sort()
O(logN) => 이분탐색 (탐색범위가 반씩 좁혀지기 때문)
O(NlogN)
- start와 end가 변할 때마다 …

[지원] 7-10. 이분검색

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/09. 결혼식/백지원/index.js

✔ 문제 제목: 결혼식
✔ 문제 유형: 그리디 알고리즘
✔ 문제 풀이 날짜: 11.14
결혼식에 특정 시간의 최대 인원 수 구하기
- 친구가 도착하면 +1, 친구가 떠나면 -1
- 정렬을 할 때 도착 시간이 똑같으면 떠나는 시간 순으로 정렬
- 그 외에는 도착 시간 순으로 정렬
- for문을 돌면서 +1, -1계산
- answer 반환
```javascript
function solution(times) {
let currentCnt = 0;
// 친구가 도착하면 +1, 떠나면 -1
// 모든 친구의 도착 시간과 떠나는 시간이 섞여서 저장됨
let timeline = [];
for (let [start, end] of times) {
timeline.push([start, 1]);
timeline.push([end, -1]);
}
timeline.sort((a, b) => {
if (a[0] === b[0]) return a[1] - b[1];
return a[0] - b[0];
});
for (let [time, type] of timeline) {
currentCnt += type;
answer = Math.max(answer, currentCnt);
}
return answer;
}
let arr = [
[14, 18],
[12, 15],
[15, 20],
[20, 30],
[5, 14],
];
```
O(NlogN)
- 같은 시간에 도착과 떠남 이벤트가 있을 때 도착 이벤트를 먼저 …

[지원] 7-9. 결혼식

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/03. Special Sort/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/04. 삽입정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/백지원/index.js
07. 정렬과 그리디, 결정알고리즘(이분검색)/08. 회의실 배정/백지원/index.js

✔ 문제 제목: 회의실 배정
✔ 문제 유형: 그리디 알고리즘
✔ 문제 풀이 날짜: 11.06
회의실 최대한 많이 배정하도록
- 종료시간 기준으로 오름차순 정렬
- 현재 종료 시간을 초기값으로
- 이전 종료 시간이 특정 회의의 시작시간보다 작거나 같으면 종료시간 업데이트
- answer++
```javascript
function solution(meeting) {
meeting.sort((a, b) => a[1] - b[1]);
let beforeTime = meeting[0][1];
for (let i = 1; i < meeting.length; i++) {
if (meeting[i][0] >= beforeTime) {
beforeTime = meeting[i][1];
answer++;
}
}
return answer;
}
let arr = [
[1, 4],
[2, 3],
[3, 5],
[4, 6],
[5, 7],
];
```
O(NlogN)
-

[지원] 7-8. 회의실 배정

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/백지원/index.js

✔ 문제 제목: 뮤직비디오
✔ 문제 유형: 이분검색
✔ 문제 풀이 날짜: 11.15
DVD의 최소 길이 구하기
- dvd 최소 1개이므로 1로 초기화
- 현재 dvd에 song을 더 담을 수 없으면 새 dvd 추가
- 그렇지 않으면 현재 dvd에 담긴 곡들의 합에 song만큼 추가
- 만약 dvd 개수가 주어진 dvd 수보다 작거나 같으면 answer을 mid로 준 후에 end 값을 mid 앞으로 땡겨서 더 작은 수로 쪼갤 수 있는지 확인
- 그 외에는 start 값을 뒤로 늘림
```javascript
let answer;
let start = Math.max(...songs);
let end = songs.reduce((a, b) => a + b, 0);
while (start <= end) {
let mid = parseInt((start + end) / 2);
let dvdCnt = 1;
let currentSum = 0; // 현재 DVD에 담긴 곡들의 합
for (let song of songs) {
if (currentSum + song > mid) {
// 현재 DVD에 더 담을 수 없으면 새 DVD 추가
dvdCnt++;
currentSum = song;
} else {
currentSum += song;
}
}
if (dvdCnt <= m) {
answer = mid;
end = mid - 1;
} else {
start = mid + 1;
}
}
return answer;
}
let arr = [1, 2, 3, 4, 5, 6, 7, …
```

[지원] 7-11. 뮤직비디오

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/05. LRU/김민영/index.js

✔ 문제 제목: 7-5. LRU
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.17
-
```javascript
function solution(size, arr) {
let answer = Array.from({ length: size }, () => 0);
for (work of arr) {
if (answer.includes(work)) {
answer.splice(answer.indexOf(work), 1)
answer.unshift(work);
} else {
answer.unshift(work);
answer.pop();
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 7-5. LRU

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/백지원/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/01. 재귀함수/백지원/index.js

✔ 문제 제목: 재귀함수
✔ 문제 유형: 재귀함수
✔ 문제 풀이 날짜: 11.20
n을 입력하면 1부터 n까지 차례로 출력
- L이 0이 되면 return
- 그 외에는 DFS(L-1) 실행
- L 출력
```javascript
if (L === 0) return;
DFS(L - 1);
console.log(L);
}
DFS(n);
}
solution(3);
```
O(1)
-

[지원] 8-1. 재귀함수

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/백지원/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/01. 재귀함수/백지원/index.js
08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/백지원/index.js

✔ 문제 제목: 이진수 출력
✔ 문제 유형: 재귀
✔ 문제 풀이 날짜: 11.20
이진수 출력
- n이 0이 아닌 경우에 한하여 n/2 DFS 재귀호출
- 나머지는 answer에 push
- join
```javascript
function DFS(n) {
if (n === 0) return;
DFS(Math.floor(n / 2));
answer.push(n % 2);
}
DFS(n);
return answer.join("");
}
console.log(solution(11));
```
O(log2(N))
-

[지원] 8-2. 이진수 출력

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/06. 장난꾸러기 현수/김민영/index.js

✔ 문제 제목: 7-6. 장난꾸러기 현수
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.20
-
```javascript
let sortedArr = [...arr].sort((a, b) => a - b);
if (arr[i] !== sortedArr[i]) {
answer.push(i + 1);
}
}
return answer;
}
```
-
```javascript
```
-

[민영] 7-6. 장난꾸러기 현수

---

04. 완전탐색(블루투포스)/04. 졸업선물/김유경/index.js

✔ 문제 제목: 졸업 선물
✔ 문제 유형: 완전 탐색 (블루투포스)
✔ 문제 풀이 날짜: 2024.10.14 (월)
- 선생님이 사줄 수 있는 최대 학생 수
- 제일 비싼 선물에 반값 할인 쿠폰 사용 가능
- 상품 금액 비싼 선물에 쿠폰 쓸 수 있도록 선물값을 기준으로 내림차순 정렬
- index가 0인 (상품 제일 비싼) 금액에 할인 쿠폰 쓰고, 나머지는 선물값 + 배송비 구하기
- 오름차순으로 정렬해서 싼 친구들 먼저 사주기 (제일 많이 사주기 위해서)
- 총합 금액을 더하면서 count++ 해주다가, 넘어가면 멈춰서 count return 해주기
```jsx
let count = 0; // 구매할 수 있는 학생 수
let price = 0; // 사용하는 금액
// 배송비 + 할인된 물품 금액
const salePrice = (a, b) => {
return a / 2 + b;
};
// 물품 금액 합
const totalPrice = (a, b) => {
return a + b;
};
// 상품 가격 비싼놈 맨 앞에 세워서 반값 쿠폰 쓰고, 나머지는 물품 값 합계 구한 다음 오름차순으로 정렬
const array = product
.sort((a, b) => b[0] - a[0])
.map((n, index) => {
if (index === 0) {
return salePrice(n[0], n[1]);
}
return totalPrice(n[0], n[1]);
})
.sort((a, b) => a - b);
// 앞에서부터 더해서, 예산을 …
```

[김유경] 4-4 졸업선물 문제풀이

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/07. 좌표 정렬/김민영/index.js

✔ 문제 제목: 7-7. 좌표 정렬
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.11.22
-
```javascript
let answer = arr.sort((a, b) => {
if (a[0] === b[0]) return a[1] - b[1];
return a[0] - b[0];
});;
return answer;
}
```
-
```javascript
```
- 풀이 참고했습니다

[민영] 7-7. 좌표 정렬

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/07. 섬나라 아일랜드(BFS)/윤아영/index.js
09. 그래프와 탐색(DFS, BFS;너비우선탐색)/07. 섬나라 아일랜드(DFS)/윤아영/index.js

✔ 문제 제목: 섬나라 아일랜드
✔ 문제 유형: BFS DFS
✔ 문제 풀이 날짜: 24-09-28
- 섬은 1로 표시되고 상하좌우, 대각선으로 연결되어 있다.
- 지도에서 섬은 몇 개 인가?
- BFS: while 반복문을 돌면서 상하좌우대각선에서 1인 좌표를 queue에 push하고, queue에서 shift한 값을 이용해 주변 연결 땅이 있는지 확인한다.
- DFS: 재귀를 돌면서 주변에 땅이 있다면 해당 땅의 상하좌우대각선을 확인한다.
```javascript
// BFS
function solution(board) {
const dx = [-1, 0, 1, -1, 1, -1, 0, 1];
const dy = [-1, -1, -1, 0, 0, 1, 1, 1];
const queue = [];
for (let i = 0; i < board.length; i++) {
for (let j = 0; j < board[i].length; j++) {
if (board[i][j] === 1) {
queue.push([i, j]);
board[i][j] = 0;
answer++;
while (queue.length) {
const [x, y] = queue.shift();
for (let k = 0; k < dx.length; k++) {
const nx = x + dx[k];
const ny = y + dy[k];
if (board[nx]?.[ny] === 1) {
queue.push([nx, ny]);
board[nx][ny] = 0;
}
}
}
}
}
}
return …
```

[윤아영] 9-7 9-8 섬나라 아일랜드 (풀이 참조)

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/06. 송아지 찾기(BFS)/윤아영/index.js

✔ 문제 제목: 송아지 찾기
✔ 문제 유형: BFS
✔ 문제 풀이 날짜: 24-09-27
- 나는 앞으로 한 칸, 뒤로 한 칸, 앞으로 5칸 움직일 수 있다.
- 송아지에게 가는 방법 중 가장 적게 움직인 수를 출력
- BFS과 메모이제이션을 활용한다.
- 시작점부터 queue에 쌓는다.
- queue.length === 0일 될 때까지 반복
- queue의 length만큼 반복하면서 queue.shfit를 진행하여 해당 값의 자식 노드로 [ n-1, n+1, n+5 ] 값을 돌면서 송아지의 위치와 비교
- 송아지 위치와 같다면 현재 깊이 + 1 값을 반환
- 각 자식노드가 0보다 크고 10000보다 작거나 같으며 메모이제이션되지 않은 값이라면 queue에 추가
- while이 한바퀴 돌때마다 깊이에 1 추가
```javascript
function solution(s, e) {
const ch = new Array(10001).fill(0);
const queue = [];
let depth = 0;
queue.push(s);
ch[s] = 1;
while (queue.length) {
const len = queue.length;
for (let i = 0; i < len; i++) {
const v = queue.shift();
for (let nv of [v - 1, v + 1, v + 5]) {
if (nv === e) return depth + 1;
if (nv > 0 && nv <= 10000 && ch[nv] === 0) {
ch[nv] = 1; …
```

[윤아영] 9-6 송아지 찾기

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/05. 이진트리 넓이우선탐색(BFS)/윤아영/index.js

✔ 문제 제목: 이진트리 넓이우선 탐색
✔ 문제 유형: BFS
✔ 문제 풀이 날짜: 24-09-19
- 이진트리를 넓이우선탐색해보세요.
<image src='https://github.com/user-attachments/assets/b69c21d0-7205-4c2f-bbf7-78dcd7a7a27f' width=50%/>
- 해당 깊이의 값을 큐에 push한다.
- 큐의 첫번째 값을 shift해서 해당 값의 자식 노드들을 큐에 push한다.
- 큐의 길이가 0이 될 때까지 반복한다.
```javascript
function solution() {
const queue = [1];
while (queue.length) {
const v = queue.shift();
answer += v + " ";
for (const nv of [v * 2, v * 2 + 1]) {
if (nv > 7) break;
queue.push(nv);
}
}
return answer;
}
console.log(solution());
```
O(n)
- 처음에는 함수에 깊이를 같이 전달하여 이중 배열로 만들었습니다.
```javascript
function solution() {
const answer = []
const DFS = (index, depth) => {
if (index > 7) return;
answer[depth] = answer[depth] ? [...answer[depth], index] : [index];
DFS(index * 2, depth + 1);
DFS(index * 2 + …
```

[윤아영] 9-5 이진트리 넓이우선탐색

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/04. 미로탐색/윤아영/index.js

✔ 문제 제목: 미로 탐색
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-09-18
- 7 * 7 격자판 미로를 탈출하는 경로의 가지수를 출력
- 상하좌우를 배열의 형태로 할당한다.
- 해당 좌표에서 상하좌우를 비교하며 0이라면 다음 좌표로 재귀 호출한다.
- 해당 좌표가 [6, 6]이라면 anwer에 1을 더한다.
- 메모이제이션을 활용하여 이미 다녀간 값을 O(1)의 시간복잡도로 확인할 수 있도록 한다.
```javascript
function solution(board) {
const moves = [
[0, -1],
[0, 1],
[-1, 0],
[1, 0],
];
const copyBoard = Array.from({ length: board.length }, (_, i) => [...board[i]]);
const DFS = (point) => {
if (point[0] === board.length - 1 && point[1] === board.length - 1) {
answer++;
return;
}
for (const move of moves) {
const newPointX = point[0] + move[0];
const newPointY = point[1] + move[1];
if (copyBoard[newPointX]?.[newPointY] !== 0) {
continue;
}
copyBoard[point[0]][point[1]] = 1;
DFS([newPointX, newPointY]);
copyBoard[point[0]][point[1]] = 0; …
```

[윤아영] 9-4 미로탐색

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/13. 수열 추측하기/윤아영/index.js

✔ 문제 제목: 수열 추측하기
✔ 문제 유형: DFS
✔ 문제 풀이 날짜: 24-09-12
- 가장 윗줄에 1부터 N까지의 숫자가 한 개씩 적혀 있다.
- 파스칼의 삼각형처럼 위의 두개를 더한 값이 저장되게 된다.
- N과 가장 밑에 잇는 숫자가 주어져 있을 때 가장 윗줄에 있는 숫자를 구하는 프로그램을 작성하시오
- 답이 여러가지가 나오는 경우에는 사전순으로 가장 앞에 오는 것을 출력한다.
- 파스칼 삼각형을 활용하여 계수를 구한다.
- 계수에 값을 더해 합계가 F와 같다면 해당 값이 정답
```javascript
function solution(n, f) {
let answer,
flag = 0;
let dy = Array.from(Array(11), () => Array(11).fill(0));
let ch = Array.from({ length: n + 1 }, () => 0);
let p = Array.from({ length: n }, () => 0);
let b = Array.from({ length: n }, () => 0);
const combi = (n, r) => {
if (dy[n][r] > 0) return dy[n][r];
if (n === r || r === 0) return 1;
return (dy[n][r] = combi(n - 1, r - 1) + combi(n - 1, r));
};
function DFS(L, sum) {
if (flag) return;
if (L === n && sum === f) {
answer = p.slice();
flag = 1;
} else { …
```

[윤아영] 8-13 수열 추측하기 (복습예정)

---

09. 그래프와 탐색(DFS, BFS;너비우선탐색)/02. 경로탐색(DFS)/윤아영/index.js

✔ 문제 제목: 경로 탐색
✔ 문제 유형: 인접행렬
✔ 문제 풀이 날짜: 24-09-12
- 방향그래프가 주어지면 1번 정점에서 N번 정점으로 가는 모든 경로의 가지 수를 출력
- 인접 행렬을 생성한다.
- 재귀적으로 돌면서 N번에 도착할 수 있으면 anwer의 값을 1추가한다.
```javascript
const graph = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(0));
for (const [s, e] of arr) {
graph[s][e] = 1;
}
const DFS = (node, route) => {
if (graph[node][n] === 1) {
answer++;
}
for (let i = 1; i < n; i++) {
if (route.includes(i)) continue;
if (graph[node][i] === 0) continue;
DFS(i, [...route, i]);
}
};
DFS(1, [1]);
return answer;
}
let arr = [[1, 2], [1, 3], [1, 4], [2, 1], [2, 3], [2, 5], [3, 4], [4, 2], [4, 5]];
console.log(solution(5, arr));
```
- 인접 행렬을 만드는 것은 사실 봉찬님이 올려주신 거 보면서 생성하였습니다.
- includes로 확인안하고 할 수는 없을까? 라는 생각이 드네요

[윤아영] 9-2 경로 탐색

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/10. 이분검색/김민영/index.js

✔ 문제 제목: 7-10. 이분검색
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.12.3
-
```javascript
return arr.sort((a, b) => a - b).indexOf(target) + 1;
}
```
-
```javascript
```
-

[민영] 7-10. 이분검색

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/11. 뮤직비디오/김민영/index.js

✔ 문제 제목: 7-11. 뮤직비디오
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.12.5
-
```javascript
let left = Math.max(...songs);
let right = songs.reduce((a, b) => a + b, 0);
const countDVDs = (capacity) => {
let count = 1;
let sum = 0;
for (let song of songs) {
if (sum + song > capacity) {
count++;
sum = song;
} else {
sum += song;
}
}
return count;
};
let mid = Math.floor((left + right) / 2);
if (countDVDs(mid) <= m) {
answer = mid;
right = mid - 1;
} else {
left = mid + 1;
}
}
return answer;
}
```
-
```javascript
```
- 풀이 참고했습니다.

[민영] 7-11. 뮤직비디오

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/01. 두 배열 합치기/김유경/index.js

✔ 문제 제목: 두 배열 합치기
✔ 문제 유형: 두 포인터
✔ 문제 풀이 날짜: 2024.12.17
정렬된 두 배열을 합쳐서 오름차순으로 출력
배열에 두 배열을 넣은 후 sort로 정렬하면 되지 않을까?
```javascript
let p1  = 0;
let p2 = 0;
// 두 배열이 끝날 때까지 반복
while (p1 < arr1.length && p2 < arr2.length){
// 정렬된 배열을 만들기 위한 조건문
// 첫 번째 배열의 값이 작으면 추가
if(arr1[p1] < arr2[p2]){
answer.push(arr1[p1])
p1++
} else {
// 두 번째 배열의 값이 작으면 추가
answer.push(arr2[p2]);
p2++
}
}
// 둘 중 한 배열이 먼저 끝나면 더 긴 배열 넣어주기
while(p1 < arr1.length) answer.push(arr1[p1++])
while(p2 < arr2.length) answer.push(arr2[p2++])
return answer
}
let a = [1, 3, 5];
let b = [2, 3, 6, 7, 9];
```
O(N + M)
- 직관적으로 쉽게 풀어봤지만, 이 문제에 적합한 알고리즘을 사용해서 푸는게 학습에 더 도움이 될 것 같아서 다시 풀었다.
```javascript
return [...arr1, …
```

[유경] 5-1 두 배열 합치기

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/02. 공통원소구하기/김유경/index.js

✔ 문제 제목: 공통 원소 구하기
✔ 문제 유형: 해시 ? 투 포인터로도 풀리긴 함
✔ 문제 풀이 날짜: 2024.12.21
두 배열을 입력 받아서, 두 배열의 교집합을 구하고 정렬해서 출력하면 된다
배열 받은 걸 순회하면서 filter하면 될 것 같다 !
```javascript
const setArr1 = new Set(arr1)
const setArr2 = new Set(arr2)
const common = [...setArr1].filter((n) => setArr2.has(n))
return common.sort((a,b)=> a -b);
}
let a = [1, 3, 9, 5, 2];
let b = [3, 2, 5, 7, 8];
```
O(N + M + P log P)
- 일단 직관적으로 떠오르는 배열 + filter 이걸로 풀었었는데, 다른 방법으로도 해보고 싶어서 투 포인터로도 풀어봤다.
```javascript
const answer = []
// 정렬된 배열로 만들기
arr1.sort((a,b)=> a-b)
arr2.sort((a,b)=> a-b)
let i = 0;
let j = 0;
while(i < arr1.length && j < arr2.length){
if(arr1[i] === arr2[j]){
answer.push(arr1[i])
i++;
j++;
} else if (arr1[i] < arr2[j]){
i++;
} …
```

[유경] 5-2 : 공통 원소 구하기

---

07. 정렬과 그리디, 결정알고리즘(이분검색)/12. 마구간 정하기/김민영/index.js

✔ 문제 제목: 7-12. 마구간 정하기
✔ 문제 유형:
✔ 문제 풀이 날짜: 24.12.10
-
```javascript
function solution(c, stable) {
stable.sort((a, b) => a - b);
let start = 1;
let end = stable[stable.length - 1] - stable[0];
const isPlacementPossible = (distance) => {
let count = 1;
let lastPosition = stable[0];
for (i = 1; i < stable.length; i++) {
if (stable[i] - lastPosition >= distance) {
count++;
lastPosition = stable[i];
if (count >= c) return true;
}
}
return false;
};
while (start <= end) {
let mid = Math.floor((start + end) / 2);
if (isPlacementPossible(mid)) {
answer = mid;
start = mid + 1;
} else {
end = mid - 1;
}
}
return answer;
}
```
-
```javascript
```
- 풀이 참고했습니다.

[민영] 7-12. 마구간 정하기

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/01. 재귀함수/김민영/index.js

✔ 문제 제목: 8-1. 재귀함수
✔ 문제 유형:
✔ 문제 풀이 날짜: 25.1.1
-
```javascript
if (L === 0) return;
DFS(L - 1);
console.log(L);
}
DFS(n);
}
```
-
```javascript
```
-

[민영] 8-1. 재귀함수

---

05. 효율성(투포인터 알고리즘, 슬라이디윈도우, 해쉬)/03. 연속부분수열1/김유경/index.js

✔ 문제 제목: 연속 부분수열 1
✔ 문제 유형: 슬라이딩 윈도우
✔ 문제 풀이 날짜: 2025.01.04
- 슬라이딩 윈도우를 이용해서 연속 부분수열의 합이 M이 될때 count++를 해주고, 다음 구간으로 넘어가면 될 것 같다.
- 슬라이딩 윈도우로 세팅을 해두고, sum이 m보다 작으면 end++, sum이 m보다 크면 start++ 한 후에 sum-= arr[start] 하면서 범위를 조절하고 그러던 중 sum === m이 되면 count++를 해서 다 순회했을 때 count를 반환하면 되지 않을까?
```jsx
let start = 0;
let end = 0;
let currentSum = 0;
let count = 0;
while (end < arr.length) {
// 윈도우 확장: end 포인터의 값을 더함
currentSum += arr[end];
// 현재 합이 m을 초과하면 윈도우를 축소
while (currentSum > m && start <= end) {
currentSum -= arr[start];
start += 1;
}
// 현재 합이 정확히 m이라면 카운트를 증가
if (currentSum === m) {
count += 1;
}
// end 포인터를 이동하여 윈도우를 확장
end += 1;
}
return count;
}
let a = [1, 2, 1, 3, 1, 1, 1, 2];
console.log(solution(6, a));
```
O(N)

[유경] 5-3. 연속부분수열1

---

08. 재귀함수와 완전탐색(DFS;깊이우선탐색)/02. 이진수 출력(재귀)/김민영/index.js

✔ 문제 제목: 8-2. 이진수 출력(재귀)
✔ 문제 유형:
✔ 문제 풀이 날짜: 25.1.14
-
```javascript
if (L === 0) return;
DFS(parseInt(L / 2));
answer += L % 2;
}
DFS(n);
return answer;
}
```
-
```javascript
```
- 풀이 참고했습니다.

[민영] 8-2. 이진수 출력(재귀)
